function metrics=evaluate_stage4a3_open_set_metrics(decisions,labels)
%EVALUATE_STAGE4A3_OPEN_SET_METRICS Offline scoring only.
%   The matcher never calls this function. Truth labels are joined here,
%   after observation-only decisions have been produced.
if numel(decisions)~=numel(labels), error('stage4a3:ScoreAlignment','Decisions and labels must align.'); end
template=struct('scenario_id','','grid_id','','category','','sample_count',0, ...
 'truth_coverage_rate',NaN,'truth_coverage_num',0,'truth_coverage_den',0, ...
 'truth_coverage_wilson_low',NaN,'truth_coverage_wilson_high',NaN, ...
 'strict_accuracy_given_covered',NaN,'strict_num',0,'strict_den',0,'strict_wilson_low',NaN,'strict_wilson_high',NaN, ...
 'equivalent_class_accuracy_given_covered',NaN,'equivalent_num',0,'equivalent_den',0,'equivalent_wilson_low',NaN,'equivalent_wilson_high',NaN, ...
 'in_library_reject_rate',NaN,'in_library_reject_num',0,'in_library_reject_den',0,'in_library_reject_wilson_low',NaN,'in_library_reject_wilson_high',NaN, ...
 'false_unique_rate_given_nonunique',NaN,'false_unique_num',0,'false_unique_den',0,'false_unique_wilson_low',NaN,'false_unique_wilson_high',NaN, ...
 'out_of_library_false_accept_rate',NaN,'out_of_library_false_accept_num',0,'out_of_library_false_accept_den',0,'out_of_library_false_accept_wilson_low',NaN,'out_of_library_false_accept_wilson_high',NaN, ...
 'out_of_library_reject_rate',NaN,'out_of_library_reject_num',0,'out_of_library_reject_den',0,'out_of_library_reject_wilson_low',NaN,'out_of_library_reject_wilson_high',NaN, ...
 'mean_best_distance',NaN,'mean_margin',NaN,'config_hash','');
metrics=repmat(template,0,1);
keys=unique(strcat({labels.scenario_id},'|',{labels.grid_id},'|',{labels.category}));
for k=1:numel(keys)
 ix=strcmp(strcat({labels.scenario_id},'|',{labels.grid_id},'|',{labels.category}),keys{k}); a=labels(ix); z=decisions(ix);
 covered=strcmp({a.coverage_status},'covered'); rejected=startsWith({z.decision},'reject_');
 nonunique=cellfun(@(x)contains(x,','),{z.best_equivalence_class});
 strict=covered & strcmp({z.best_topology_id},{a.truth_topology_id});
 equiv=covered & cellfun(@(x,y)contains(x,y),{z.best_equivalence_class},{a.truth_topology_id});
 [cr,cn,cd,cl,ch]=ratio(sum(covered),numel(covered));
 [sr,sn,sd,sl,sh]=ratio(sum(strict),sum(covered));
 [er,en,ed,el,eh]=ratio(sum(equiv),sum(covered));
 [ir,in_,id_,il,ih]=ratio(sum(covered&rejected),sum(covered));
 [fr,fn,fd,fl,fh]=ratio(sum(nonunique&strcmp({z.decision},'unique_topology')),sum(nonunique));
 out=~covered;
 [far,fan,fad,fal,fah]=ratio(sum(out&~rejected),sum(out));
 [oar,oan,oad,oal,oah]=ratio(sum(out&rejected),sum(out));
 metrics(k)=struct('scenario_id',a(1).scenario_id,'grid_id',a(1).grid_id,'category',a(1).category,'sample_count',numel(a), ...
  'truth_coverage_rate',cr,'truth_coverage_num',cn,'truth_coverage_den',cd,'truth_coverage_wilson_low',cl,'truth_coverage_wilson_high',ch, ...
  'strict_accuracy_given_covered',sr,'strict_num',sn,'strict_den',sd,'strict_wilson_low',sl,'strict_wilson_high',sh, ...
  'equivalent_class_accuracy_given_covered',er,'equivalent_num',en,'equivalent_den',ed,'equivalent_wilson_low',el,'equivalent_wilson_high',eh, ...
  'in_library_reject_rate',ir,'in_library_reject_num',in_,'in_library_reject_den',id_,'in_library_reject_wilson_low',il,'in_library_reject_wilson_high',ih, ...
  'false_unique_rate_given_nonunique',fr,'false_unique_num',fn,'false_unique_den',fd,'false_unique_wilson_low',fl,'false_unique_wilson_high',fh, ...
  'out_of_library_false_accept_rate',far,'out_of_library_false_accept_num',fan,'out_of_library_false_accept_den',fad,'out_of_library_false_accept_wilson_low',fal,'out_of_library_false_accept_wilson_high',fah, ...
  'out_of_library_reject_rate',oar,'out_of_library_reject_num',oan,'out_of_library_reject_den',oad,'out_of_library_reject_wilson_low',oal,'out_of_library_reject_wilson_high',oah, ...
  'mean_best_distance',mean([z.best_distance]),'mean_margin',mean([z.margin]), ...
  'config_hash',getfield_default(a(1),'config_hash',''));
end
end

function v=getfield_default(s,name,default)
if isfield(s,name),v=s.(name);else,v=default;end
end

function [rate,num,den,lo,hi]=ratio(num,den)
if den==0,rate=NaN;lo=NaN;hi=NaN;return,end
rate=num/den; z=1.95996398454005; den2=den; center=(rate+z^2/(2*den2))/(1+z^2/den2); half=z*sqrt(rate*(1-rate)/den2+z^2/(4*den2^2))/(1+z^2/den2);lo=max(0,center-half);hi=min(1,center+half);
end
