function test_stage7a10r1_integrity(root,run_id)
%TEST_STAGE7A10R1_INTEGRITY Verify paired identities, scope and denominators.
    if nargin<1||isempty(root),root=fileparts(fileparts(mfilename('fullpath')));end
    if nargin<2||isempty(run_id),run_id='formal1';end
    addpath(fullfile(root,'src'),fullfile(root,'tests'));
    folder=fullfile(root,'results','data','stage7a_10_r1','formal',run_id);
    samples=readtable(fullfile(folder,'samples.csv'),'TextType','string');
    derived=readtable(fullfile(folder,'derived_statistics.csv'),'TextType','string');
    pairs=readtable(fullfile(folder,'paired_changes.csv'),'TextType','string');
    meta=readtable(fullfile(folder,'metadata.csv'),'TextType','string');
    assert(height(meta)==1&&meta.T_seed==950000000&& ...
        meta.physical_graphs==8&&meta.repetitions_per_graph==30&& ...
        meta.physical_observations==240&&meta.parallel_workers==0&& ...
        meta.audit_baseline_commit=="b76972dceb17e46710afcd8b10b8e3f19b9f0a31", ...
        'R.1 identity/seed/sample size differs from protocol.');
    assert(height(samples)==12960&&height(pairs)==8640&& ...
        numel(unique(samples.noise_seed))==240&& ...
        all(ismember(samples.scenario,["baseline", "node_port_bias", ...
        "node_acquisition_load_drift"])), ...
        'R.1 paired experiment row count differs.');
    assert(all(samples.used_clean_rms_delta>=0)&& ...
        all(samples.effective_on_used_observation== ...
            (samples.used_clean_rms_delta>0)), ...
        'Recorded effect flag disagrees with clean CFR distance.');
    assert(~any(samples.scenario=="baseline" & ...
        samples.effective_on_used_observation), ...
        'Baseline cannot be physically perturbed.');
    assert(~any(samples.method=="A_H50" & ...
        samples.effective_on_used_observation)&& ...
        ~any(samples.method=="E_H50_Zin50" & ...
        samples.effective_on_used_observation), ...
        'Node-state pressure leaked into H50 or source Zin.');
    assert(~any(samples.method=="D_adaptive" & ...
        samples.selected_view==0 & samples.effective_on_used_observation), ...
        'An empty first-stage set cannot use a changed node observation.');
    assert(all(samples.truth_in_set<=samples.truth_in_library)&& ...
        ~any(samples.correct_unique & samples.false_unique), ...
        'Truth/set/unique accounting mismatch.');
    check(derived,'baseline','D_adaptive','original_three', ...
        'in_library','correct_unique',90);
    check(derived,'baseline','D_adaptive','original_three', ...
        'out_library','false_unique',150);
    check(derived,'baseline','D_adaptive','expanded_six', ...
        'in_library','truth_in_set',180);
    check(derived,'baseline','D_adaptive','expanded_six', ...
        'out_library','nonempty_set',60);
    check(derived,'baseline','D_adaptive','diagnostic_pair', ...
        'in_library','correct_unique',60);
    assert(all(pairs.state_changed==(pairs.baseline_state~=pairs.perturbed_state)), ...
        'Paired state-change indicator differs from paired states.');
    assert(nnz(pairs.method=="D_adaptive" & pairs.effective)>0, ...
        'No adaptive observations were effectively stressed.');
    test_stage7a10_result_integrity(root,'confirm1');
    views=readtable(fullfile(root,'results','data','stage7a_10_r1', ...
        'audit','confirm1_view_counts.csv'),'TextType','string');
    assert(~any(views.view_index==3 & views.n>0)&& ...
        ~any(views.view_index==7 & views.n>0), ...
        'Historical adaptive method selected a termination view.');
    groups=unique(views(:,{'condition','library'}));
    old_app=readtable(fullfile(root,'results','data','stage7a_10_r1', ...
        'audit','confirm1_applicability.csv'),'TextType','string');
    for j=1:height(groups)
        mask=views.condition==groups.condition(j)& ...
            views.library==groups.library(j);
        raw=old_app.condition==groups.condition(j)& ...
            old_app.library==groups.library(j);
        assert(sum(views.n(mask))==nnz(raw), ...
            'Historical per-view counts do not cover the raw D rows.');
    end
    archive=fullfile(root,'results','data','stage7a_10_r1','archive');
    for filename={'artifact_manifest.csv','source_inventory.csv'}
        path=fullfile(archive,filename{1});
        if exist(path,'file')==2
            manifest=readtable(path,'TextType','string');
            for k=1:height(manifest)
                p=fullfile(root,strrep(char(manifest.relative_path(k)),'/',filesep));
                assert(exist(p,'file')==2,'R.1 inventoried file is missing.');
                info=dir(p);
                assert(info.bytes==manifest.size_bytes(k)&& ...
                    strcmp(stage4a7_2_r2_sha256_file(p),char(manifest.sha256(k))), ...
                    'R.1 artifact SHA-256 differs from manifest.');
            end
        end
    end
    fprintf('PASS test_stage7a10r1_integrity: %d samples, %d pairs\n', ...
        height(samples),height(pairs));
end
function check(z,scenario,method,library,pop,metric,n)
    r=z(z.scenario==scenario & z.method==method & z.library==library & ...
        z.truth_group=="ALL" & z.population==pop & z.metric==metric,:);
    assert(height(r)==1&&r.denominator==n&&r.applicability=="applicable", ...
        'R.1 metric uses an incorrect population denominator.');
    [lo,hi]=stage7a4_wilson(r.numerator,n);
    assert(abs(r.proportion-r.numerator/n)<1e-14&& ...
        abs(r.wilson_low95-lo)<1e-14&& ...
        abs(r.wilson_high95-hi)<1e-14, ...
        'R.1 Wilson interval differs from numerator/denominator.');
end
