function test_stage3_band_configs()
%TEST_STAGE3_BAND_CONFIGS Check dual-band design configuration boundaries.
    root_dir = fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root_dir, 'src'));
    addpath(fullfile(root_dir, 'config'));

    before = default_config(root_dir);
    stage3a = stage3a_config(root_dir);
    [cfg_nb, cfg_bb, meta] = stage3_band_configs(root_dir);
    after = default_config(root_dir);

    assert(meta.nb_requires_protocol_confirmation && ...
        meta.bb_is_existing_project_assumption, ...
        'Dual-band configuration provenance flags are missing.');
    assert(isequal(before.frequency_hz, after.frequency_hz) && ...
        isequal(before.ofdm, after.ofdm), ...
        'stage3_band_configs changed default configuration state.');
    assert(isequal(cfg_nb.frequency_band_hz, [42e3, 472e3]) && ...
        isempty(cfg_nb.frequency_grid_hz) && isnan(cfg_nb.fs_hz) && ...
        strcmp(cfg_nb.cp_source, '待与实际 NB-PLC PHY 确认'), ...
        'NB configuration must remain explicitly incomplete until PHY confirmation.');
    assert(isequal(cfg_bb.frequency_band_hz, [2e6, 30e6]) && ...
        cfg_bb.fs_hz == 64e6 && cfg_bb.nfft == 4096 && ...
        cfg_bb.cp_samples == stage3a.ofdm.cyclic_prefix_samples && ...
        cfg_bb.cp_samples == 256 && ...
        cfg_bb.stage2_baseline_cp_samples == before.ofdm.cyclic_prefix_samples && ...
        strcmp(cfg_bb.cp_source, 'stage3a_project_simulation_assumption') && ...
        numel(cfg_bb.frequency_grid_hz) == before.ofdm.num_active_subcarriers, ...
        'BB project configuration does not match the existing baseline.');
    assert(cfg_bb.validation.frequency_grid_valid && ...
        cfg_bb.validation.subcarrier_spacing_consistent && ...
        ~cfg_bb.validation.physical_delay_available && ...
        ~cfg_bb.validation.cp_coverage_evaluable, ...
        'BB frequency/CP validation did not preserve the sampled-CFR boundary.');
    assert(~cfg_nb.validation.ready_for_dual_band_experiment && ...
        ~cfg_bb.validation.ready_for_dual_band_experiment, ...
        'Dual-band experiment must remain blocked until protocol/physical-delay inputs are fixed.');
    assert(all(cfg_bb.frequency_grid_hz >= cfg_bb.frequency_band_hz(1)) && ...
        all(cfg_bb.frequency_grid_hz <= cfg_bb.frequency_band_hz(2)), ...
        'BB active frequencies are outside the configured band.');
    assert(isfield(cfg_nb, 'parameter_vector') && ...
        isfield(cfg_bb, 'shared_network_interface') && ...
        ~isempty(cfg_bb.observation_types), ...
        'Shared H(f;G,theta) and observation interfaces are incomplete.');
    assert(any(strcmp(cfg_nb.reference_basis, ...
        'P12 local review compares 42--472 kHz NB-PLC conditions')) && ...
        any(strcmp(cfg_bb.reference_basis, ...
        'P09 discusses 1.1--30 MHz and 30--86 MHz separately in standard-specific context')), ...
        'Dual-band literature reference identifiers are inconsistent with the paper notes.');
    fprintf('  PASS Stage3 dual-band configuration boundaries and default isolation\n');
end
