function test_stage7a6_candidate_space(root)
%TEST_STAGE7A6_CANDIDATE_SPACE Identity, reachability, budget and leakage.
    if nargin<1||isempty(root)
        root=fileparts(fileparts(mfilename('fullpath')));
    end
    addpath(fullfile(root,'src'),fullfile(root,'config'));
    base=default_config(root);
    cfg=stage7a6_config(base,'smoke',17);
    [pool,base_ix,grammar,truth,groups,steps]=stage7a6_candidate_space(base);
    assert(numel(pool)==17&&numel(truth)==19&&grammar.max_branches==3);
    assert(all(steps(groups.reachable)==2)&& ...
        all(isinf(steps(groups.grammar_out))));
    ids={pool.topology_id};
    assert(isequal(sort(ids(base_ix)),sort({'G001','G002','G003'})));
    assert(all(ismember({'EXT_111','EXT_021'},ids)));
    pool_sigs=arrayfun(@(x)stage6b_network_signature(x.network),pool, ...
        'UniformOutput',false);
    for j=groups.grammar_out
        assert(~any(strcmp(pool_sigs, ...
            stage6b_network_signature(truth(j).network))), ...
            'Grammar-out truth leaked into the search pool.');
        theta=struct('main_length_scale',1,'branch_length_scale',1, ...
            'branch_load_scale',1,'first_segment_scale',1, ...
            'source_impedance_ohm',50,'receiver_impedance_ohm',50);
        z=stage7a4_forward_state(truth(j).network,theta,base, ...
            cfg.frequency_hz,cfg.state_50);
        assert(all(isfinite(z.H_endpoint))&&all(isfinite(z.Zin)), ...
            'The forward model failed on a grammar-out truth graph.');
    end
    bank=stage7a5_template_bank(pool,base,cfg);
    assert(bank.forward_calls==17*numel(cfg.main_scale_grid)* ...
        numel(cfg.load_scale_grid));
    sample=stage7a5_generate_split(truth,groups.reachable(1),base,cfg, ...
        811000000,1,'unit',false);
    sigma=[0.03 1];
    b3=stage7a6_score_observation(sample.observed,pool,bank,base,cfg, ...
        base_ix,1,sigma,3,[]);
    assert(b3.search_truncated&&numel(b3.candidate_ids)==3);
    b17=stage7a6_score_observation(sample.observed,pool,bank,base,cfg, ...
        base_ix,1,sigma,17,[]);
    assert(b17.optimizer_evaluations>=sum(b17.distances>=0));
    assert(b17.profile_evaluations>=numel(b17.candidate_ids));
    fake=struct('kind','C','budget',3,'bank_identity',bank.identity, ...
        'search_identity',bank.search_identity,'views',1);
    caught=false;
    try
        stage7a6_score_observation(sample.observed,pool,bank,base,cfg, ...
            base_ix,1,sigma,5,fake);
    catch ME
        caught=strcmp(ME.identifier,'stage7a6:CalibrationIdentityMismatch');
    end
    assert(caught,'Mismatched calibration budget was not rejected.');
    oldcfg=stage7a5_config(base,'smoke');
    [oldpool,oldbase]=stage7a5_candidate_pool(base);
    oldbank=stage7a5_template_bank(oldpool,base,oldcfg);
    oldsample=stage7a5_generate_split(oldpool,oldbase(2),base,oldcfg, ...
        812000000,1,'unit',false);
    p5=stage7a5_expand_candidates(oldsample.observed,oldpool,oldbank, ...
        base,oldcfg,oldbase,1,sigma,oldcfg.frequency_train_indices,10);
    p6=stage7a6_expand_candidates(oldsample.observed,oldpool,oldbank, ...
        base,oldcfg,oldbase,1,sigma,10);
    assert(isequal(p5.active_ids,p6.active_ids)&& ...
        isequal(p5.generated_ids,p6.generated_ids)&& ...
        max(abs(p5.distances-p6.distances))<1e-12&& ...
        p5.search_truncated==p6.search_truncated, ...
        'Stage 7A.6 editor changed the frozen Stage 7A.5 decisions.');
    fprintf('PASS test_stage7a6_candidate_space\n');
end
