function test_stage7a10r1_statistics(root)
%TEST_STAGE7A10R1_STATISTICS Catch mixed-denominator and zero-n errors.
    if nargin<1||isempty(root),root=fileparts(fileparts(mfilename('fullpath')));end
    addpath(fullfile(root,'src'),fullfile(root,'config'));
    scenarios=repmat("T20",4,1);methods=repmat("D_adaptive",4,1);
    libraries=repmat("original_three",4,1);
    truths=["G001";"G003";"MIRROR_M3";"EXT_021"];
    in=[true;true;false;false];correct=[true;false;false;false];
    false_unique=[false;false;true;false];in_set=[true;true;false;false];
    set_size=[1;2;1;0];states=["UNIQUE_CONFIDENT"; ...
        "MULTIPLE_AMBIGUOUS";"UNIQUE_CONFIDENT";"REJECTED"];
    samples=table(scenarios,methods,libraries,truths,in,correct, ...
        false_unique,in_set,set_size,states, ...
        'VariableNames',{'scenario','method','library','truth_id', ...
        'truth_in_library','correct_unique','false_unique', ...
        'truth_in_set','candidate_set_size','decision_state'});
    z=stage7a10r1_derive_statistics(samples);
    check(z,'ALL','in_library','correct_unique',1,2);
    check(z,'ALL','in_library','truth_in_set',2,2);
    check(z,'ALL','out_library','false_unique',1,2);
    check(z,'ALL','out_library','nonempty_set',1,2);
    check(z,'ALL','all','UNIQUE_CONFIDENT',2,4);
    check(z,'ALL','out_library','REJECTED',1,2);
    miss=z(z.truth_group=="G001" & z.population=="out_library" & ...
        z.metric=="false_unique",:);
    assert(height(miss)==1&&miss.denominator==0&& ...
        miss.applicability=="not_applicable"&&isnan(miss.proportion)&& ...
        isnan(miss.wilson_low95)&&isnan(miss.wilson_high95), ...
        'Empty out-of-library group must be not applicable.');
    base=default_config(root);cfg=stage7a10r1_config(base,'smoke');
    [graphs,~,~]=stage7a4_fixed_topologies(base);
    theta=struct('main_length_scale',1,'branch_length_scale',1, ...
        'branch_load_scale',1,'first_segment_scale',1, ...
        'source_impedance_ohm',50,'receiver_impedance_ohm',50);
    [standard,observed]=stage7a4_measure_views(graphs(3).network, ...
        theta,base,cfg,970000001,20,struct());
    for kind={'node_port_bias','node_acquisition_load_drift'}
        [clean,y,calls]=stage7a10r1_measure_views(graphs(3).network, ...
            theta,base,cfg,970000001,20,kind{1},0.01);
        assert(calls==numel(cfg.states)&&isequal(clean{5},standard{5})&& ...
            isequal(y{5},observed{5})&&isequal(clean{6},standard{6})&& ...
            isequal(y{6},observed{6})&& ...
            any(abs(clean{14}-standard{14})>0), ...
            'Perturbation must change node view but preserve first H50/Zin.');
        for v=[3 7 9]
            assert(isequal(clean{v},standard{v})&&isequal(y{v},observed{v}), ...
                'Node-state perturbation leaked into a termination view.');
        end
    end
    fprintf('PASS test_stage7a10r1_statistics: denominators, n/a and physical perturbation\n');
end
function check(z,truth,pop,metric,k,n)
    x=z(z.truth_group==truth & z.population==pop & z.metric==metric,:);
    [lo,hi]=stage7a4_wilson(k,n);
    assert(height(x)==1&&x.numerator==k&&x.denominator==n&& ...
        abs(x.proportion-k/n)<1e-14&& ...
        abs(x.wilson_low95-lo)<1e-14&& ...
        abs(x.wilson_high95-hi)<1e-14, ...
        'Population denominator or Wilson interval is incorrect.');
end
