function result=test_stage4a6_3_1_r1_metrics_and_identity(root)
%TEST_STAGE4A6_3_1_R1_METRICS_AND_IDENTITY Metric semantics and hard gates.
    if nargin<1||isempty(root),root=fileparts(fileparts(mfilename('fullpath')));end
    addpath(fullfile(root,'src'),fullfile(root,'config'));
    % Parameter OOD does not make a topology false-unique when truth is unique.
    l=label('a','out_of_domain','G001','G001',1,true);
    d=decision('a','unique_topology','G001','parameter_out_suspected');
    m=stage4a6_3_1_r1_evaluate_metrics(d,l);
    assert(m.false_unique_numerator==0);assert(isfinite(m.false_unique_rate)&&m.false_unique_rate==0);
    % A nonunique truth class with a singleton output is false-unique.
    l(2)=label('b','in_domain','G002','G002,G005',2,false);
    d(2)=decision('b','unique_topology','G002','parameter_in_domain');
    m=stage4a6_3_1_r1_evaluate_metrics(d,l);
    assert(m.false_unique_numerator==1);assert(m.false_unique_denominator==2);
    % Missing equivalence labels make the metric not evaluable.
    l3=label('c','in_domain','G001','',NaN,NaN);
    d3=decision('c','unique_topology','G001','parameter_in_domain');
    m2=stage4a6_3_1_r1_evaluate_metrics(d3,l3);
    assert(isnan(m2.false_unique_rate));assert(m2.false_unique_evaluable_count==0);
    % Separate topology and parameter selective risks.
    assert(isfinite(m.topology_acceptance_coverage));
    assert(isfinite(m.parameter_decision_coverage));
    assert(isfield(m,'end_to_end_selective_risk'));

    p_in=parameter_evidence('in_domain',false);p_out=parameter_evidence('out_suspected',true);
    e1=member('G002',true,p_in);e2=member('G005',true,p_out);
    conf=struct('decision','equivalence_class','accepted_topology_set','G002,G005', ...
        'accepted_member_ids',{{'G002','G005'}},'best_topology_id','G002');
    pm=struct('calibration_status','calibrated','parameter_thresholds', ...
        struct('parameter_name','main_length_scale','status','calibrated', ...
        'absolute_improvement_threshold',0.01,'relative_improvement_threshold',0.01, ...
        'sensitivity_floor',0.1));
    a=stage4a6_3_1_r1_aggregate_class_evidence(conf,[e1,e2],pm, ...
        'A6_3_M3_joint_diagnostic','compat','parameter-cal');
    assert(strcmp(a.parameter_domain_status,'parameter_domain_indeterminate'));
    % An unreliable member cannot yield a deterministic OOD conclusion.
    e2=member('G005',false,p_out);
    a=stage4a6_3_1_r1_aggregate_class_evidence(conf,[e1,e2],pm, ...
        'A6_3_M3_joint_diagnostic','compat','parameter-cal');
    assert(strcmp(a.parameter_domain_status,'parameter_domain_indeterminate'));
    % The adapter fails closed if either calibration identity is missing.
    bad=struct('compatibility_hash','compat','topology_calibration_hash','');
    assert_throws_local(@() stage4a6_3_1_r1_confirm_with_frozen_stage4a5_1( ...
        {},struct('compatibility_hash','compat'),{},bad,struct(),'compat','topo'), ...
        'stage4a6_3_1_r1:TopologyCalibrationMismatch');
    % The parameter profile adapter fails closed on parameter calibration identity.
    pmodel=struct('compatibility_hash','compat', ...
        'parameter_calibration_hash','good');
    assert_throws_local(@() stage4a6_3_1_r1_profile_all_accepted_members( ...
        {},[],conf,{},struct(),struct(),struct(),pmodel,'compat','bad', ...
        'A6_3_M3_joint_diagnostic'), ...
        'stage4a6_3_1_r1:ParameterCalibrationMismatch');
    fprintf('ALL STAGE 4A.6.3.1-R.1 METRIC/IDENTITY TESTS PASSED\n');
    result=struct('name','test_stage4a6_3_1_r1_metrics_and_identity','status','passed');
end

function r=label(id,truth_type,truth,eq,n,unique_flag)
    r=struct('sample_id',id,'category','test','truth_topology_id',truth, ...
        'truth_equivalence_set',eq,'truth_equivalence_member_count',n, ...
        'truth_unique_under_observation',unique_flag,'equivalence_audit_hash','eq', ...
        'equivalence_configuration_hash','eq','parameter_domain_truth',truth_type, ...
        'physical_scenario_id',['p_' id],'parameter_vector_hash',['p_' id], ...
        'noiseless_cfr_hash',['c_' id],'observation_hash',['c_' id]);
end
function r=decision(id,status,set,pstatus)
    r=struct('sample_id',id,'method_id','m','decision',status,'topology_status',status, ...
        'topology_set',set,'accepted_topology_set',set,'parameter_domain_status',pstatus);
end
function p=parameter_evidence(status,outside)
    p=struct('parameter_name','main_length_scale','active',true,'profile_status','indeterminate', ...
        'in_domain_min_distance',0.2,'extended_min_distance',0.01, ...
        'absolute_improvement',0.2,'relative_improvement',0.5, ...
        'extended_optimum',1.2,'extended_optimum_outside',outside, ...
        'boundary_behavior','upper_boundary','outward_decrease',outside, ...
        'flatness_metric',0.1,'relative_dynamic_range',0.1,'absolute_dynamic_range',0.1, ...
        'valid_point_fraction',1,'local_sensitivity',1,'multistart_evaluated',false, ...
        'multistart_consistent','not_applicable','profile_reliable',true, ...
        'reliability_reason','test');
    p.profile_status=status;
end
function e=member(id,reliable,p)
    e=struct('topology_id',id,'profile_reliable',reliable,'profile_computed',true, ...
        'optimizer_converged',true,'parameter_evidence',p);
end
function assert_throws_local(fun,id)
    threw=false;try,fun();catch ME,threw=true;assert(strcmp(ME.identifier,id));end
    assert(threw);
end
