function test_stage4a7_2_candidate_closure()
%TEST_STAGE4A7_2_CANDIDATE_CLOSURE Targeted tests for Stage 4A.7.2.
    root=fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root,'src'),fullfile(root,'config'));
    cfg=default_config(root);

    grammar=stage4a1_config(cfg).generator;
    legacy=generate_radial_topology_candidates(grammar);
    assert(numel(legacy)==7,'Legacy candidate count changed.');

    spec=struct('node_ids',{{'A','B','C','D'}},'source_node_id','A', ...
        'receiver_node_id','D','allowed_edges',{{'A','B';'A','C';'A','D';'B','C';'B','D';'C','D'}}, ...
        'required_edges',{{'A','B'}},'forbidden_edges',{{'C','D'}}, ...
        'maximum_degree',3,'maximum_candidate_count',128,'radial_only',true, ...
        'require_connected',true,'prior_source','synthetic_demo_prior_not_field_data', ...
        'edge_prior_cost',[0;3;1;2;4;5]);
    [full,~]=generate_engineering_topology_candidates(spec);
    assert(all([full.edge_count]==numel(spec.node_ids)-1) && all([full.node_count]==numel(spec.node_ids)), ...
        'Engineering candidates must expose deterministic node/edge counts.');
    [top,~]=generate_topk_topology_candidates(spec,numel(full));
    assert(isequal({full.canonical_graph_key},{top.canonical_graph_key}), ...
        'Lazy Top-K does not reproduce full enumeration at K=all.');
    assert(numel(unique({top.canonical_graph_key}))==numel(top), ...
        'Lazy Top-K returned duplicate canonical keys.');
    [top_all,top_audit]=generate_topk_topology_candidates(spec,numel(full)+10);
    assert(numel(top_all)==numel(full) && top_audit.exhausted, ...
        'Top-K did not report exhausted when K exceeded the feasible set.');
    assert(top_audit.states_expanded>0 && top_audit.states_pushed>0, ...
        'Top-K search statistics were not generated by the search.');

    shuffled=spec; shuffled.allowed_edges=spec.allowed_edges([6 2 4 1 5 3],:);
    shuffled.edge_prior_cost=spec.edge_prior_cost([6 2 4 1 5 3]);
    [top_shuffled,~]=generate_topk_topology_candidates(shuffled,numel(full));
    assert(isequal({top.canonical_graph_key},{top_shuffled.canonical_graph_key}) && ...
        isequal([top.prior_cost],[top_shuffled.prior_cost]), ...
        'Synchronized edge/cost permutation changed Top-K output.');
    bad_cost=spec;bad_cost.edge_prior_cost(2)=-1;
    assert_throws(@()generate_topk_topology_candidates(bad_cost,1),'stage4a7_2:InvalidEdgeCost');
    bad_cost=spec;bad_cost.edge_prior_cost(2)=NaN;
    assert_throws(@()generate_engineering_topology_candidates(bad_cost),'stage4a7_2:InvalidEdgeCost');
    cycle=spec;cycle.required_edges={'A','B';'B','C';'A','C'};
    assert_throws(@()generate_topk_topology_candidates(cycle,1),'stage4a7_2:RequiredCycle');
    fprintf('  PASS Stage 4A.7.2 exact lazy Top-K identity and uniqueness\n');

    [lo,hi]=stage4a7_2_wilson_interval(0,10);
    assert(lo==0 && hi>0,'Wilson interval implementation failed at zero successes.');
    [lo2,hi2]=stage4a7_2_wilson_interval(5,0);
    assert(isnan(lo2)&&isnan(hi2),'Wilson zero denominator must be not applicable.');
    fprintf('  PASS Stage 4A.7.2 Wilson denominator semantics\n');

    D=[0.10 0.30;0.12 0.28;0.09 0.31;0.11 0.29];
    model=calibrate_candidate_nonconformity_family(D,[1;1;2;2],{'G1','G2'}, {'G1','G2'},0.05,struct('scales',[1 1],'minimum_per_candidate',2));
    assert(strcmp(model.status,'calibrated') && all([model.classes.sample_count]==2), ...
        'Candidate nonconformity calibration count/status failed.');
    applied=apply_candidate_nonconformity_set([0.10 0.30],model,0.05);
    assert(numel(applied)==4 && all(isfield(applied,{'method_id','p_values','accepted_candidate_set'})), ...
        'Candidate score-family output schema failed.');
    applied_i=apply_candidate_nonconformity_set_indistinguishable([0.10 0.30],model,0.05,1e-12);
    assert(strcmp(applied_i.method_id,'absolute_I') && isfield(applied_i,'indistinguishability_graph'), ...
        'Indistinguishability-augmented candidate set schema failed.');
    fprintf('  PASS Stage 4A.7.2 score-family calibration and frozen application\n');

    adapted=stage4a7_1_adapt_legacy_candidates(legacy);
    [clusters,audit]=build_stage4a7_2_nonunique_clusters(adapted,cfg,4,20262741,1e-10);
    assert(audit.generated_count==4 && numel(unique({clusters.parameter_hash}))==4, ...
        'Same-theta non-unique cluster generation is not reproducible/independent.');
    assert(max([clusters.same_theta_distance])<=1e-10, ...
        'Same-theta symmetry cluster exceeds the frozen tolerance.');
    fprintf('  PASS Stage 4A.7.2 non-unique same-theta cluster audit\n');

    near=build_stage4a7_2_near_symmetry(adapted,cfg,20262761,[.001 .01],2,1e-10);
    assert(numel(near)==4 && numel(unique({near.parameter_hash}))==4, ...
        'Near-symmetry scenario generation is not independent.');
    assert(all([near.perturbation_fraction]>0), ...
        'Near-symmetry perturbations must be positive and explicit.');
    fprintf('  PASS Stage 4A.7.2 symmetry-preserving and symmetry-breaking audit\n');

    % The structure-out construction is tested here only at the identity
    % level; scoring remains separate from truth labels in the experiment.
    outside_spec=spec; outside_spec.required_edges=[]; outside_spec.forbidden_edges=[];
    [outside,~]=generate_engineering_topology_candidates(outside_spec);
    assert(~isempty(outside) && numel(unique({outside.canonical_graph_key}))==numel(outside), ...
        'Engineering candidate canonical keys must remain explicit and deduplicated.');
    fprintf('  PASS Stage 4A.7.2 canonical engineering identity audit\n');
end

function assert_throws(fun,id)
    hit=false;
    try
        fun();
    catch ME
        hit=true;
        assert(strcmp(ME.identifier,id),'Expected %s but received %s.',id,ME.identifier);
    end
    assert(hit,'Expected error %s.',id);
end
