function test_stage3a_2()
%TEST_STAGE3A_2 Short interface tests for Stage 3A.2 model validity.
    root=fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root,'src'));addpath(fullfile(root,'config'));
    s3=stage3a_config(root);base=s3.base_config;
    symbol=stage3a_generate_symbol(s3.ofdm,1,17);
    H=exp(-1i*2*pi*(0:numel(s3.ofdm.active_frequency_hz)-1)/numel(s3.ofdm.active_frequency_hz)*0.01);
    [rx_c,dc]=stage3a_apply_ofdm_channel(symbol,H,s3.ofdm, ...
        struct('kind','none','snr_db',Inf),struct('channel_mode','circular_sampled_cfr'),7);
    [rx_l,dl]=stage3a_apply_ofdm_channel(symbol,H,s3.ofdm, ...
        struct('kind','none','snr_db',Inf),struct('channel_mode','linear_sampled_cfr'),7);
    assert(strcmp(dc.channel_mode,'circular_sampled_cfr')&&strcmp(dl.channel_mode,'linear_sampled_cfr'), ...
        'Circular/linear channel modes were not labelled explicitly.');
    assert(numel(dl.linear_full_frame)==numel(symbol.tx_frame)+s3.ofdm.nfft-1&& ...
        numel(rx_l)==numel(symbol.tx_frame)&&max(abs(rx_c-rx_l))>1e-9, ...
        'Linear sampled-CFR output did not expose the expected CP comparison.');
    x=[1+1i,2-1i,3];h=[1,0.5i];
    assert(max(abs(stage3a_explicit_linear_convolution(x,h)-conv(x,h)))==0, ...
        'Explicit linear convolution does not match finite convolution.');
    coverage=stage3a_cp_coverage(dl.h_sampled,s3.ofdm.cyclic_prefix_samples,-40);
    assert(isfield(coverage,'energy_99_support_samples')&& ...
        isfield(coverage,'physical_delay_support_samples')&& ...
        isnan(coverage.physical_delay_support_samples)&&~coverage.physical_delay_available, ...
        'CP audit did not distinguish sampled support from physical delay support.');
    info=stage3a_observation_config('dual_receiver_counterfactual');
    assert(info.is_counterfactual&&info.view_count==2&&info.network_is_complete, ...
        'Counterfactual observation metadata is invalid.');
    candidates=topology_candidates(base);
    f=s3.ofdm.active_frequency_hz;
    [views,details]=stage3a_compute_observations(f,candidates(2),base,struct(), ...
        'dual_receiver_counterfactual');
    assert(numel(views)==2&&details.is_counterfactual&&details.network_complete&& ...
        all(isfinite(views{1}))&&all(isfinite(views{2})), ...
        'Counterfactual complete-network observation failed.');
    fprintf('  PASS Stage3A.2 linear/CP audit and counterfactual observation interfaces\n');
end
