function test_stage4a6_3_1_protocol_pilot()
%TEST_STAGE4A6_3_1_PROTOCOL_PILOT Protocol, identity and metric semantics.
    root=fileparts(fileparts(mfilename('fullpath')));addpath(fullfile(root,'src'),fullfile(root,'config'),fullfile(root,'experiments'));
    cfg=default_config(root);sc=stage4a6_3_1_protocol_config(cfg,'pilot');c=generate_radial_topology_candidates(sc.generator);d=build_extended_parameter_domain(sc.parameter_search,sc.extended_domain_eta);
    b=generate_stage4a6_3_1_independent_trials(sc,'pilot',c);assert(numel(unique({b.sample_id}))==numel(b));
    out=b(strcmp({b.parameter_domain_truth},'out_of_domain'));assert(~isempty(out));assert(numel(unique({out.physical_scenario_id}))==numel(out));
    th=out(1).truth_theta;other=out(find(~strcmp({out.sample_id},out(1).sample_id),1));assert(~isequal(th,other.truth_theta),'Pilot replicates did not vary physics.');
    [h1,~]=stage4a6_3_1_compatibility_hash(sc,c,topology_parameter_grid(sc.parameter_search),'source_a',struct());sc2=sc;sc2.confirmation.K=sc.confirmation.K+1;[h2,~]=stage4a6_3_1_compatibility_hash(sc2,c,topology_parameter_grid(sc2.parameter_search),'source_a',struct());assert(~strcmp(h1,h2),'Compatibility hash ignored confirmation change.');
    txt=fileread(fullfile(root,'experiments','exp_stage4a6_3_1_protocol_pilot.m'));assert(isempty(strfind(txt,'match_nominal')));assert(~isempty(strfind(fileread(fullfile(root,'src','confirm_stage4a6_3_1_topology.m')),'score_stage4a5_observation')));
    ids={'G002','G005'};confirmation=struct('decision','equivalence_class','accepted_topology_set','G002,G005','best_topology_id','G002','accepted_member_ids',{ids});e=repmat(struct('topology_id','','optimizer_converged',true,'profile_computed',false,'profile_reliable',false,'parameter_evidence',struct([])),2,1);e(1).topology_id='G002';e(2).topology_id='G005';r=aggregate_stage4a6_3_1_member_evidence(confirmation,e,struct([]),'A6_3_M0_topology_only');assert(r.accepted_member_count==2&&r.evaluated_member_count==2);
    t=struct('parameter_name','main_length_scale','status','calibrated','absolute_improvement_threshold',0.1,'relative_improvement_threshold',0.1,'sensitivity_floor',0.01);m=struct('calibration_status','calibrated','parameter_thresholds',t);p1=parameter_row('main_length_scale',false);p2=parameter_row('main_length_scale',true);e2=repmat(e(1),2,1);e2(1).profile_computed=true;e2(1).profile_reliable=true;e2(1).parameter_evidence=p1;e2(2).profile_computed=true;e2(2).profile_reliable=true;e2(2).parameter_evidence=p2;e2(1).topology_id='G002';e2(2).topology_id='G005';r2=aggregate_stage4a6_3_1_member_evidence(confirmation,e2,m,'A6_3_M3_joint_diagnostic');assert(strcmp(r2.parameter_domain_status,'parameter_domain_indeterminate'),'Conflicting members were not indeterminate.');
    labels=[label('s1','phys1','in_domain','G002'),label('s2','phys1','in_domain','G002')];dec=[decision('s1'),decision('s2')];mm=evaluate_stage4a6_3_1_metrics(dec,labels);assert(mm(1).nominal_row_count==2&&mm(1).unique_physical_scenario_count==1&&mm(1).duplicate_observation_count==1);fprintf('ALL STAGE 4A.6.3.1 PROTOCOL TESTS PASSED\n');
end
function p=parameter_row(name,outside),p=struct('parameter_name',name,'active',true,'profile_status','indeterminate','in_domain_min_distance',0.1,'extended_min_distance',0.01,'absolute_improvement',0.2,'relative_improvement',0.2,'extended_optimum',1.5,'extended_optimum_outside',outside,'boundary_behavior','upper_boundary','outward_decrease',true,'flatness_metric',0.2,'relative_dynamic_range',0.2,'absolute_dynamic_range',0.2,'valid_point_fraction',1,'local_sensitivity',0.2,'multistart_evaluated',false,'multistart_consistent','not_applicable','profile_reliable',true,'reliability_reason','test');end
function x=label(id,phys,dom,top),x=struct('sample_id',id,'category','in_domain_interior','truth_topology_id',top,'parameter_domain_truth',dom,'physical_scenario_id',phys,'outlier_dimension','','outlier_severity','','outlier_direction','');end
function x=decision(id),x=struct('sample_id',id,'method_id','M','decision','unique_topology','topology_status','unique_topology','topology_set','G002','parameter_domain_status','parameter_in_domain');end
