function test_stage7a13_confirm(root)
%TEST_STAGE7A13_CONFIRM Identity, pooled bridge and pruned-mirror safety.
    if nargin<1||isempty(root)
        root=fileparts(fileparts(mfilename('fullpath')));
    end
    addpath(fullfile(root,'src'));
    names=repmat({'unused'},1,17);
    templates=cell(3,17);
    values=[0,0.1,2];
    for k=1:3
        for v=1:17
            templates{k,v}=complex(values(k));
        end
    end
    bank=struct('identity','test_bank', ...
        'candidate_ids',{{'A','B','C'}}, ...
        'candidate_signatures',{{'sa','sb','sc'}}, ...
        'view_names',{names},'templates',{templates}, ...
        'params',[1 1 1]);
    strata(1)=struct('class_threshold',1,'fit_threshold',1, ...
        'fallback',true);
    strata(2)=struct('class_threshold',1,'fit_threshold',1, ...
        'fallback',false);
    model=struct('bank_identity','test_bank', ...
        'candidate_signatures',{{'sa','sb','sc'}}, ...
        'sigma',ones(1,17),'pooled_class_threshold',1, ...
        'pooled_fit_threshold',1,'margin_threshold',0.5, ...
        'strata',strata);
    observed=repmat({complex(0)},1,17);
    guarded=stage7a13_confirm(observed,bank,model,1,1:3,2,'pooled');
    assert(strcmp(guarded.decision_state,'LOW_CONFIDENCE') && ...
        guarded.selected_only_margin==Inf && guarded.margin<0.5, ...
        'stage7a13:PrunedCompetitorSafety');
    unguarded=stage7a13_confirm(observed,bank,model,1,1,2,'pooled');
    assert(strcmp(unguarded.decision_state,'UNIQUE_CONFIDENT'), ...
        'stage7a13:TestCompetitorControl');
    both=stage7a13_confirm(observed,bank,model,[1 2],1:3,2,'pooled');
    assert(strcmp(both.decision_state,'MULTIPLE_AMBIGUOUS'));
    empty=stage7a13_confirm(observed,bank,model,[],1:3,2,'pooled');
    assert(strcmp(empty.decision_state,'REJECTED'));
    fallback=stage7a13_confirm(observed,bank,model,1,1:3,1,'stratified');
    assert(fallback.stratum_fallback && ...
        strcmp(fallback.decision_state,guarded.decision_state), ...
        'stage7a13:InsufficientStratumFallback');
    old=struct('bank_identity','test_bank', ...
        'candidate_signatures',{{'sa','sb','sc'}}, ...
        'sigma',ones(1,17),'class_threshold',1, ...
        'fit_threshold',1,'margin_threshold',0.5);
    legacy=stage7a12_confirm(observed,bank,old,1,1:3);
    assert(strcmp(legacy.decision_state,guarded.decision_state) && ...
        strcmp(legacy.candidate_set,guarded.candidate_set) && ...
        abs(legacy.margin-guarded.margin)<1e-12, ...
        'stage7a13:PooledSemanticBridge');
    mirrored=bank;
    for v=1:17
        mirrored.templates{2,v}=mirrored.templates{1,v};
    end
    tie=stage7a13_confirm(observed,mirrored,model,1,1:2,2,'stratified');
    assert(~strcmp(tie.decision_state,'UNIQUE_CONFIDENT'), ...
        'stage7a13:MirrorForcedUnique');
    bad=model;bad.bank_identity='wrong';
    try
        stage7a13_confirm(observed,bank,bad,1,1:3,2,'pooled');
        error('stage7a13:ExpectedIdentityError', ...
            'The mismatched bank identity was not rejected.');
    catch err
        assert(strcmp(err.identifier,'stage7a13:BankIdentity'));
    end
    fprintf('PASS test_stage7a13_confirm: identity, pooled bridge, margin safety\n');
end
