function test_stage3a_1()
%TEST_STAGE3A_1 Regression tests for the Stage-3A.1 audit interfaces.
%   These tests exercise configuration and a small complete-network grid;
%   they do not rerun the 50-trial-per-condition audit experiment.
    root = fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root, 'src'));
    addpath(fullfile(root, 'config'));

    s3 = stage3a_config(root);
    assert(s3.audit_trials_per_condition >= 50, ...
        'Audit must have at least 50 trials per topology and condition.');
    assert(isequal(s3.audit_snr_db, [5, 10, 15, 20, 30]), ...
        'Audit SNR grid is incomplete.');
    assert(isequal(s3.audit_pilot_spacings, [1, 2, 4, 8]), ...
        'Audit pilot-spacing grid is incomplete.');
    assert(numel(s3.measurement_kinds) == 4 && numel(s3.features) == 4, ...
        'Stage3A.1 audit dimensions are incomplete.');

    base = s3.base_config;
    candidates_all = topology_candidates(base);
    candidates = candidates_all(s3.candidate_indices(1:2));
    f = linspace(2e6, 30e6, 17);
    [theta_grid, bounds] = stage3a_parameter_grid(base, s3);
    assert(numel(theta_grid) >= 15 && theta_grid(1).regularization == 0, ...
        'Bounded parameter grid is missing its nominal point.');
    assert(isfield(bounds, 'main_length_scale') && ...
        isfield(bounds, 'branch_load_scale') && ...
        isfield(bounds, 'source_impedance_ohm'), ...
        'Parameter bounds are incomplete.');

    small_grid = theta_grid(1:min(3, numel(theta_grid)));
    library = stage3a_parameter_library(f, candidates, small_grid, ...
        'siso_forward', base);
    prepared = topology_prepare_parameter_library(library);
    refs = cell(1, numel(candidates));
    for k = 1:numel(candidates)
        [refs{k}, ~] = stage3a_compute_observations(f, candidates(k), base, ...
            struct(), 'siso_forward');
    end
    ofdm_cfg = s3.ofdm;
    audit = topology_observability_classes(refs, candidates, ofdm_cfg, ...
        s3.tie_tolerance);
    nominal = topology_equivalence_match(refs{1}, refs, candidates, audit, ...
        'amp_phase_joint_weighted', ofdm_cfg, [0.5, 0.5], ...
        struct('phase_mask_threshold_db', -40));
    joint = topology_joint_match(refs{1}, prepared, ...
        'amp_phase_joint_weighted', ofdm_cfg, [0.5, 0.5], ...
        s3.audit_parameter_lambda, struct('phase_mask_threshold_db', -40));
    assert(isfinite(nominal.best_distance) && isfinite(joint.objective) && ...
        strcmp(nominal.selected_feature, joint.feature), ...
        'Nominal and joint matchers do not expose the same feature interface.');
    assert(numel(joint.scores) == numel(library) && ...
        all(isfinite(joint.scores)), ...
        'Joint parameter matcher returned invalid grid scores.');
    fprintf('  PASS Stage3A.1 audit configuration and nominal/joint interface\n');
end
