function test_stage7a1_diagnostics()
%TEST_STAGE7A1_DIAGNOSTICS Split identity, exhaustive cache and state gates.
    root=fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root,'src'),fullfile(root,'config'));
    base=default_config(root);dc=stage7a1_diagnostic_config(base,'smoke');sc=dc.stage7a;
    library=stage6b_build_candidate_library('radial_grammar', ...
        sc.stage6b.scale.grammars(1),base,struct());
    cache=stage7a_build_profile_cache(library,base,sc);
    cond=dc.conditions(1);cond.per_candidate=8;
    [model,~]=stage7a1_calibrate_split_library(library,base,sc,cache,cond, ...
        'test_small',220001100,320001100);
    assert(~strcmp(model.calibration_set_id,model.evidence_set_id)&& ...
        model.set_per_candidate==8&&model.evidence_per_candidate==8, ...
        'Stage 7A.1 calibration batches are not independently identified.');
    truth=find(arrayfun(@(c)isequal(sort([c.network.branches.node]),2),library),1);
    theta=struct('main_length_scale',1.015,'branch_length_scale',1, ...
        'branch_load_scale',1,'source_impedance_ohm',sc.search.source_impedance_ohm, ...
        'receiver_impedance_ohm',sc.search.receiver_impedance_ohm,'regularization',0);
    y=stage6b_forward_cfr(library(truth).network,theta,base, ...
        sc.frequency_hz,sc.measurement_kind);
    coarse=stage7a_profile_distance(y,cache,sc.search);
    exhaustive=stage7a1_exhaustive_profile_distance(y,cache,sc.search);
    assert(all(exhaustive.profile_distances<=coarse.profile_distances+1e-12)&& ...
        exhaustive.forward_evaluations==0&&all(exhaustive.best_template_indices>0), ...
        'Exhaustive audit did not minimize over the cached fine templates.');
    signature=stage6b_network_signature(library(truth).network);
    [audit,candidates]=stage7a1_audit_decision(y,model,coarse.profile_distances,signature,coarse);
    direct=stage7a_score_observation(y,model,sc.search);
    assert(strcmp(audit.decision_state,direct.decision_state)&& ...
        audit.candidate_set_size==direct.candidate_set_size&& ...
        numel(candidates)==numel(library)&&nnz([candidates.is_truth])==1&& ...
        all(isfinite([candidates.candidate_p_value])), ...
        'Expanded audit differs from the unchanged Stage 7A decision.');
    evidence=struct('margin_threshold',0.1,'top1_confidence_threshold',0.5, ...
        'normalized_entropy_threshold',0.8);
    frozen=struct('candidate_set_size',2,'domain_accepted',true, ...
        'best_candidate_in_set',true);
    passed=classify_stage5b1_decision_state(frozen,struct('margin',0.2), ...
        struct('top1_confidence',0.9,'normalized_entropy',0.3),evidence);
    failed=classify_stage5b1_decision_state(frozen,struct('margin',0.01), ...
        struct('top1_confidence',0.9,'normalized_entropy',0.3),evidence);
    assert(strcmp(passed.enhanced_decision_state,'LOW_CONFIDENCE')&& ...
        strcmp(failed.enhanced_decision_state,'MULTIPLE_AMBIGUOUS'), ...
        'Frozen multi-candidate state semantics changed.');
    fprintf('  PASS Stage 7A.1 split identity, exhaustive cache, candidate p-values and multi-set state branches\n');
end
