function test_stage7a8_resource_audit(root,mode)
%TEST_STAGE7A8_RESOURCE_AUDIT Check replay identity and resource semantics.
    if nargin<1||isempty(root),root=fileparts(fileparts(mfilename('fullpath')));end
    if nargin<2||isempty(mode),mode='formal';end
    dir=fullfile(root,'results','data','stage7a_8','resource_audit',mode);
    r=readtable(fullfile(dir,'per_sample_resources.csv'), ...
        'TextType','string','Delimiter',',');
    m=readtable(fullfile(dir,'metadata.csv'), ...
        'TextType','string','Delimiter',',');
    if strcmp(mode,'formal'),n=66;else,n=11;end
    assert(height(r)==2*n&&height(m)==1&& ...
        height(unique(r(:,{'sample_id','method'})))==2*n);
    assert(all(r.archived_scientific_match)&&all(r.candidate_count==37));
    assert(all(r.forward_calls_search==r.optimizer_evaluations)&& ...
        all(r.forward_calls_holdout==1)&& ...
        all(r.forward_calls_total==r.optimizer_evaluations+1));
    assert(all(r.scored_struct_bytes>0)&&all(r.rss_before_kb>0)&& ...
        all(r.rss_after_kb>0)&& ...
        all(r.process_hwm_after_kb>=r.process_hwm_before_kb));
    assert(all(r.shared_template_cache_bytes==m.template_cache_bytes)&& ...
        m.template_forward_calls==1665&&m.worker_count==0&& ...
        ~m.use_parallel&&m.process_peak_rss_kb== ...
        max(r.process_hwm_after_kb));
    assert(contains(m.memory_semantics,'no isolated per-sample peak'));
    fprintf('PASS test_stage7a8_resource_audit %s (%d scored rows)\n', ...
        mode,height(r));
end
