function test_stage7a12_ci(root)
%TEST_STAGE7A12_CI Common paths, hidden junction, estimator, generator.
    if nargin<1||isempty(root),root=fileparts(fileparts(mfilename('fullpath')));end
    addpath(fullfile(root,'src'),fullfile(root,'config'));
    base=default_config(root);cfg=stage7a12_config(base,'smoke');
    net=struct('main_lengths',[10 20], ...
        'branches',struct('node',1,'length',5,'cable_type',1,'load',50));
    ci=stage7a12_ci_matrix(net,cfg);
    expected=1e-3*[30 10;10 17.5];
    assert(norm(ci.R-expected,'fro')<1e-12,'stage7a12:CommonPath');
    assert(norm(ci.R-ci.R.','fro')<1e-14,'stage7a12:Symmetry');
    assert(abs(ci.R(1,2)-0.01)<1e-12 && ...
        ~ismember('M1',ci.labels), ...
        'Unmetered M1 junction must be encoded only by mutual CI.');
    measured=stage7a12_measure_ci(ci,cfg,1234,'ideal');
    est=stage7a12_estimate_ci(measured,cfg.lf_ridge_lambda);
    assert(norm(est.ols-ci.R,'fro')<1e-10,'stage7a12:IdealOLS');
    assert(norm(est.symmetric_ridge-est.symmetric_ridge.','fro')==0, ...
        'Constraint must be built into regression.');
    sync=stage7a12_measure_ci(ci,cfg,2334,'synchronous');
    async=stage7a12_measure_ci(ci,cfg,2334,'asynchronous');
    high=stage7a12_measure_ci(ci,cfg,2334,'high_noise');
    assert(isequal(sync.I,async.I)&&isequal(async.I,high.I), ...
        'Sensitivity conditions must share current innovations.');
    assert(norm(sync.clean_U-async.clean_U,'fro')==0 && ...
        norm(async.clean_U-high.clean_U,'fro')==0, ...
        'Sensitivity conditions must share ideal voltage responses.');
    [pool,~,~,catalog,~,~]=stage7a6_candidate_space(base);
    i=find(strcmp({pool.topology_id},'DOUBLE_M2'),1);
    true_ci=stage7a12_ci_matrix(pool(i).network,cfg);
    g=stage7a12_generate_candidates(true_ci.R,true_ci.labels,pool,cfg,1e-12,3);
    assert(ismember(i,g.indices),'stage7a12:TopKTruth');
    scaled=pool(i).network;scaled.main_lengths=scaled.main_lengths*1.017;
    shifted=stage7a12_ci_matrix(scaled,cfg);
    g_scaled=stage7a12_generate_candidates(shifted.R,shifted.labels, ...
        pool,cfg,1e-12,3);
    assert(ismember(i,g_scaled.indices), ...
        'Ideal CI must profile allowed physical main-length scale.');
    assert(numel(unique(g.selected_signatures))==numel(g.indices), ...
        'stage7a12:TopKDedup');
    fixed=stage7a12_ci_matrix(pool(i).network,cfg,1);
    single=find(strcmp({pool.topology_id},'G002'),1);
    one=stage7a12_ci_matrix(pool(single).network,cfg);
    assert(norm(fixed.R-one.R,'fro')<1e-12, ...
        'Unmetered second branch should be invisible to common-path CI.');
    j=find(strcmp({catalog.topology_id},'MID30'),1);
    outside=stage7a12_ci_matrix(catalog(j).network,cfg);
    assert(isequal(outside.labels,one.labels) && ...
        ~ismember(stage6b_network_signature(catalog(j).network), ...
        arrayfun(@(x)stage6b_network_signature(x.network),pool, ...
        'UniformOutput',false)), ...
        'Held-out midpoint must share meter identity but lie outside grammar.');
    audit=stage7a12_structure_audit(pool(i).network,pool(i));
    assert(audit.min_wrong_branch_edges==0 && ...
        audit.max_recovered_hidden_junctions==1);
    theta=struct('main_length_scale',1,'branch_length_scale',1, ...
        'branch_load_scale',1,'first_segment_scale',1, ...
        'source_impedance_ohm',50,'receiver_impedance_ohm',50);
    z=stage7a4_forward_state(g.graphs(1).network,theta,base, ...
        cfg.frequency_hz,cfg.states(3));
    assert(all(isfinite(z.H_endpoint)), ...
        'Generated graph must pass the stable CFR forward interface.');
    fprintf('PASS test_stage7a12_ci: common path, symmetry, generator, invisible branch\n');
end
