function cfg = default_config(root_dir)
%DEFAULT_CONFIG Configuration for the prescribed PLC CFR experiments.
%   All frequencies are Hz, lengths are m, and terminal impedances are ohm.

    if nargin < 1 || isempty(root_dir)
        root_dir = fileparts(fileparts(mfilename('fullpath')));
    end
    cfg = struct();
    cfg.root_dir = root_dir;
    cfg.frequency_hz = linspace(2e6, 30e6, 2048);
    cfg.kG = 1;
    cfg.Zs = 50;
    cfg.Zr = 50;
    cfg.port_reference_ohm = 50;
    cfg.lossless = false;
    cfg.abcd_det_warning_threshold = 1e-6;
    cfg.suppress_abcd_warning = false;
    cfg.measurement_floor_reference_db = -120;
    cfg.main_cable_type = 0;
    cfg.branch_cable_type = 1;
    % Stage 2 uses a complex-baseband, all-pilot OFDM equivalent model.
    % No original communication waveform implementation was present in
    % the project; these values are therefore explicit baseline assumptions.
    cfg.ofdm = ofdm_config();
    cfg.topology = struct('main_total_length_m', 80, ...
        'main_segment_length_m', 20, 'branch_length_m', 15, ...
        'branch_load_ohm', 50, 'branch_cable_type', 1, ...
        'main_cable_type', 0, 'num_candidates', 6);
    cfg.stage2 = struct('snr_db', [30, 20, 10, 0], ...
        'monte_carlo_trials', 20, 'load_scales', [0.8, 0.9, 1.1, 1.2], ...
        'length_scales', [0.95, 0.98, 1.02, 1.05], ...
        'loss_scales', [0.95, 1.05], 'joint_distance_weights', [0.5, 0.5], ...
        'tie_tolerance', 1e-10);
    % Stage 2.1 audit settings are separate from stage-2 baseline settings so
    % that the original 20-trial results remain reproducible and comparable.
    cfg.stage2_1 = struct('snr_db', [30, 20, 10, 0], ...
        'monte_carlo_trials', 50, ...
        'phase_mask_threshold_db', -40, ...
        'noise_modes', {{'fixed_received_snr', 'fixed_noise_power'}}, ...
        'reference_topology_index', 1, ...
        'joint_distance_weights', [0.5, 0.5], ...
        'joint_trials', 50, ...
        'uncertainty_seed_offset', 2100000, ...
        'asymmetric_Zs', 50, 'asymmetric_Zr', 75, ...
        'extra_receiver_segments', 2, ...
        'length_scales', [0.99, 1.01, 0.98, 1.02, 0.95, 1.05], ...
        'load_scales', [0.90, 1.10, 0.80, 1.20], ...
        'feature_audit_snr_db', 20, ...
        'feature_audit_weights', [0.2, 0.8; 0.5, 0.5; 0.8, 0.2]);
    % Stage 2.2 values are explicit simulation/search assumptions. They are
    % not field-calibrated PLC parameter distributions.
    search22 = struct('main_length_scale',[0.95,1,1.05], ...
        'branch_length_scale',[0.95,1,1.05], ...
        'branch_load_scale',[0.8,1,1.2], ...
        'source_impedance_ohm',[45,50,55], ...
        'receiver_impedance_ohm',[45,50,55], ...
        'nominal_source_impedance_ohm',50, ...
        'nominal_receiver_impedance_ohm',50, ...
        'couple_line_scales',false);
    cfg.stage2_2 = struct('snr_db',[30,20,10,0], ...
        'monte_carlo_trials',20,'candidate_indices',[2,3,4,5], ...
        'noise_modes',{{'fixed_received_snr','fixed_noise_power'}}, ...
        'measurement_kinds',{{'siso_forward','bidirectional_endpoint_fixed', ...
            'dual_receiver_complete','three_view_complete'}}, ...
        'search',search22,'regularization_lambda',0.01, ...
        'matching_feature','amp_phase_joint_weighted', ...
        'single_feature_baseline','amplitude', ...
        'joint_weights',[0.5,0.5], ...
        'joint_weight_scan',[0.2,0.8;0.5,0.5;0.8,0.2], ...
        'phase_mask_thresholds_db',[-20,-30,-40,-50,-60], ...
        'true_main_length_scale_range',[0.95,1.05], ...
        'true_branch_length_scale_range',[0.95,1.05], ...
        'true_load_scale_range',[0.8,1.2], ...
        'true_kG_scale_range',[0.95,1.05], ...
        'true_Zs_range_ohm',[45,55], 'true_Zr_range_ohm',[45,55], ...
        'audit_snr_db',20,'reference_noise_topology_index',1);
    % Stage 2.3 is an observability audit, not a waveform-optimization
    % configuration.  These values are frozen before the formal test set;
    % they are simulation assumptions rather than tuned optima.
    cfg.stage2_3 = struct('snr_db',[30,20,10,0], ...
        'formal_trials',100,'smoke_trials',5, ...
        'trial_offset',0, ...
        'candidate_indices',[2,3,4,5], ...
        'measurement_kinds',{{'siso_forward','siso_forward_asymmetric', ...
            'siso_reverse_role_fixed','siso_reverse_endpoint_fixed', ...
            'bidirectional_endpoint_fixed','dual_receiver_complete', ...
            'three_view_complete'}}, ...
        'features',{{'amplitude','amplitude_raw_db', ...
            'amplitude_db_standardized','phase_weighted','complex', ...
            'amp_phase_joint_weighted'}}, ...
        'fair_feature','amp_phase_joint_weighted', ...
        'joint_weights',[0.5,0.5], ...
        'phase_mask_threshold_db',-40, ...
        'tie_tolerance',1e-10, ...
        'regularization_lambda',0.01, ...
        'search',search22, ...
        'asymmetric_Zs',50,'asymmetric_Zr',75, ...
        'parameter_snr_db',20, ...
        'length_scale_range',[0.95,1.05], ...
        'load_scale_range',[0.8,1.2], ...
        'endpoint_impedance_range_ohm',[45,55], ...
        'kG_scale_range',[0.95,1.05], ...
        'calibration_note',['lambda=0.01, weights=0.5/0.5 and the stage-2.2 ' ...
            'grid are frozen simulation settings, not test-set-optimized values.']);
    cfg.default_network = struct();
    cfg.default_network.main_lengths = [20, 20];
    cfg.default_network.main_cable_type = [0, 0];
    cfg.default_network.branches = struct('node', 1, 'length', 10, ...
        'cable_type', 1, 'load', 50);
    cfg.results_figures = fullfile(root_dir, 'results', 'figures');
    cfg.results_data = fullfile(root_dir, 'results', 'data');
    cfg.random_seed = 20260819;
end
