function cfg=stage7a4_impedance_resolution_config(base,mode)
%STAGE7A4_IMPEDANCE_RESOLUTION_CONFIG Frozen pair-only resolution audit.
%   Lengths are m, complex impedance errors ohm RMS per frequency and read.
    if nargin<1||isempty(base)
        base=default_config(fileparts(fileparts(mfilename('fullpath'))));
    end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));
    assert(ismember(mode,{'smoke','formal'}),'stage7a4r1:Mode');
    old=stage7a4_mirror_observation_config(base,'formal');
    cfg=struct('mode',mode,'version','stage7a4_impedance_resolution_v1', ...
        'verification_baseline_commit','b69d109c9b2773dbd46858778ca532b3d4f7e13e', ...
        'frequency_hz',old.frequency_hz,'state',old.states(3), ...
        'branch_load_ohm',1e9, ...
        'branch_lengths_m',[0.0001 0.00025 0.0005 0.001 0.002 0.005 0.01], ...
        'repeat_counts',[1 4 16 64 256 1024], ...
        'main_scale_grid',old.main_scale_grid, ...
        'branch_load_grid',old.branch_load_grid, ...
        'offgrid_main_bounds',[0.98 1.02], ...
        'offgrid_load_bounds',[0.8 1.2], ...
        'single_read_error_rms_ohm',1,'alpha',0.05, ...
        'separation_threshold',old.separation_threshold, ...
        'seed_A',811000000,'seed_F',821000000, ...
        'seed_C',831000000,'seed_T',841000000, ...
        'n_per_truth',100,'use_parallel',false,'worker_count',0, ...
        'output_dir',fullfile(base.root_dir,'results','data', ...
            'stage7a_4_resolution',mode), ...
        'log_dir',fullfile(base.root_dir,'results','logs', ...
            'stage7a_4_resolution'));
    if strcmp(mode,'smoke')
        cfg.branch_lengths_m=[0.0001 0.001 0.005];
        cfg.repeat_counts=[1 16 1024];
        cfg.n_per_truth=20;
    end
end
