function sc=stage4a7_3_domain_validation_config(base,mode)
%STAGE4A7_3_DOMAIN_VALIDATION_CONFIG Frozen model-internal domain protocol.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode)); assert(ismember(mode,{'smoke','formal'}),'stage4a7_3:Mode','Mode must be smoke or formal.');
    sc=struct('stage_name','Stage 4A.7.3','version','stage4a7_3_domain_nonunique_v1','mode',mode, ...
        'frequency_hz',linspace(2e6,30e6,61),'measurement_kind','siso_forward','feature','complex_raw', ...
        'noise',struct('snr_db',20,'kind','frequency_domain_circular_complex_gaussian'), ...
        'alpha',0.05,'use_parallel',false,'num_workers',1, ...
        'source_formal_dir',fullfile(base.root_dir,'results','data','stage4a7_2_r2_1_1','final_source_v3','formal'), ...
        'output_root',fullfile(base.root_dir,'results','data','stage4a7_3'), ...
        'results_logs',fullfile(base.root_dir,'results','logs','stage4a7_3'), ...
        'seeds',struct('development',20263101,'calibration',20263111,'pilot',20263121,'nonunique_calibration',20263131,'nonunique_test',20263141,'final_reserved',20263151), ...
        'parameter_domain',struct('lower',0.95,'upper',1.05,'near_lower',0.90,'near_upper',1.10, ...
          'medium_lower',0.75,'medium_upper',1.30,'far_lower',0.60,'far_upper',1.60, ...
          'calibration_quantile',0.95,'near_boundary_quantile',0.80,'in_domain_acceptance_floor',0.90, ...
          'methods',{{'profile_min_distance','profile_relative_distance'}}, ...
          'selection_rule','maximize development in-domain acceptance subject to floor; then minimize medium_far_ood_false_acceptance; ties are no_unique_winner'), ...
        'scenario_design',struct('development_per_candidate',3,'calibration_per_candidate',40,'pilot_replicates',1), ...
        'nonunique',struct('candidate_ids',{{'T3','T5'}},'calibration_per_candidate',40,'test_per_noise',40, ...
          'noise_levels_db',[Inf 30 10],'numerical_tolerance',1e-10,'parameter_perturbation_fraction',0.02));
    if strcmp(mode,'smoke')
        sc.scenario_design=struct('development_per_candidate',1,'calibration_per_candidate',5,'pilot_replicates',1);
        sc.nonunique.calibration_per_candidate=8;sc.nonunique.test_per_noise=4;
    end
    sc.final_reserved=struct('status','manifest_only_not_materialized','seed',sc.seeds.final_reserved);
end
