function cfg=stage7a2_set_coverage_config(base,mode)
%STAGE7A2_SET_COVERAGE_CONFIG Prespecified independent-split synthetic study.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));assert(ismember(mode,{'smoke','formal'}),'stage7a2:Mode','Invalid mode.');
    sc=stage7a_profile_search_config(base,'formal');
    cfg=struct('mode',mode,'stage7a',sc,'alpha',0.05,'curve_alpha',[0.05 0.10 0.20], ...
        'risk_target',0.05,'risk_delta',0.05,'snr_db',20,'shift_snr_db',10, ...
        'main_bounds',[0.98 1.02],'load_bounds',[1 1], ...
        'parameter_out_low',[0.82 0.88],'parameter_out_high',[1.12 1.18], ...
        'development_per_class',10,'set_per_class',60,'evidence_per_class',40, ...
        'risk_per_class',30,'test_per_class',50,'stress_count',100, ...
        'seed_development',510000000,'seed_set',520000000, ...
        'seed_evidence',530000000,'seed_risk',540000000, ...
        'seed_test',550000000,'seed_library_out',560000000, ...
        'seed_parameter_out',570000000,'seed_snr_shift',580000000, ...
        'source_commit','5217ee8edf9b8a814d26690b873e28fd2d82e218', ...
        'use_parallel',false,'worker_count',0, ...
        'output_root',fullfile(base.root_dir,'results','data','stage7a_2',mode), ...
        'figure_root',fullfile(base.root_dir,'results','figures','stage7a_2'), ...
        'log_root',fullfile(base.root_dir,'results','logs','stage7a_2'));
    if strcmp(mode,'smoke')
        cfg.development_per_class=2;cfg.set_per_class=4;cfg.evidence_per_class=4;
        cfg.risk_per_class=4;cfg.test_per_class=2;cfg.stress_count=4;
        cfg.stage7a.evidence_calibration.minimum_reference_count=2;
    end
end
