function sc=stage7a_profile_search_config(base,mode)
%STAGE7A_PROFILE_SEARCH_CONFIG Prespecified controlled Stage 7A protocol.
%   Length bounds come from the Stage 6A synthetic allowed-edge prior.
%   Load-scale bounds are an explicit Stage 6B nuisance-model assumption.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));
    assert(ismember(mode,{'smoke','formal'}),'stage7a:Mode','Mode must be smoke or formal.');
    s6a=stage6a_candidate_generation_config(base,'formal');
    s6b=stage6b_robustness_config(base,'formal');
    prior=s6a.partial_prior_cases(1);
    edges=prior.allowed_edges;
    main=edges(strcmp({edges.kind},'main'));
    assert(numel(main)==4&&all([main.length_m]==main(1).length_m), ...
        'stage7a:PriorShape','Stage 7A requires four equal nominal main edges.');
    nominal=main(1).length_m;
    bounds=[max([main.length_min_m]./[main.length_m]), ...
        min([main.length_max_m]./[main.length_m])];
    assert(bounds(1)<1&&bounds(2)>1&&all(isfinite(bounds)), ...
        'stage7a:InvalidPriorBounds','The synthetic prior lacks a usable main-length interval.');
    fraction=s6b.parameter.load_perturbation_fraction;
    search=struct('main_scale_bounds',bounds,'main_nominal_length_m',nominal, ...
        'main_length_bounds_m',[min([main.length_min_m]) max([main.length_max_m])], ...
        'partial_prior_total_length_range_m',prior.total_length_range_m, ...
        'branch_load_scale_bounds',[1-fraction 1+fraction], ...
        'coarse_main_step',0.05,'fine_main_step',0.025, ...
        'coarse_load_step',0.20,'fine_load_step',0.10, ...
        'branch_length_scale',1,'source_impedance_ohm',s6b.parameter_search.source_impedance_ohm(1), ...
        'receiver_impedance_ohm',s6b.parameter_search.receiver_impedance_ohm(1), ...
        'domain_source','stage6a_synthetic_allowed_edges_main_intersection', ...
        'load_source','stage6b_synthetic_load_perturbation_not_field_prior');
    sc=struct('stage_name','Stage 7A','version','bounded_coarse_to_fine_profile_v1', ...
        'mode',mode,'development_base_commit','81b95a63c5ce7e4ba6985de52cd5177768f68a59', ...
        'output_root',fullfile(base.root_dir,'results','data','stage7a'), ...
        'log_root',fullfile(base.root_dir,'results','logs','stage7a'), ...
        'frequency_hz',s6b.frequency_hz,'measurement_kind',s6b.measurement_kind, ...
        'search',search,'alpha',s6b.alpha,'domain_quantile',s6b.domain_quantile, ...
        'calibration_snr_db',s6b.calibration_snr_db,'calibration_per_candidate',20, ...
        'calibration_seed',20267001,'calibration_seed_offset',9000000, ...
        'test_seed',20267002,'test_replicates',10, ...
        'evidence_calibration',s6b.evidence_calibration,'prior',prior, ...
        'stage6b',s6b,'baseline_source_commit','bea0aee10b216ba42813329772f05a24dbdca07c', ...
        'use_parallel',false,'worker_count',0, ...
        'validation_scope','controlled_synthetic_model_internal');
    if strcmp(mode,'smoke')
        sc.calibration_per_candidate=4;
        sc.test_replicates=2;
        sc.alpha=0.20;
        sc.evidence_calibration.minimum_reference_count=2;
    end
end
