function cfg=stage7a4_mirror_observation_config(base,mode)
%STAGE7A4_MIRROR_OBSERVATION_CONFIG Frozen synthetic observation study.
%   Frequencies are Hz, line lengths m, impedances ohm. No field hardware
%   capability or impedance-measurement accuracy is inferred from this setup.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));assert(ismember(mode,{'smoke','formal'}),'stage7a4:Mode');
    old=stage7a_profile_search_config(base,'formal');
    term=[12.5 25 50 100 200];nodes=[2 3 4];
    states=repmat(struct('name','','receiver_ohm',50,'node_index',0, ...
        'node_load_ohm',Inf),1,numel(term)+numel(nodes));
    for k=1:numel(term)
        states(k)=struct('name',sprintf('termination_%g_ohm',term(k)), ...
            'receiver_ohm',term(k),'node_index',0,'node_load_ohm',Inf);
    end
    for k=1:numel(nodes)
        states(numel(term)+k)=struct('name',sprintf('node_M%d_highZ',nodes(k)-1), ...
            'receiver_ohm',50,'node_index',nodes(k),'node_load_ohm',1e6);
    end
    view_names=cell(1,2*numel(states));
    for k=1:numel(term)
        view_names{2*k-1}=sprintf('H_term_%g',term(k));
        view_names{2*k}=sprintf('Zin_term_%g',term(k));
    end
    for k=1:numel(nodes)
        j=2*numel(term)+2*k-1;
        view_names{j}=sprintf('H_endpoint_with_M%d_port',nodes(k)-1);
        view_names{j+1}=sprintf('H_node_M%d',nodes(k)-1);
    end
    view_names{end+1}='H50_independent_repeat';
    cfg=struct('stage','Stage 7A.4','version','mirror_observation_design_v1', ...
        'mode',mode,'verification_baseline_commit','e9d61b3a51b2701f02a5ee0de8c958b3acd5d48e', ...
        'frequency_hz',old.frequency_hz,'states',states,'view_names',{view_names}, ...
        'termination_ohm',term,'node_indices',nodes,'source_impedance_ohm',50, ...
        'port_reference_ohm',50,'input_impedance_reference_ohm',50, ...
        'main_scale_grid',0.9:0.025:1.1,'branch_load_grid',0.8:0.1:1.2, ...
        'asymmetry_grid',[1 1.015 1.03],'true_main_bounds',[0.98 1.02], ...
        'true_branch_load_scale',1,'cfr_snr_db',20,'shift_snr_db',10, ...
        'zin_error_rms_ohm',1,'alpha',0.05,'separation_threshold',3, ...
        'near_equal_tolerance',1e-12,'termination_error_fraction',0.01, ...
        'branch_load_drift_fraction',0.02,'node_port_error_fraction',0.01, ...
        'seed_D',710000000,'seed_E',720000000,'seed_A',730000000, ...
        'seed_F',740000000,'seed_T20',750000000,'seed_T10',760000000, ...
        'seed_Tasym',770000000,'seed_Tstress',780000000, ...
        'seed_E_asym',721000000,'seed_A_asym',731000000, ...
        'seed_F_asym',741000000, ...
        'seed_control_A',790000000,'seed_control_F',791000000, ...
        'seed_control_T',792000000, ...
        'n_E_per_topology',100,'n_A_per_topology',100,'n_F_per_topology',100, ...
        'n_T_per_topology',100,'n_extra_per_topology',50, ...
        'use_parallel',false,'worker_count',0, ...
        'output_dir',fullfile(base.root_dir,'results','data','stage7a_4',mode), ...
        'log_dir',fullfile(base.root_dir,'results','logs','stage7a_4'));
    if strcmp(mode,'smoke')
        cfg.n_E_per_topology=6;cfg.n_A_per_topology=8;cfg.n_F_per_topology=8;
        cfg.n_T_per_topology=8;cfg.n_extra_per_topology=4;
    end
    assert(numel(cfg.frequency_hz)==61 && abs(cfg.frequency_hz(1)-2e6)<1e-9 && ...
        abs(cfg.frequency_hz(end)-30e6)<1e-9,'stage7a4:FrequencyIdentity');
end
