function sc=stage5b1_objective_confirmation_config(base,mode)
%STAGE5B1_OBJECTIVE_CONFIRMATION_CONFIG Add-only decision-layer protocol.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));assert(ismember(mode,{'smoke','formal'}),'stage5b1:Mode','Mode must be smoke or formal.');
    sc=struct('stage_name','Stage 5B.1','version','stage5b1_objective_confirmation_v1','mode',mode, ...
        'source_formal_dir',fullfile(base.root_dir,'results','data','stage4a7_2_r2_1_1','final_source_v3','formal'), ...
        'stage4a_formal_dir',fullfile(base.root_dir,'results','data','stage4a_freeze_r1_1','stage4a7_3','formal'), ...
        'output_root',fullfile(base.root_dir,'results','data','stage5b1'), ...
        'use_parallel',false,'num_workers',1, ...
        'expected_freeze_commit','9611b284da57bd10cd64ee7e48c7ba9f3ec46a92', ...
        'expected_canonical_source_commit','54868370cc6c426f417681146caace79de782e91', ...
        'expected_rule_a_method','profile_relative_distance', ...
        'expected_rule_a_threshold',0.110340450651554, ...
        'calibration',struct('margin_quantile',0.05,'confidence_quantile',0.05, ...
          'entropy_quantile',0.95,'temperature_target_odds',9,'minimum_reference_count',100), ...
        'pilot_categories',{{'in_domain','exact_lower_boundary','exact_upper_boundary', ...
          'near_lower_ood','near_upper_ood','medium_lower_ood','medium_upper_ood','far_lower_ood','far_upper_ood'}}, ...
        'smoke_candidate_count',2,'smoke_nonunique_per_noise',4, ...
        'probability_semantics','normalized_confidence_score_not_posterior_probability');
end
