function cfg=stage7a4_continuous_fit_config(base,mode)
%STAGE7A4_CONTINUOUS_FIT_CONFIG Independent bounded-profile diagnosis.
%   Lengths are metres and complex Zin errors are ohm RMS per frequency.
    if nargin<1||isempty(base)
        base=default_config(fileparts(fileparts(mfilename('fullpath'))));
    end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));assert(ismember(mode,{'smoke','formal'}));
    old=stage7a4_impedance_resolution_config(base,'formal');
    cfg=struct('mode',mode,'version','stage7a4_continuous_fit_v1', ...
        'verification_baseline_commit','b69d109c9b2773dbd46858778ca532b3d4f7e13e', ...
        'frequency_hz',old.frequency_hz,'state',old.state, ...
        'branch_load_ohm',old.branch_load_ohm, ...
        'branch_lengths_m',[0.0001 0.002 0.01], ...
        'repeat_counts',[1 256], ...
        'main_scale_grid',old.main_scale_grid, ...
        'branch_load_grid',old.branch_load_grid, ...
        'main_scale_bounds',[min(old.main_scale_grid) max(old.main_scale_grid)], ...
        'load_scale_bounds',[min(old.branch_load_grid) max(old.branch_load_grid)], ...
        'offgrid_main_bounds',old.offgrid_main_bounds, ...
        'offgrid_load_bounds',old.offgrid_load_bounds, ...
        'single_read_error_rms_ohm',1,'alpha',0.05, ...
        'separation_threshold',old.separation_threshold, ...
        'seed_A',851000000,'seed_F',861000000, ...
        'seed_C',871000000,'seed_T',881000000,'seed_D',891000000, ...
        'n_calibration_per_truth',50,'n_test_per_truth',100, ...
        'n_diagnostic_per_truth',10, ...
        'optimizer_tol_x',1e-7,'optimizer_max_fun_evals',60, ...
        'use_parallel',false,'worker_count',0, ...
        'output_dir',fullfile(base.root_dir,'results','data', ...
            'stage7a_4_continuous',mode), ...
        'log_dir',fullfile(base.root_dir,'results','logs','stage7a_4_continuous'));
    if strcmp(mode,'smoke')
        cfg.branch_lengths_m=0.01;
        cfg.repeat_counts=[1 256];
        cfg.n_calibration_per_truth=5;
        cfg.n_test_per_truth=5;
        cfg.n_diagnostic_per_truth=2;
    end
end
