function sc=stage4a3_open_set_config(cfg)
if nargin<1||isempty(cfg),cfg=default_config(fileparts(fileparts(mfilename('fullpath'))));end
a2=stage4a2_prior_config(cfg);sc=struct('version','4a3_open_set_v1','seed_calibration',20261001,'seed_test',20261002,...
 'per_graph_calibration',1,'per_graph_test',1,'generator',a2.generator,'parameter_search',a2.parameter_search,...
 'measurement_kind','siso_forward','feature','complex_raw','weights',[.5 .5],'tie_tolerance',a2.tie_tolerance,'batch_size',24,...
 'quantile',.95,'safety_factor',1.1,'margin_quantile',.05,'source_tag','synthetic_demo_prior_not_field_data',...
 'grids',a2.frequency_grids,'scenarios',a2.prior_scenarios,'output_prefix','stage4a3', ...
 'code_version','stage4a3_open_set_v1');
sc.config_hash=stable_hash(jsonencode(sc));
end

function h=stable_hash(s)
b=double(char(s)); h=sprintf('%08X',mod(sum(b.*(1:numel(b))),2^32));
end
