function sc=stage6b_robustness_config(base,mode)
%STAGE6B_ROBUSTNESS_CONFIG Controlled robustness/identifiability protocol.
%   All priors and perturbations are synthetic. Frozen Stage 4A/5B.1
%   thresholds and formal results are read-only and are never overwritten.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));assert(ismember(mode,{'smoke','formal'}),'stage6b:Mode','Mode must be smoke or formal.');
    s6a=stage6a_candidate_generation_config(base,'formal');
    sc=struct('stage_name','Stage 6B','version','stage6b_robustness_identifiability_v1', ...
        'mode',mode,'output_root',fullfile(base.root_dir,'results','data','stage6b'), ...
        'figure_root',fullfile(base.root_dir,'results','figures','stage6b'), ...
        'frequency_hz',linspace(2e6,30e6,61),'measurement_kind','siso_forward', ...
        'seed',20266001,'alpha',0.05,'calibration_snr_db',35,'calibration_per_candidate',20, ...
        'domain_quantile',0.99,'parameter_search',s6a.parameter_search, ...
        'evidence_calibration',s6a.evidence_calibration,'rank',s6a.rank,'export',s6a.export, ...
        'truth_branch_nodes',2,'validation_scope','controlled_synthetic_model_internal');
    sc.export.id_prefix='S6B';
    sc.prior=struct('error_rates',[0 .05 .10 .20],'replicates_per_rate',20, ...
        'snr_db',20,'base_prior',s6a.partial_prior_cases(1), ...
        'wrong_open_edge',{{'M2','B2'}},'wrong_closed_edge',{{'M1','B1'}});
    sc.scale=struct('replicates',10,'snr_db',20,'runtime_repetitions',20, ...
        'grammars',scale_grammars(s6a.legacy_grammar));
    sc.parameter=struct('length_errors',[-.20 -.10 -.05 0 .05 .10 .20], ...
        'load_perturbation_fraction',.20,'replicates_per_error',10,'snr_db',30, ...
        'grammar',s6a.legacy_grammar);
    sc.identifiability=struct('matched_impedance_ohm',50,'near_invisible_branch_length_m',1e-6, ...
        'near_invisible_branch_load_ohm',1e12,'stage5b1_model_file', ...
        fullfile(base.root_dir,'results','data','stage5b1','formal','stage5b1_results.mat'));
    if strcmp(mode,'smoke')
        sc.calibration_per_candidate=4;sc.alpha=.20;sc.evidence_calibration.minimum_reference_count=2;
        sc.prior.replicates_per_rate=20;sc.scale.replicates=2;sc.scale.runtime_repetitions=5;sc.parameter.replicates_per_error=2;
    end
end

function rows=scale_grammars(base)
    small=base;small.scale_id='small';small.allowed_branch_main_nodes=[1 2];small.max_branches=1;
    small.max_side_branches_per_node=1;small.max_nodes=7;small.max_candidates=16;
    medium=base;medium.scale_id='medium';
    large=base;large.scale_id='large';large.allowed_branch_main_nodes=[1 2 3];large.max_branches=4;
    large.max_side_branches_per_node=2;large.max_nodes=9;large.max_candidates=64;
    rows=[small medium large];
end
