function dc=stage7a1_diagnostic_config(base,mode)
%STAGE7A1_DIAGNOSTIC_CONFIG Frozen split-calibration diagnosis only.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));
    assert(ismember(mode,{'smoke','formal'}),'stage7a1:Mode','Mode must be smoke or formal.');
    sc=stage7a_profile_search_config(base,mode);
    narrow=[min(sc.stage6b.parameter_search.main_length_scale), ...
        max(sc.stage6b.parameter_search.main_length_scale)];
    broad=sc.search.main_scale_bounds;
    load_broad=sc.search.branch_load_scale_bounds;
    conditions=[condition('matched20_n20',20,narrow,[1 1],20), ...
        condition('matched20_n100',20,narrow,[1 1],100), ...
        condition('matched20_n200',20,narrow,[1 1],200), ...
        condition('snr35_n100',35,narrow,[1 1],100), ...
        condition('nuisance_broad20_n100',20,broad,load_broad,100), ...
        condition('combined_broad35_n20',35,broad,load_broad,20), ...
        condition('combined_broad35_n100',35,broad,load_broad,100)];
    reps=100;
    if strcmp(mode,'smoke')
        reps=2;
        for k=1:numel(conditions),conditions(k).per_candidate=4;end
    end
    dc=struct('stage','Stage 7A.1','mode',mode, ...
        'protocol_version','stage7a1_split_calibration_diagnostic_v1', ...
        'source_commit','38fcced7eac5aa310b7604afebd1807619a05169', ...
        'stage7a_algorithm_commit','64c2ec2258b14d4eb02d15b88cdbb6672e992548', ...
        'stage7a',sc,'conditions',conditions,'test_replicates',reps, ...
        'canonical_replay',strcmp(mode,'formal'), ...
        'set_seed_base',202671100,'evidence_seed_base',302671100, ...
        'test_seed_base',402671100,'condition_seed_stride',1000000, ...
        'library_seed_stride',100000,'candidate_seed_stride',1000, ...
        'test_snr_db',sc.stage6b.scale.snr_db, ...
        'test_main_bounds',narrow,'test_load_bounds',[1 1], ...
        'output_root',fullfile(base.root_dir,'results','data','stage7a_1',mode), ...
        'log_root',fullfile(base.root_dir,'results','logs','stage7a_1'), ...
        'use_parallel',false,'worker_count',0, ...
        'validation_scope','controlled_synthetic_model_internal');
end
function c=condition(name,snr,main,load,n)
    c=struct('name',name,'snr_db',snr,'main_bounds',main, ...
        'load_bounds',load,'per_candidate',n);
end
