function sc = stage4a6_3_1_r1_protocol_config(base_cfg, mode)
%STAGE4A6_3_1_R1_PROTOCOL_CONFIG Metric/calibration closure protocol.
% This configuration is intentionally separate from the historical R run.
% Truth fields are generated for offline scoring only.
    if nargin < 1 || isempty(base_cfg)
        root = fileparts(fileparts(mfilename('fullpath')));
        base_cfg = default_config(root);
    end
    if nargin < 2 || isempty(mode), mode = 'pilot'; end
    old = stage4a6_3_1_r_protocol_config(base_cfg, 'pilot');
    sc = old;
    sc.stage_name = 'Stage 4A.6.3.1-R.1';
    sc.version = '4a6_3_1_r1_metric_calibration_closure_v1';
    sc.code_version = sc.version;
    sc.mode = lower(char(mode));
    sc.output_prefix = 'stage4a6_3_1_r1';
    sc.results_data = fullfile(base_cfg.results_data, 'stage4a6_3_1_r1');
    sc.results_figures = fullfile(base_cfg.results_figures, 'stage4a6_3_1_r1');
    sc.results_logs = fullfile(base_cfg.root_dir, 'results', 'logs', 'stage4a6_3_1_r1');
    sc.cache_dir = fullfile(sc.results_data, 'cache');
    sc.execution = struct('use_parallel', false, 'num_workers', 1, ...
        'resume', false, 'overwrite_completed', false, 'batch_size', 1);
    sc.seeds = struct('calibration', 20266031, 'pilot', 20266032, ...
        'final_reserved', 20266033);
    sc.trial_design = struct('calibration_per_graph', 2, ...
        'pilot_in_domain_per_graph', 1, 'pilot_boundary_per_graph', 1, ...
        'pilot_out_per_graph', 3, 'parameter_jitter_fraction', 0.08, ...
        'severity_names', {{'near','medium','far'}}, ...
        'direction_names', {{'lower','upper'}}, 'final_reserved_count', 7);
    sc.results_mode = 'new_r1_only';
    sc.metric_definition_version = 'stage4a6_3_1_r1_metrics_v1';
    sc.independence_definition_version = 'stage4a6_3_1_r1_independence_v1';
    sc.protocol = struct('scenario_design_version', 'independent_physical_scenarios_v1', ...
        'final_reserved_is_manifest_only', true, ...
        'profile_all_accepted_members', true, ...
        'truth_free_confirmation_adapter', ...
            'stage4a6_3_1_r1_confirm_with_frozen_stage4a5_1', ...
        'parameter_profile_name', 'constrained_residual_profile_not_likelihood', ...
        'candidate_generation_tag', 'synthetic_demo_prior_not_field_data', ...
        'metric_definition_version', sc.metric_definition_version);
end
