function cfg=stage7a3_library_out_config(base,mode)
%STAGE7A3_LIBRARY_OUT_CONFIG Frozen OOD detectability audit design.
%   All data are controlled MATLAB synthetic-model observations.
    if nargin<1||isempty(base),base=default_config(fileparts(fileparts(mfilename('fullpath'))));end
    if nargin<2||isempty(mode),mode='formal';end
    mode=lower(char(mode));
    assert(ismember(mode,{'smoke','formal'}),'stage7a3:Mode','Mode must be smoke or formal.');
    old=stage7a2_set_coverage_config(base,'formal');
    patterns=[3 0 0;0 3 0;3 1 0;3 0 1;1 3 0;0 3 1;2 2 1;2 1 2];
    cfg=struct('stage_name','Stage 7A.3','version','library_out_detectability_audit_v1', ...
        'mode',mode,'legacy',old,'library_out_patterns',patterns, ...
        'gate_alpha',0.05,'frequency_band_count',4, ...
        'development_per_candidate',20,'gate_calibration_per_candidate',200, ...
        'risk_per_candidate',30,'in_library_test_per_candidate',100, ...
        'parameter_out_per_candidate',100,'ood_replicates_per_topology',30, ...
        'snr_db',20,'shift_snr_db',10,'main_bounds',[0.98 1.02], ...
        'parameter_out_low',[0.82 0.88],'parameter_out_high',[1.12 1.18], ...
        'seed_development',590000000,'seed_gate_calibration',600000000, ...
        'seed_risk',610000000,'seed_in_library_test',620000000, ...
        'seed_in_library_snr_shift',660000000, ...
        'seed_parameter_out',650000000,'seed_ood_20db',630000000, ...
        'seed_ood_10db',640000000, ...
        'source_commit','f1e1ed13f296b5e21267bf6aceda4199c8ee86f0', ...
        'use_parallel',false,'worker_count',0, ...
        'output_root',fullfile(base.root_dir,'results','data','stage7a_3'), ...
        'figure_root',fullfile(base.root_dir,'results','figures','stage7a_3'), ...
        'log_root',fullfile(base.root_dir,'results','logs','stage7a_3'));
    if strcmp(mode,'smoke')
        cfg.development_per_candidate=2;cfg.gate_calibration_per_candidate=10;
        cfg.risk_per_candidate=4;cfg.in_library_test_per_candidate=2;
        cfg.parameter_out_per_candidate=2;cfg.ood_replicates_per_topology=2;
    end
end
