function sc = stage4a2_prior_config(base_cfg)
%STAGE4A2_PRIOR_CONFIG Frozen synthetic-prior and robust-matching settings.
%   No field in these priors contains a simulated truth label or a measured
%   CFR. All source tags explicitly identify them as synthetic demonstrations.

    if nargin<1 || isempty(base_cfg)
        root=fileparts(fileparts(mfilename('fullpath'))); base_cfg=default_config(root);
    end
    base4a1=stage4a1_config(base_cfg);
    source_tag='synthetic_demo_prior_not_field_data';
    sc=struct();
    sc.stage_name='Stage 4A.2'; sc.version='4a2_prior_library_v1';
    sc.random_seed=20260906; sc.calibration_seed=20260916; sc.test_seed=20261006;
    sc.output_prefix='stage4a2'; sc.generator=base4a1.generator;
    sc.max_candidates=sc.generator.max_candidates;
    sc.parameter_search_source='default_config.stage2_3.search';
    sc.parameter_search=base_cfg.stage2_3.search;
    sc.parameter_template_count_expected=parameter_count(sc.parameter_search);
    sc.batch_size=24; sc.measurement_kind='siso_forward';
    sc.distance_feature='complex_raw'; sc.distance_weights=[0.5,0.5];
    sc.distance_options=struct('phase_mask_threshold_db',base_cfg.stage2_3.phase_mask_threshold_db);
    sc.tie_tolerance=base_cfg.stage2_3.tie_tolerance;
    sc.frequency_grids=struct( ...
        'id',{'A_stage4a1_quick61','B_ofdm_active_subcarriers'}, ...
        'source',{'stage4a1_config.frequency_hz','default_config.ofdm.active_frequency_hz'}, ...
        'frequency_hz',{base4a1.frequency_hz(:).',base_cfg.ofdm.active_frequency_hz(:).'}, ...
        'nfft',{base_cfg.ofdm.nfft,base_cfg.ofdm.nfft}, ...
        'sample_rate_hz',{base_cfg.ofdm.sample_rate_hz,base_cfg.ofdm.sample_rate_hz}, ...
        'active_bin_1based',{[],base_cfg.ofdm.active_bin_1based(:).'}, ...
        'subcarrier_spacing_hz',{NaN,base_cfg.ofdm.subcarrier_spacing_hz});
    sc.calibration=struct('mismatch_quantile',0.95,'mismatch_safety_factor',1.10, ...
        'minimum_mismatch_threshold',1e-9,'margin_quantile',0.05, ...
        'minimum_margin_threshold',1e-12, ...
        'threshold_name','model-internal calibration threshold');
    sc.prior_scenarios=[ ...
        make_scenario('P0_no_prior',make_prior(source_tag,[],[],sc.generator),source_tag), ...
        make_scenario('P1_partial_consistent_prior',make_prior(source_tag, ...
            edge_rule('TX','M1',true,false,false,0,Inf,[],'main','hard',source_tag), ...
            edge_rule('M3','*',false,false,true,0,Inf,[],'branch','hard',source_tag),sc.generator),source_tag), ...
        make_scenario('P2_stale_or_inconsistent_prior',make_prior(source_tag, ...
            edge_rule('M2','*',false,false,true,0,Inf,[],'branch','hard',source_tag), ...
            edge_rule('M1','*',false,false,false,10,25,1,'branch','soft',source_tag),sc.generator),source_tag)];
end

function n=parameter_count(search)
    n=numel(search.main_length_scale)*numel(search.branch_length_scale)* ...
        numel(search.branch_load_scale)*numel(search.source_impedance_ohm)* ...
        numel(search.receiver_impedance_ohm);
end
function x=make_scenario(id,prior,tag)
    x=struct('id',id,'asset_prior',prior,'source_tag',tag);
end
function prior=make_prior(tag,first,second,g)
    nodes=[node_row('TX','transformer',true,tag),node_row('M1','branch_box',true,tag), ...
        node_row('M2','branch_box',true,tag),node_row('M3','branch_box',true,tag), ...
        node_row('RX','plc_endpoint',true,tag)];
    edges=struct('from',{},'to',{},'allowed',{},'required',{},'forbidden',{}, ...
        'length_min_m',{},'length_max_m',{},'permitted_cable_types',{},'edge_kind',{},'prior_kind',{},'source_tag',{});
    if ~isempty(first), edges(end+1)=first; end %#ok<AGROW>
    if ~isempty(second), edges(end+1)=second; end %#ok<AGROW>
    prior=struct('node_inventory',nodes,'edge_prior',edges, ...
        'network_rules',struct('radial_only',true,'root_node',g.source_node_id, ...
            'receiver_node',g.receiver_node_id,'maximum_degree',3, ...
            'maximum_branch_depth',1,'permitted_branch_nodes',g.allowed_branch_main_nodes, ...
            'permitted_switch_states',{{'closed_tree_only'}}), ...
        'observation_prior',struct('measurement_nodes',{{g.source_node_id,g.receiver_node_id}}, ...
            'direction','forward','terminal_impedance','role_terminated', ...
            'frequency_grid_source','configuration_export','reference_plane_status','simulation_reference_plane'), ...
        'source_tag',tag);
end
function x=node_row(id,role,known,tag)
    x=struct('node_id',id,'node_role',role,'known_or_candidate',known,'source_tag',tag);
end
function x=edge_rule(from,to,allowed,required,forbidden,lo,hi,cables,edge_kind,kind,tag)
    x=struct('from',from,'to',to,'allowed',allowed,'required',required,'forbidden',forbidden, ...
        'length_min_m',lo,'length_max_m',hi,'permitted_cable_types',cables,'edge_kind',edge_kind, ...
        'prior_kind',kind,'source_tag',tag);
end
