function sc = stage4a6_2_profile_config(base_cfg, mode)
%STAGE4A6_2_PROFILE_CONFIG Configuration for profile-stabilization audit.
%   This configuration is independent of historical Stage 4A.6.1 outputs.

    if nargin < 1 || isempty(base_cfg)
        root = fileparts(fileparts(mfilename('fullpath')));
        base_cfg = default_config(root);
    end
    if nargin < 2 || isempty(mode), mode = 'smoke'; end
    mode = lower(char(mode));
    valid = {'smoke','development','formal_a','formal_b'};
    if ~ismember(mode, valid)
        error('stage4a6_2:Mode', 'Unsupported mode: %s', mode);
    end

    parent = stage4a6_1_optimizer_config(base_cfg, 'formal_a');
    sc = parent;
    sc.stage_name = 'Stage 4A.6.2';
    sc.version = '4a6_2_profile_stabilization_v1';
    sc.code_version = sc.version;
    sc.mode = mode;
    sc.output_prefix = 'stage4a6_2';
    sc.results_data = fullfile(base_cfg.results_data, 'stage4a6_2');
    sc.results_figures = fullfile(base_cfg.results_figures, 'stage4a6_2');
    sc.results_logs = fullfile(base_cfg.root_dir, 'results', 'logs', 'stage4a6_2');
    sc.shard_dir = fullfile(sc.results_data, 'shards');
    sc.development_seeds = [20261801 20261802];
    sc.final_seeds = 20261901:20261905;

    sc.profile = struct( ...
        'enabled', true, ...
        'initial_grid_points', 3, ...
        'refinement_points', 2, ...
        'max_refinement_rounds', 1, ...
        'minimum_valid_fraction', 0.80, ...
        'flatness_threshold', 0.05, ...
        'minimum_absolute_dynamic_range', 1e-9, ...
        'profile_max_iterations', 120, ...
        'profile_max_function_evaluations', 400, ...
        'profile_multi_start_count', 1, ...
        'warm_start', true, ...
        'require_all_scan_points', false);
    sc.identifiability = struct( ...
        'baseline_relative_floor', 0.05, ...
        'profile_requires_nonflat', true, ...
        'minimum_sensitivity_floor', 1e-10, ...
        'calibrated_sensitivity_required', false);
    sc.parameter_calibration = struct( ...
        'improvement_quantile', 0.95, ...
        'relative_improvement_quantile', 0.95, ...
        'sensitivity_floor_quantile', 0.05, ...
        'minimum_samples', 2, ...
        'minimum_profile_reliable_samples', 2, ...
        'indeterminate_band', 0.10);
    sc.execution = struct( ...
        'resume', true, ...
        'overwrite_completed', false, ...
        'retry_failed', false, ...
        'batch_size', 1, ...
        'use_parallel', false, ...
        'num_workers', 1, ...
        'parallel_strategy', 'outer_cases');
    sc.parallel = struct('use_parallel', false, 'num_workers', 1, ...
        'benchmark_workers', [1 4]);
    sc.optimization = struct( ...
        'solver', 'auto', ...
        'multi_start_count', 3, ...
        'max_iterations', 160, ...
        'max_function_evaluations', 600, ...
        'tolerance_x', 1e-7, ...
        'tolerance_fun', 1e-9, ...
        'boundary_fraction', 0.05, ...
        'finite_difference_step', 1e-3, ...
        'multistart_distance_tolerance', 1e-3, ...
        'multistart_parameter_tolerance', 0.05);
    sc.protocol_note = ['Profile evidence is computed from observations, candidate definitions, ' ...
        'domains and frozen calibration only; truth labels are offline scoring data.'];

    if strcmp(mode, 'smoke')
        sc.output_prefix = 'stage4a6_2_smoke';
        sc.development_seeds = sc.development_seeds(1);
        sc.final_seeds = sc.final_seeds(1);
        sc.grids = sc.grids(1);
        sc.optimization.multi_start_count = 2;
        sc.optimization.max_iterations = 60;
        sc.optimization.max_function_evaluations = 180;
        sc.profile.initial_grid_points = 3;
        sc.profile.refinement_points = 1;
        sc.profile.max_refinement_rounds = 0;
        sc.profile.profile_max_iterations = 40;
        sc.profile.profile_max_function_evaluations = 120;
        sc.sample_design.calibration_per_graph = 1;
        sc.sample_design.in_domain_per_replicate = 1;
        sc.sample_design.dimensions = sc.sample_design.dimensions(1:2);
        sc.parameter_calibration.minimum_samples = 1;
        sc.parameter_calibration.minimum_profile_reliable_samples = 1;
    elseif strcmp(mode, 'development')
        sc.output_prefix = 'stage4a6_2_development';
        sc.final_seeds = [];
    elseif strcmp(mode, 'formal_a')
        sc.output_prefix = 'stage4a6_2_final_A';
        sc.grids = sc.grids(1);
        sc.development_seeds = [];
    elseif strcmp(mode, 'formal_b')
        sc.output_prefix = 'stage4a6_2_final_B';
        sc.grids = sc.grids(2);
        sc.development_seeds = [];
    end
end
