function audit = audit_candidate_observability(candidates, nominal_library, cfg, tie_tolerance)
%AUDIT_CANDIDATE_OBSERVABILITY Audit full-complex-CFR equivalence classes.
%   Equivalence is configuration specific: noiseless nominal templates are
%   compared by full complex CFR and connected components at tie_tolerance.
%   It is neither graph isomorphism nor a unique-topology decision rule.

    if nargin<4 || isempty(tie_tolerance), tie_tolerance=1e-10; end
    if numel(nominal_library)~=numel(candidates)
        error('audit_candidate_observability:NominalTemplateCount', ...
            'Exactly one nominal template per topology candidate is required.');
    end
    refs=cell(1,numel(candidates)); legacy=repmat(struct('id','','network',struct()),1,numel(candidates));
    fingerprint=cell(1,numel(candidates)); template_ids=cell(1,numel(candidates));
    for k=1:numel(candidates)
        t=nominal_library(k);
        if ~strcmp(t.topology_id,candidates(k).topology_id) || ~t.is_nominal_template
            error('audit_candidate_observability:InvalidNominalLibrary', ...
                'Library order must contain the nominal template for each candidate.');
        end
        refs{k}=t.views; legacy(k)=struct('id',t.topology_id,'network',t.network);
        fingerprint{k}=fingerprint_text(t.views); template_ids{k}=t.template_id;
    end
    core=topology_observability_classes(refs,legacy,cfg.ofdm,tie_tolerance);
    duplicate_keys=unique({candidates.canonical_key});
    classes=cell(1,numel(core.class_members));
    for c=1:numel(classes)
        idx=core.class_members{c}; classes{c}=struct('label',core.class_labels{idx(1)}, ...
            'member_indices',idx,'member_topology_ids',{ {candidates(idx).topology_id} });
    end
    observation=nominal_library(1).observation_summary;
    config_text=sprintf('%s|%s|Zs=%.12g|Zr=%.12g|Nf=%d|tol=%.3g', ...
        observation.measurement_kind,nominal_library(1).forward_model_summary.model, ...
        observation.source_impedance_ohm,observation.receiver_impedance_ohm, ...
        observation.frequency_count,tie_tolerance);
    audit=struct('candidate_count',numel(candidates), ...
        'structural_count_before_dedup',numel(candidates), ...
        'structural_count_after_dedup',numel(duplicate_keys), ...
        'parameter_template_count',numel(nominal_library), ...
        'composite_template_count',numel(nominal_library), ...
        'template_ids',{template_ids},'cfr_fingerprint',{fingerprint}, ...
        'pairwise_complex_distance',core.pairwise_complex_distance, ...
        'equivalence_classes',{classes},'core',core, ...
        'observation_summary',observation,'tie_tolerance',tie_tolerance, ...
        'config_hash',simple_hash(config_text),'config_text',config_text, ...
        'definition',['full-complex CFR connected components under frozen nominal ' ...
            'parameters and observation configuration; not graph isomorphism']);
end

function out=fingerprint_text(views)
    x=[views{:}]; out=sprintf('n=%d|sumRe=%.12g|sumIm=%.12g|energy=%.12g', ...
        numel(x),sum(real(x)),sum(imag(x)),sum(abs(x).^2));
end

function hash=simple_hash(text)
    bytes=double(char(text)); hash=sprintf('%08X',mod(sum(bytes.*(1:numel(bytes))),2^32));
end
