function [ledger,spec,reference,audit] = build_stage4a7_2_r1_uncertain_engineering_prior(reference,sc)
%BUILD_STAGE4A7_2_R1_UNCERTAIN_ENGINEERING_PRIOR Build one shared ledger.
%   The hidden reference graph is used only to construct an offline audit and
%   a controlled observed ledger.  Candidate generation receives only spec,
%   which is built from the ledger below.
    if nargin<2||isempty(sc),error('stage4a7_2_r1:MissingConfig','Config required.');end
    nodes=reference.node_ids;ref=reference.edges;
    edge0=struct('id','','from','','to','','kind','line','length_m',NaN, ...
        'cable_type',NaN,'load',50,'prior_cost',NaN);
    ledger=repmat(struct('node_id','','source_node_id','','receiver_node_id','', ...
        'edge_id','','from_node','','to_node','','edge_status','','edge_confidence','', ...
        'prior_cost',NaN,'length_nominal_m',NaN,'length_lower_m',NaN, ...
        'length_upper_m',NaN,'cable_type_nominal',NaN,'cable_type_candidates','', ...
        'terminal_load_status','','uncertainty_mechanism','','source_dataset','', ...
        'source_network_id','','source_feeder_id','','source_record_id','', ...
        'evidence_level',''),1,0);
    actual_keys=cell(1,numel(ref));
    for k=1:numel(ref)
        actual_keys{k}=endpoint_key(ref(k).from,ref(k).to);
        status='optional';confidence='processed_public_model_reference';cost=0.20;
        if any(strcmp(actual_keys{k},sc.required_edge_keys)),status='required';confidence='anchored_source_receiver_path';cost=0;end
        ledger(end+1)=ledger_row(ref(k),status,confidence,cost, ...
            'controlled_unknown_edge_presence',reference); %#ok<AGROW>
    end
    % Add a small graph-distance-two/three ambiguity layer.  It is explicitly
    % synthetic uncertainty derived from the selected local graph, not GIS.
    for k=1:size(sc.synthetic_ambiguity_edges,1)
        a=char(sc.synthetic_ambiguity_edges{k,1});b=char(sc.synthetic_ambiguity_edges{k,2});
        key=endpoint_key(a,b);
        if any(strcmp(actual_keys,key)),continue;end
        e=edge0;e.id=['SYN_' strrep(key,'--','_')];e.from=a;e.to=b;
        e.length_m=median([ref.length_m]);e.cable_type=0;e.load=50;
        ledger(end+1)=ledger_row(e,'synthetic_ambiguity','controlled_graph_distance_exchange', ...
            1.00, 'synthetic_edge_exchange', reference); %#ok<AGROW>
    end
    allowed=repmat(edge0,1,numel(ledger));cost=zeros(numel(ledger),1);
    for k=1:numel(ledger)
        allowed(k).id=ledger(k).edge_id;allowed(k).from=ledger(k).from_node;
        allowed(k).to=ledger(k).to_node;allowed(k).length_m=ledger(k).length_nominal_m;
        allowed(k).cable_type=ledger(k).cable_type_nominal;allowed(k).load=50;
        allowed(k).prior_cost=ledger(k).prior_cost;cost(k)=ledger(k).prior_cost;
    end
    req=repmat(edge0,1,numel(sc.required_edge_keys));
    for k=1:numel(sc.required_edge_keys)
        pair=strsplit(sc.required_edge_keys{k},'--');j=find(strcmp({ledger.from_node},pair{1}) & strcmp({ledger.to_node},pair{2}),1);
        if isempty(j),j=find(strcmp({ledger.from_node},pair{2}) & strcmp({ledger.to_node},pair{1}),1);end
        if isempty(j),error('stage4a7_2_r1:MissingRequiredEdge','Required edge is not in ledger.');end
        req(k)=allowed(j);
    end
    spec=struct('node_ids',{nodes},'source_node_id',sc.source_node_id, ...
        'receiver_node_id',sc.receiver_node_id,'allowed_edges',allowed, ...
        'required_edges',req,'forbidden_edges',repmat(edge0,1,0), ...
        'edge_prior_cost',cost,'maximum_degree',sc.maximum_degree, ...
        'maximum_candidate_count',sc.maximum_candidate_count,'radial_only',true, ...
        'require_connected',true,'prior_source',sc.prior_source, ...
        'prior_config_hash',stage4a4_scientific_config_hash(ledger));
    audit=struct('shared_ledger',true,'ledger_count',numel(ledger), ...
        'reference_edge_count',numel(ref),'synthetic_ambiguity_count', ...
        nnz(strcmp({ledger.uncertainty_mechanism},'synthetic_edge_exchange')), ...
        'required_count',nnz(strcmp({ledger.edge_status},'required')), ...
        'status','controlled_uncertain_prior_ready');
end
function r=ledger_row(e,status,confidence,cost,mechanism,reference)
    r=struct('node_id','','source_node_id','32','receiver_node_id','39', ...
        'edge_id',e.id,'from_node',e.from,'to_node',e.to,'edge_status',status, ...
        'edge_confidence',confidence,'prior_cost',cost,'length_nominal_m',e.length_m, ...
        'length_lower_m',0.98*e.length_m,'length_upper_m',1.02*e.length_m, ...
        'cable_type_nominal',e.cable_type,'cable_type_candidates',sprintf('%d',e.cable_type), ...
        'terminal_load_status','controlled_nominal_50_ohm', ...
        'uncertainty_mechanism',mechanism,'source_dataset',reference.source_table(1).source_dataset, ...
        'source_network_id',reference.source_table(1).source_network_id, ...
        'source_feeder_id',reference.source_table(1).source_feeder_id, ...
        'source_record_id',e.id,'evidence_level','derived_public_processed_model');
end
function k=endpoint_key(a,b),p=sort({char(a),char(b)});k=[p{1} '--' p{2}];end
