function labels = build_stage4a3_1_truth_equivalence_labels(bank, p0_audit, current_audit, candidates, grid_id, scenario_id, config_hash)
%BUILD_STAGE4A3_1_TRUTH_EQUIVALENCE_LABELS Create offline-only truth labels.
%   Baseline labels always come from the complete P0 audit. Current labels
%   describe the candidate set after the selected hard prior. No label is
%   consumed by match_cached_composite_library_open_set.

    if nargin < 7, config_hash = ''; end
    labels = repmat(empty_label(), numel(bank), 1);
    current_ids = cell(1, numel(candidates));
    for k = 1:numel(candidates), current_ids{k} = candidates(k).topology_id; end
    for k = 1:numel(bank)
        truth_id = bank(k).truth_topology_id;
        [base_class, base_size] = class_for_id(p0_audit, truth_id);
        [current_class, current_size] = class_for_id(current_audit, truth_id);
        in_current = any(strcmp(current_ids, truth_id));
        if strcmp(bank(k).category, 'in_library_continuous') && in_current
            status = 'covered';
        elseif strcmp(bank(k).category, 'in_library_continuous') && ~in_current
            status = 'excluded_by_prior';
        elseif strcmp(bank(k).category, 'structure_out')
            status = 'out_of_library_structure';
        else
            status = 'out_of_library_parameter';
        end
        t = bank(k).truth_theta;
        labels(k) = struct('sample_id',bank(k).sample_id,'split',bank(k).split, ...
            'grid_id',grid_id,'scenario_id',scenario_id,'category',bank(k).category, ...
            'truth_topology_id',truth_id,'truth_canonical_key',bank(k).canonical_key, ...
            'coverage_status',status,'truth_covered',strcmp(status,'covered'), ...
            'baseline_P0_equivalence_class',base_class, ...
            'baseline_P0_equivalence_class_size',base_size, ...
            'truth_is_observationally_nonunique',base_size > 1, ...
            'prior_conditioned_equivalence_class',current_class, ...
            'prior_conditioned_equivalence_class_size',current_size, ...
            'prior_collapsed_equivalence',base_size > 1 && current_size == 1 && in_current, ...
            'truth_main_length_scale',t.main_length_scale, ...
            'truth_branch_length_scale',t.branch_length_scale, ...
            'truth_branch_load_scale',t.branch_load_scale, ...
            'truth_source_impedance_ohm',t.source_impedance_ohm, ...
            'truth_receiver_impedance_ohm',t.receiver_impedance_ohm, ...
            'outlier_dimension',bank(k).outlier_dimension, ...
            'outlier_direction',bank(k).outlier_direction, ...
            'source_tag',bank(k).source_tag,'config_hash',config_hash);
    end
end

function row = empty_label()
    row = struct('sample_id','','split','','grid_id','','scenario_id','', ...
        'category','','truth_topology_id','','truth_canonical_key','', ...
        'coverage_status','','truth_covered',false, ...
        'baseline_P0_equivalence_class','','baseline_P0_equivalence_class_size',0, ...
        'truth_is_observationally_nonunique',false, ...
        'prior_conditioned_equivalence_class','', ...
        'prior_conditioned_equivalence_class_size',0, ...
        'prior_collapsed_equivalence',false, ...
        'truth_main_length_scale',NaN,'truth_branch_length_scale',NaN, ...
        'truth_branch_load_scale',NaN,'truth_source_impedance_ohm',NaN, ...
        'truth_receiver_impedance_ohm',NaN,'outlier_dimension','', ...
        'outlier_direction','','source_tag','','config_hash','');
end

function [label, size_value] = class_for_id(audit, topology_id)
    label = '';
    size_value = 0;
    if isempty(audit) || ~isfield(audit, 'equivalence_classes'), return; end
    for k = 1:numel(audit.equivalence_classes)
        ids = audit.equivalence_classes{k}.member_topology_ids;
        if any(strcmp(ids, topology_id))
            label = audit.equivalence_classes{k}.label;
            size_value = numel(audit.equivalence_classes{k}.member_indices);
            return;
        end
    end
end
