function library = build_composite_topology_library(f_hz, candidates, theta_grid, measurement_kind, cfg, max_templates)
%BUILD_COMPOSITE_TOPOLOGY_LIBRARY Build bounded (graph,theta) CFR templates.
%   Graph candidates remain separate from parameter templates.  Each output
%   item records the physical/measurement semantics required to reproduce its
%   noiseless full-network CFR views; no classifier or decision is applied.

    if nargin<6 || isempty(max_templates), max_templates=Inf; end
    if isempty(candidates)||isempty(theta_grid)
        error('build_composite_topology_library:EmptyInput','Candidates and theta_grid are required.');
    end
    total=numel(candidates)*numel(theta_grid);
    if total>max_templates
        error('build_composite_topology_library:MaxTemplatesExceeded', ...
            'Requested %d composite templates, above configured maximum %d.',total,max_templates);
    end
    item=empty_item(); library=repmat(item,1,total); cursor=0;
    for g=1:numel(candidates)
        for q=1:numel(theta_grid)
            cursor=cursor+1; theta=theta_grid(q);
            [network,local_cfg]=topology_apply_parameters(candidates(g).network,cfg,theta);
            [measurement,metadata]=plc_measurement_bundle(measurement_kind,network,theta,local_cfg);
            [views,details]=plc_multiview_response(f_hz,network,measurement,local_cfg);
            if any(cellfun(@(x)any(~isfinite(x(:))),views))
                error('build_composite_topology_library:NonfiniteCFR','Template %s has nonfinite CFR.',candidates(g).topology_id);
            end
            library(cursor)=struct('template_id',sprintf('%s_P%03d',candidates(g).topology_id,q), ...
                'topology_id',candidates(g).topology_id,'topology_index',g, ...
                'canonical_key',candidates(g).canonical_key,'theta',theta, ...
                'parameter_grid_index',q,'is_nominal_template',theta.regularization==0, ...
                'network',network,'views',{views},'measurement_kind',char(measurement_kind), ...
                'measurement_metadata',metadata,'response_details',details, ...
                'regularization',theta.regularization, ...
                'forward_model_summary',struct('model','complete-tree distributed-line nodal-admittance model', ...
                    'frequency_hz',f_hz(:).','kG',local_cfg.kG), ...
                'observation_summary',struct('measurement_kind',char(measurement_kind), ...
                    'source_impedance_ohm',metadata.source_impedance_role_ohm, ...
                    'receiver_impedance_ohm',metadata.receiver_impedance_role_ohm, ...
                    'port_reference_ohm',local_cfg.port_reference_ohm, ...
                    'frequency_band_hz',[min(f_hz),max(f_hz)],'frequency_count',numel(f_hz)));
        end
    end
end

function x=empty_item()
    x=struct('template_id','','topology_id','','topology_index',0,'canonical_key','', ...
        'theta',struct(),'parameter_grid_index',0,'is_nominal_template',false, ...
        'network',struct(),'views',{{}},'measurement_kind','','measurement_metadata',struct(), ...
        'response_details',struct(),'regularization',NaN,'forward_model_summary',struct(), ...
        'observation_summary',struct());
end
