function thresholds = calibrate_stage4a3_1_thresholds(decisions, labels, sc, grid_id, config_hash)
%CALIBRATE_STAGE4A3_1_THRESHOLDS Freeze P0 calibration-only thresholds.
%   Residual threshold: high quantile of all finite P0 calibration residuals
%   times the frozen safety factor. Margin threshold: low quantile of samples
%   whose baseline truth class is a singleton and whose nearest topology is
%   the truth. No test or P1/P2 sample is accepted by this function.

    if numel(decisions) ~= numel(labels)
        error('calibrate_stage4a3_1_thresholds:Alignment', ...
            'Decisions and labels must have equal length.');
    end
    if any(~strcmp({labels.split}, 'calibration')) || ...
            any(~strcmp({labels.scenario_id}, 'P0_no_prior'))
        error('calibrate_stage4a3_1_thresholds:WrongCalibrationSet', ...
            'Thresholds must use P0 calibration labels only.');
    end
    d = [decisions.best_distance];
    d = d(isfinite(d));
    eligible = false(1, numel(labels));
    for k = 1:numel(labels)
        eligible(k) = labels(k).truth_covered && ...
            labels(k).baseline_P0_equivalence_class_size == 1 && ...
            strcmp(decisions(k).best_topology_id, labels(k).truth_topology_id) && ...
            isfinite(decisions(k).margin);
    end
    margins = [decisions(eligible).margin];
    margins = margins(isfinite(margins));
    if numel(d) < sc.calibration.minimum_residual_samples
        error('calibrate_stage4a3_1_thresholds:InsufficientResidualSamples', ...
            'Only %d finite residual samples; at least %d are required.', ...
            numel(d), sc.calibration.minimum_residual_samples);
    end
    if numel(margins) < sc.calibration.minimum_margin_samples
        error('calibrate_stage4a3_1_thresholds:InsufficientMarginSamples', ...
            'Only %d eligible margin samples; at least %d are required.', ...
            numel(margins), sc.calibration.minimum_margin_samples);
    end
    residual_q = empirical_quantile(d, sc.calibration.residual_quantile);
    margin_q = empirical_quantile(margins, sc.calibration.margin_quantile);
    thresholds = struct('name',sc.calibration.threshold_name, ...
        'residual_threshold',max(sc.calibration.minimum_residual_threshold, ...
            residual_q * sc.calibration.residual_safety_factor), ...
        'margin_threshold',max(sc.calibration.minimum_margin_threshold, margin_q), ...
        'residual',max(sc.calibration.minimum_residual_threshold, ...
            residual_q * sc.calibration.residual_safety_factor), ...
        'margin',max(sc.calibration.minimum_margin_threshold, margin_q), ...
        'grid_id',grid_id,'sample_count',numel(decisions), ...
        'residual_calibration_count',numel(d), ...
        'margin_calibration_count',numel(margins), ...
        'residual_quantile',sc.calibration.residual_quantile, ...
        'margin_quantile',sc.calibration.margin_quantile, ...
        'residual_quantile_value',residual_q, ...
        'margin_quantile_value',margin_q, ...
        'residual_safety_factor',sc.calibration.residual_safety_factor, ...
        'calibration_seed',sc.calibration_seed,'test_seed',sc.test_seed, ...
        'configuration_hash',config_hash,'source','P0 calibration set only');
end

function value = empirical_quantile(x, p)
    x = sort(x(isfinite(x)));
    if isempty(x), value = NaN; return; end
    index = 1 + (numel(x)-1)*p;
    lower = floor(index); upper = ceil(index);
    if lower == upper, value = x(lower); else
        value = x(lower) + (index-lower)*(x(upper)-x(lower));
    end
end
