function model = calibrate_parameter_domain_detector(calibration_evidence,sc,eta,hash)
%CALIBRATE_PARAMETER_DOMAIN_DETECTOR Freeze thresholds from in-domain data.
    if isempty(calibration_evidence),error('stage4a6:EmptyCalibration','Calibration evidence is empty.');end
    lam=[calibration_evidence.lambda];rel=[calibration_evidence.relative_improvement];sens=[calibration_evidence.minimum_sensitivity];
    if numel(lam)<sc.parameter_calibration.minimum_samples,error('stage4a6:CalibrationCount','Insufficient calibration evidence.');end
    model=struct('eta',eta,'lambda_threshold',q(lam,sc.parameter_calibration.improvement_quantile), ...
        'relative_improvement_threshold',q(rel,sc.parameter_calibration.relative_improvement_quantile), ...
        'sensitivity_floor',max(q(sens,sc.parameter_calibration.sensitivity_floor_quantile),1e-8), ...
        'boundary_fraction',sc.optimization.boundary_fraction,'calibration_sample_count',numel(lam), ...
        'calibration_hash',stage4a4_scientific_config_hash(struct('evidence',calibration_evidence,'eta',eta,'rule',sc.parameter_calibration,'experiment_hash',hash)), ...
        'source','in-domain development/calibration evidence only');
end
function y=q(x,p),x=sort(x(isfinite(x)));if isempty(x),y=NaN;elseif numel(x)==1,y=x;else,t=1+(numel(x)-1)*p;l=floor(t);h=ceil(t);y=x(l)+(t-l)*(x(h)-x(l));end,end
