function model = calibrate_stage4a6_1_parameter_domain(calibration_evidence,sc,eta,hash)
%CALIBRATE_STAGE4A6_1_PARAMETER_DOMAIN Calibrate only from reliable profiles.

    if isempty(calibration_evidence)
        model=empty_model(eta,hash,'insufficient_calibration',0); return;
    end
    reliable=false(size(calibration_evidence));
    for k=1:numel(calibration_evidence),reliable(k)=isfield(calibration_evidence(k),'profile_reliable')&&calibration_evidence(k).profile_reliable;end
    e=calibration_evidence(reliable);n=numel(e);
    if n<sc.parameter_calibration.minimum_samples
        model=empty_model(eta,hash,'insufficient_calibration',n);return;
    end
    lam=[e.lambda];rel=[e.relative_improvement];sens=[e.minimum_sensitivity];
    model=struct('eta',eta,'lambda_threshold',quantile_safe(lam,sc.parameter_calibration.improvement_quantile), ...
        'relative_improvement_threshold',quantile_safe(rel,sc.parameter_calibration.relative_improvement_quantile), ...
        'sensitivity_floor',max(quantile_safe(sens,sc.parameter_calibration.sensitivity_floor_quantile),1e-12), ...
        'boundary_fraction',sc.optimization.boundary_fraction,'calibration_sample_count',n, ...
        'total_calibration_sample_count',numel(calibration_evidence), ...
        'profile_reliable_rate',n/numel(calibration_evidence), ...
        'calibration_status','calibrated','calibration_valid',true, ...
        'calibration_hash',stage4a4_scientific_config_hash(struct('evidence',e,'eta',eta,'rule',sc.parameter_calibration,'experiment_hash',hash)), ...
        'source','reliable in-domain calibration profiles only');
end
function m=empty_model(eta,hash,status,n)
    m=struct('eta',eta,'lambda_threshold',NaN,'relative_improvement_threshold',NaN, ...
        'sensitivity_floor',NaN,'boundary_fraction',NaN,'calibration_sample_count',n, ...
        'total_calibration_sample_count',n,'profile_reliable_rate',NaN, ...
        'calibration_status',status,'calibration_valid',false, ...
        'calibration_hash',hash,'source','no threshold generated');
end
function y=quantile_safe(x,p)
    x=sort(x(isfinite(x)));if isempty(x),y=NaN;elseif numel(x)==1,y=x;else,t=1+(numel(x)-1)*p;l=floor(t);h=ceil(t);y=x(l)+(t-l)*(x(h)-x(l));end
end
