function evidence = compute_stage4a6_2_member_evidence(observed_views, frequency_hz, candidate, cfg, domain, initial_thetas, options)
%COMPUTE_STAGE4A6_2_MEMBER_EVIDENCE Per-member and per-parameter evidence.
%   This interface never receives truth labels or coverage status.

    if nargin < 7 || isempty(options), options = struct(); end
    names = domain.names(:).';
    mask = topology_active_parameter_mask(candidate, names);
    active_names = names(mask);
    ib = struct('names',{active_names},'lower',domain.in_lower(mask),'upper',domain.in_upper(mask));
    eb = struct('names',{active_names},'lower',domain.ext_lower(mask),'upper',domain.ext_upper(mask));
    rin = optimize_stage4a6_1_parameters(observed_views,frequency_hz,candidate,cfg,ib,initial_thetas,options);
    rext = optimize_stage4a6_1_parameters(observed_views,frequency_hz,candidate,cfg,eb, ...
        [rin.theta initial_thetas],options);
    jac = compute_stage4a6_1_jacobian(frequency_hz,candidate,cfg,rext.theta,domain,options);
    ident = analyze_parameter_identifiability(jac);
    prof_options = options.profile;
    if ~isfield(prof_options,'enabled'), prof_options.enabled = false; end
    prof = compute_stage4a6_2_parameter_profile(observed_views,frequency_hz,candidate,cfg,domain, ...
        rin,rext,initial_thetas,prof_options);
    active_ident = ident.effective_rank >= numel(active_names) && ...
        all(ident.sensitivity_norms >= getopt(options,'minimum_sensitivity_floor',1e-10));
    residual_finite = rin.residual_finite && rext.residual_finite;
    optimizer_converged = rin.optimizer_converged && rext.optimizer_converged;
    multistart_consistent = rin.multistart_consistent && rext.multistart_consistent;
    profile_computed = any([prof.profile_computed]);
    profile_reliable = profile_computed && all(~[prof(mask).active] | [prof(mask).profile_reliable]);
    if isempty(prof)
        profile_reliable = false;
    end
    boundary = boundary_summary(rin,domain,active_names,candidate,cfg,observed_views,frequency_hz,options);
    parameter_evidence = repmat(parameter_template(), numel(names), 1);
    for k = 1:numel(names)
        parameter_evidence(k).parameter_name = names{k};
        parameter_evidence(k).active = mask(k);
        if ~mask(k)
            parameter_evidence(k).profile_status = 'inactive';
            parameter_evidence(k).reliability_reason = 'inactive parameter';
            continue;
        end
        p = prof(k);
        parameter_evidence(k).profile_status = p.profile_status;
        parameter_evidence(k).in_domain_min_distance = p.in_min_distance;
        parameter_evidence(k).extended_min_distance = p.ext_min_distance;
        parameter_evidence(k).absolute_improvement = p.lambda;
        parameter_evidence(k).relative_improvement = p.relative_improvement;
        parameter_evidence(k).extended_optimum = p.ext_min_value;
        parameter_evidence(k).extended_optimum_outside = p.extended_min_outside;
        parameter_evidence(k).boundary_behavior = boundary_label(rin,domain,names{k});
        parameter_evidence(k).outward_decrease = outward_decrease_for(names{k},active_names,boundary.outward_distance_change);
        parameter_evidence(k).flatness_metric = p.flatness_metric;
        parameter_evidence(k).relative_dynamic_range = getfield_default(p,'relative_dynamic_range',p.flatness_metric);
        parameter_evidence(k).absolute_dynamic_range = getfield_default(p,'absolute_dynamic_range',NaN);
        parameter_evidence(k).valid_point_fraction = p.profile_valid_fraction;
        parameter_evidence(k).local_sensitivity = sensitivity_for(names{k},active_names,ident.sensitivity_norms);
        parameter_evidence(k).multistart_evaluated = getfield_default(p,'profile_multistart_evaluated',false);
        parameter_evidence(k).multistart_consistent = getfield_default(p,'profile_multistart_consistent','not_applicable');
        parameter_evidence(k).profile_reliable = p.profile_reliable;
        parameter_evidence(k).reliability_reason = p.reliability_reason;
        if ~p.profile_computed
            parameter_evidence(k).profile_status = 'not_computed';
        elseif ~p.profile_reliable && strcmp(p.profile_status,'indeterminate')
            parameter_evidence(k).profile_status = 'indeterminate';
        end
    end
    evidence = struct( ...
        'topology_id',candidate.topology_id, ...
        'canonical_key',getfield_default(candidate,'canonical_key',''), ...
        'active_parameter_names',{active_names}, ...
        'active_parameter_mask',mask, ...
        'active_parameter_count',numel(active_names), ...
        'in_distance',rin.distance,'ext_distance',rext.distance, ...
        'in_theta',rin.theta,'ext_theta',rext.theta, ...
        'lambda',rin.distance^2-rext.distance^2, ...
        'relative_improvement',(rin.distance-rext.distance)/(rin.distance+1e-12), ...
        'extended_outside',any(rext.theta_vector(mask)<domain.in_lower(mask)-1e-10 | ...
            rext.theta_vector(mask)>domain.in_upper(mask)+1e-10), ...
        'boundary_hit',boundary.boundary_hit, ...
        'outward_decrease',boundary.outward_decrease, ...
        'minimum_boundary_distance',boundary.minimum_boundary_distance, ...
        'outward_distance_change',boundary.outward_distance_change, ...
        'minimum_sensitivity',min_or_nan(ident.sensitivity_norms), ...
        'sensitivity_norms',ident.sensitivity_norms, ...
        'low_sensitivity_baseline',ident.low_sensitivity, ...
        'singular_values',ident.singular_values, ...
        'condition_number',ident.condition_number, ...
        'effective_rank',ident.effective_rank, ...
        'optimizer_converged',optimizer_converged, ...
        'multistart_consistent',multistart_consistent, ...
        'residual_finite',residual_finite, ...
        'active_parameters_identifiable',active_ident, ...
        'profile_computed',profile_computed, ...
        'profile_reliable',profile_reliable, ...
        'profile_summary',prof, ...
        'parameter_evidence',parameter_evidence, ...
        'in_optimization',rin,'ext_optimization',rext);
end

function p = parameter_template()
    p = struct('parameter_name','','active',false,'profile_status','not_computed', ...
        'in_domain_min_distance',NaN,'extended_min_distance',NaN, ...
        'absolute_improvement',NaN,'relative_improvement',NaN,'extended_optimum',NaN, ...
        'extended_optimum_outside',false,'boundary_behavior','none','outward_decrease',false, ...
        'flatness_metric',NaN,'relative_dynamic_range',NaN,'absolute_dynamic_range',NaN, ...
        'valid_point_fraction',0,'local_sensitivity',NaN,'multistart_evaluated',false, ...
        'multistart_consistent','not_applicable','profile_reliable',false, ...
        'reliability_reason','');
end
function label = boundary_label(r,domain,name)
    k=find(strcmp(domain.names,name),1);if isempty(k),label='none';return;end
    x=r.theta.(name);w=domain.in_upper(k)-domain.in_lower(k);p=(x-domain.in_lower(k))/w;
    if p<=0.05,label='lower_boundary';elseif p>=0.95,label='upper_boundary';else,label='interior';end
end
function s = sensitivity_for(name,names,v),k=find(strcmp(names,name),1);if isempty(k),s=NaN;else,s=v(k);end,end
function v = outward_decrease_for(name,names,changes),k=find(strcmp(names,name),1);if isempty(k),v=false;else,v=isfinite(changes(k))&&changes(k)<0;end,end
function v = min_or_nan(x),x=x(isfinite(x));if isempty(x),v=NaN;else,v=min(x);end,end
function v=getfield_default(s,f,d),if isstruct(s)&&isfield(s,f),v=s.(f);else,v=d;end,end
function v=getopt(s,n,d),if isfield(s,n)&&~isempty(s.(n)),v=s.(n);else,v=d;end,end

function out=boundary_summary(r,domain,names,candidate,cfg,obs,freq,options)
    lo=domain.in_lower(ismember(domain.names,names));hi=domain.in_upper(ismember(domain.names,names));
    x=zeros(1,numel(names));for k=1:numel(names),x(k)=r.theta.(names{k});end;w=hi-lo;
    pos=(x-lo)./w;nearlo=pos<=getopt(options,'boundary_fraction',0.05);nearhi=pos>=1-getopt(options,'boundary_fraction',0.05);trend=NaN(size(x));
    for k=1:numel(names)
        if nearlo(k)||nearhi(k)
            q=x; idx=find(strcmp(domain.names,names{k}),1); step=getopt(options,'finite_difference_step',1e-3)*w(k);
            if nearlo(k),q(k)=max(domain.ext_lower(idx),x(k)-step);else,q(k)=min(domain.ext_upper(idx),x(k)+step);end
            trend(k)=fixed_distance(q);
        end
    end
    base=r.distance;change=trend-base;out=struct('boundary_hit',any(nearlo|nearhi), ...
        'outward_decrease',any(isfinite(change)&change<0),'minimum_boundary_distance',min(min(pos,1-pos)), ...
        'outward_distance_change',change);
    function d=fixed_distance(q)
        t=r.theta;for j=1:numel(names),t.(names{j})=q(j);end
        [n,lc]=topology_apply_parameters(candidate.network,cfg,t);[m,~]=plc_measurement_bundle('siso_forward',n,t,lc);[v,~]=plc_multiview_response(freq,n,m,lc);e=0;nn=0;
        for j=1:numel(v),z=v{j}(:)-obs{j}(:);e=e+sum(abs(z).^2);nn=nn+numel(z);end
        d=sqrt(e/max(nn,1));
    end
end
