function evidence = compute_stage4a6_1_member_evidence(observed_views,frequency_hz,candidate,cfg,domain,initial_thetas,options)
%COMPUTE_STAGE4A6_1_MEMBER_EVIDENCE Stable orthogonal parameter evidence.

    names=domain.names(:).'; mask=topology_active_parameter_mask(candidate,names);
    active_names=names(mask); ib=struct('names',{active_names}, ...
        'lower',domain.in_lower(mask),'upper',domain.in_upper(mask));
    eb=struct('names',{active_names}, ...
        'lower',domain.ext_lower(mask),'upper',domain.ext_upper(mask));
    rin=optimize_stage4a6_1_parameters(observed_views,frequency_hz,candidate,cfg,ib,initial_thetas,options);
    rext=optimize_stage4a6_1_parameters(observed_views,frequency_hz,candidate,cfg,eb, ...
        [rin.theta initial_thetas],options);
    jac=compute_stage4a6_1_jacobian(frequency_hz,candidate,cfg,rext.theta,domain,options);
    ident=analyze_parameter_identifiability(jac);
    prof=compute_stage4a6_1_profile(observed_views,frequency_hz,candidate,cfg,domain,rin,rext,initial_thetas,options.profile);
    active_identifiable=ident.effective_rank>=numel(active_names) && ~any(ident.low_sensitivity);
    residual_finite=rin.residual_finite && rext.residual_finite;
    optimizer_converged=rin.optimizer_converged && rext.optimizer_converged;
    multistart_consistent=rin.multistart_consistent && rext.multistart_consistent;
    profile_reliable=residual_finite && optimizer_converged && multistart_consistent && ...
        active_identifiable && (isempty(prof) || all([prof.scan_reliable]));
    profile_outside=false; profile_lambda=NaN; profile_relative=NaN;
    if ~isempty(prof)
        profile_outside=any([prof.extended_min_outside]);
        profile_lambda=max([prof.lambda]); profile_relative=max([prof.relative_improvement]);
    end
    boundary=boundary_summary(rin,domain,active_names,candidate,cfg,observed_views,frequency_hz,options);
    evidence=struct('topology_id',candidate.topology_id, ...
        'active_parameter_names',{active_names},'active_parameter_mask',mask, ...
        'active_parameter_count',numel(active_names), ...
        'in_distance',rin.distance,'ext_distance',rext.distance, ...
        'in_theta',rin.theta,'ext_theta',rext.theta, ...
        'lambda',rin.distance^2-rext.distance^2, ...
        'relative_improvement',(rin.distance-rext.distance)/(rin.distance+1e-12), ...
        'extended_outside',any(rext.theta_vector(mask)<domain.in_lower(mask)-1e-10 | ...
            rext.theta_vector(mask)>domain.in_upper(mask)+1e-10), ...
        'profile_outside',profile_outside,'profile_lambda',profile_lambda, ...
        'profile_relative_improvement',profile_relative, ...
        'profile_summary',prof,'boundary_hit',boundary.boundary_hit, ...
        'outward_decrease',boundary.outward_decrease, ...
        'minimum_boundary_distance',boundary.minimum_boundary_distance, ...
        'outward_distance_change',boundary.outward_distance_change, ...
        'minimum_sensitivity',min(ident.sensitivity_norms), ...
        'sensitivity_norms',ident.sensitivity_norms, ...
        'singular_values',ident.singular_values,'condition_number',ident.condition_number, ...
        'effective_rank',ident.effective_rank,'low_sensitivity',ident.low_sensitivity, ...
        'optimizer_converged',optimizer_converged, ...
        'multistart_consistent',multistart_consistent, ...
        'residual_finite',residual_finite, ...
        'active_parameters_identifiable',active_identifiable, ...
        'profile_reliable',profile_reliable, ...
        'in_optimization',rin,'ext_optimization',rext);
end

function out=boundary_summary(r,domain,names,candidate,cfg,obs,freq,options)
    lo=domain.in_lower(ismember(domain.names,names));hi=domain.in_upper(ismember(domain.names,names));
    x=zeros(1,numel(names));for k=1:numel(names),x(k)=r.theta.(names{k});end;w=hi-lo;
    pos=(x-lo)./w;nearlo=pos<=getopt(options,'boundary_fraction',0.05);nearhi=pos>=1-getopt(options,'boundary_fraction',0.05);trend=NaN(size(x));
    for k=1:numel(names),if nearlo(k)||nearhi(k),q=x;if nearlo(k),q(k)=max(domain.ext_lower(find(strcmp(domain.names,names{k}))),x(k)-getopt(options,'finite_difference_step',1e-3)*w(k));else,q(k)=min(domain.ext_upper(find(strcmp(domain.names,names{k}))),x(k)+getopt(options,'finite_difference_step',1e-3)*w(k));end;trend(k)=fixed_distance(q);end,end
    out=struct('boundary_hit',any(nearlo|nearhi),'outward_decrease',any(trend<0),'minimum_boundary_distance',min(min(pos,1-pos)),'outward_distance_change',trend);
    function d=fixed_distance(q)
        t=r.theta;for j=1:numel(names),t.(names{j})=q(j);end;[n,lc]=topology_apply_parameters(candidate.network,cfg,t);[m,~]=plc_measurement_bundle('siso_forward',n,t,lc);[v,~]=plc_multiview_response(freq,n,m,lc);e=0;nn=0;for j=1:numel(v),z=v{j}(:)-obs{j}(:);e=e+sum(abs(z).^2);nn=nn+numel(z);end;d=sqrt(e/max(nn,1));
    end
end
function v=getopt(s,n,d),if isfield(s,n)&&~isempty(s.(n)),v=s.(n);else,v=d;end,end
