function r=match_composite_topology_library_open_set(observed_views,f,candidates,grid,cfg,opt)
%MATCH_COMPOSITE_TOPOLOGY_LIBRARY_OPEN_SET Decision has no truth/coverage input.
req={'measurement_kind','tie_tolerance','feature','weights','batch_size','thresholds'};for k=1:numel(req),assert(isfield(opt,req{k}),'missing option');end
if isempty(candidates)
 r=struct('best_template_id','','best_topology_id','', ...
  'best_topology_index',NaN,'best_equivalence_class','','best_parameter_values',struct(), ...
  'best_distance',Inf,'second_competing_class','','second_distance',Inf,'margin',NaN, ...
  'topology_scores',[],'class_scores',[],'class_audit',struct(), ...
  'candidate_count_before_prior',getopt(opt,'candidate_count_before_prior',0), ...
  'candidate_count_after_prior',0,'parameter_template_count',numel(grid), ...
  'composite_template_count',0,'streaming_used',true,'config_hash',getopt(opt,'config_hash',''), ...
  'decision','reject_no_feasible_candidate','thresholds',opt.thresholds);
 return
end
ni=find([grid.regularization]==0,1);nom=build_composite_topology_library(f,candidates,grid(ni),opt.measurement_kind,cfg,numel(candidates));audit=audit_candidate_observability(candidates,nom,cfg,opt.tie_tolerance);
s=Inf(1,numel(candidates));best_parameter=zeros(1,numel(candidates));bid=cell(1,numel(candidates));cursor=1;
while cursor<=numel(candidates)*numel(grid)
 b=stream_composite_library_templates(candidates,grid,cursor,opt.batch_size);
 for q=1:numel(b.items),x=b.items(q);[n,cfgx]=topology_apply_parameters(candidates(x.topology_index).network,cfg,x.theta);[m,~]=plc_measurement_bundle(opt.measurement_kind,n,x.theta,cfgx);v=plc_multiview_response(f,n,m,cfgx);d=dist(observed_views,v,opt.feature,cfg.ofdm,opt.weights);if d<s(x.topology_index),s(x.topology_index)=d;best_parameter(x.topology_index)=x.parameter_grid_index;bid{x.topology_index}=x.template_id;end,end
 cursor=b.next_index;
end
ci=audit.core.class_index;cs=Inf(1,max(ci));ix=zeros(size(cs));for c=1:numel(cs),z=find(ci==c);[cs(c),j]=min(s(z));ix(c)=z(j);end
[d1,c1]=min(cs);z=cs;z(c1)=Inf;[d2,c2]=min(z);if isinf(d2),second_label='';else,second_label=audit.core.class_labels{find(ci==c2,1)};end;margin=d2-d1;best=ix(c1);lab=audit.core.class_labels{best};
if d1>opt.thresholds.residual,decision='reject_model_mismatch';elseif audit.core.class_sizes(c1)>1||margin<opt.thresholds.margin,decision='equivalence_class';else,decision='unique_topology';end
r=struct('best_distance',d1,'second_distance',d2,'margin',margin, ...
 'best_topology_id',candidates(best).topology_id,'best_topology_index',best, ...
 'best_template_id',bid{best},'best_equivalence_class',lab, ...
 'second_competing_class',second_label, ...
 'best_parameter_values',grid(best_parameter(best)), ...
 'topology_scores',s,'class_scores',cs,'class_audit',audit, ...
 'candidate_count_before_prior',getopt(opt,'candidate_count_before_prior',numel(candidates)), ...
 'candidate_count_after_prior',numel(candidates), ...
 'parameter_template_count',numel(grid), ...
 'composite_template_count',numel(candidates)*numel(grid), ...
 'streaming_used',true,'config_hash',getopt(opt,'config_hash',''), ...
 'decision',decision,'thresholds',opt.thresholds);
end
function d=dist(a,b,f,o,w),x=zeros(1,numel(a));for i=1:numel(a),x(i)=topology_feature_distance(a{i},b{i},f,o,w);end,d=sqrt(mean(x.^2));end
function v=getopt(s,name,default)
if isfield(s,name)&&~isempty(s.(name)),v=s.(name);else,v=default;end
end
