function shard = run_stage4a6_2_case(case_spec, context)
%RUN_STAGE4A6_2_CASE Execute one compact profile case.
%   case_spec contains only experiment identity; context contains the
%   observation, candidate, domain and frozen solver configuration.

    started=tic;
    shard=struct('case_id',case_spec.case_id,'scientific_hash',context.scientific_hash, ...
        'source_tree_hash',context.source_tree_hash,'status','failed','exit_status',1, ...
        'parameter_name',getfield_default(case_spec,'parameter_name',''), ...
        'started_at',datestr(now,30),'finished_at','','runtime_s',NaN, ...
        'profile_summary',struct([]),'error_identifier','','error_message','', ...
        'optimizer_state',struct(),'checksum','', ...
        'attempt_count',getfield_default(case_spec,'attempt_count',1), ...
        'retry_count',getfield_default(case_spec,'retry_count',0), ...
        'attempt_history',getfield_default(case_spec,'attempt_history',struct([])));
    try
        rng(getfield_default(case_spec,'case_seed',1),'twister');
        evidence=compute_stage4a6_2_member_evidence(context.observed_views,context.frequency_hz, ...
            context.candidate,context.cfg,context.domain,context.initial_thetas,context.options);
        shard.profile_summary=evidence;
        shard.optimizer_state=struct('optimizer_converged',evidence.optimizer_converged, ...
            'multistart_consistent',evidence.multistart_consistent, ...
            'residual_finite',evidence.residual_finite, ...
            'profile_computed',evidence.profile_computed, ...
            'profile_reliable',evidence.profile_reliable);
        shard.status='completed';shard.exit_status=0;
    catch err
        shard.error_identifier=err.identifier;shard.error_message=err.message;
        if isempty(shard.error_identifier), shard.error_identifier='stage4a6_2:UnhandledCaseFailure'; end
        if isempty(shard.error_message), shard.error_message='Unhandled case failure; inspect MATLAB process log.'; end
    end
    shard.finished_at=datestr(now,30);shard.runtime_s=toc(started);
end
function v=getfield_default(s,f,d),if isstruct(s)&&isfield(s,f),v=s.(f);else,v=d;end,end
