function raw = score_stage4a5_observation(observed_views, cache, subband_index_sets, options)
%SCORE_STAGE4A5_OBSERVATION Build shared M0--M3 evidence for one observation.
%   Only observed CFR, a truth-free candidate cache and deterministic
%   resampling options are accepted.  No decision threshold is applied here.
    if nargin<4||isempty(options),options=struct();end
    residual=compute_subband_residuals(observed_views,cache,subband_index_sets);
    topk=compute_topk_template_evidence(residual.template_full_distance, ...
        residual.template_subband_distance,cache,[3,5,10]);
    stability=compute_frequency_block_stability(observed_views,cache,topk,options, ...
        get_option(options,'stability_seed',1));
    bt=topk.best_template_index; item=cache.templates(bt);
    baseline_label=item.baseline_P0_equivalence_class; baseline_size=item.baseline_P0_equivalence_class_size;
    raw=struct('best_template_id',item.template_id,'best_topology_id',item.topology_id, ...
        'best_topology_index',item.topology_index,'best_equivalence_class',topk.best_class, ...
        'best_equivalence_members',topk.best_class_members, ...
        'baseline_P0_equivalence_class',baseline_label,'baseline_P0_equivalence_class_size',baseline_size, ...
        'prior_conditioned_equivalence_class',topk.best_class, ...
        'prior_conditioned_equivalence_class_size',numel(strsplit(topk.best_class_members,',')), ...
        'best_parameter_values',item.theta,'best_distance',topk.best_distance_value, ...
        'second_competing_class',class_label(topk.class_labels,topk.second_class_index), ...
        'second_distance',topk.second_distance_value,'margin',topk.margin, ...
        'rho',topk.best_distance_value/(topk.second_distance_value+1e-12), ...
        'current_class_size',numel(strsplit(topk.best_class_members,',')), ...
        'class_scores',topk.class_scores,'class_labels',{topk.class_labels}, ...
        'topology_scores',topk.best_distance,'topology_labels',{topk.topology_labels}, ...
        'topology_best_template',topk.best_template,'class_members',{topk.class_members}, ...
        'best_subband_distance',topk.best_subband_distance(topk.best_topology_index,:), ...
        'subband_counts',residual.subband_counts, ...
        'best_amplitude_distance',residual.template_amplitude_distance(bt), ...
        'best_phase_distance',residual.template_phase_distance(bt), ...
        'template_full_distance',residual.template_full_distance, ...
        'template_subband_distance',residual.template_subband_distance, ...
        'topk_evidence',topk,'stability',stability, ...
        'candidate_count_before_prior',get_option(options,'candidate_count_before_prior',cache.candidate_count), ...
        'candidate_count_after_prior',cache.candidate_count,'parameter_template_count',cache.parameter_template_count, ...
        'composite_template_count',cache.composite_template_count,'distance_evaluations',residual.template_count, ...
        'configuration_hash',cache.configuration_hash,'cache_frequency_grid_id',cache.frequency_grid_id, ...
        'matching_time_s',NaN,'best_neighborhood_score',topk.best_neighborhood_scores, ...
        'second_neighborhood_score',topk.second_neighborhood_scores, ...
        'neighborhood_margin',topk.neighborhood_margins, ...
        'baseline_class_scores',baseline_class_scores(cache,residual.template_full_distance), ...
        'baseline_class_labels',{baseline_class_labels(cache)});
end
function s=class_label(labels,index),if isempty(labels)||isnan(index)||index<1,s='';else,s=labels{index};end,end
function labels=baseline_class_labels(cache),labels=stable_unique({cache.templates.baseline_P0_equivalence_class});labels=labels(~cellfun(@isempty,labels));end
function scores=baseline_class_scores(cache,d)
    labels=baseline_class_labels(cache);ids={cache.templates.baseline_P0_equivalence_class};scores=Inf(1,numel(labels));
    for k=1:numel(labels),ix=find(strcmp(ids,labels{k}));if ~isempty(ix),scores(k)=min(d(ix));end,end
end
function x=get_option(s,n,d),if isfield(s,n)&&~isempty(s.(n)),x=s.(n);else,x=d;end,end
function y=stable_unique(x),y={};for k=1:numel(x),if ~any(strcmp(y,x{k})),y{end+1}=x{k};end,end,end
