function raw = score_stage4a5_1_observation(observed_views,cache,subband_index_sets,masks,options)
%SCORE_STAGE4A5_1_OBSERVATION A5 evidence with truth-independent masks.
    if nargin<5,options=struct();end
    residual=compute_subband_residuals(observed_views,cache,subband_index_sets);
    topk=compute_topk_template_evidence(residual.template_full_distance,residual.template_subband_distance,cache,[3,5,10]);
    stability=compute_frequency_block_stability_frozen(observed_views,cache,topk,masks);
    bt=topk.best_template_index;item=cache.templates(bt);
    raw=struct('best_template_id',item.template_id,'best_topology_id',item.topology_id,'best_topology_index',item.topology_index, ...
        'best_equivalence_class',topk.best_class,'best_equivalence_members',topk.best_class_members, ...
        'baseline_P0_equivalence_class',item.baseline_P0_equivalence_class,'baseline_P0_equivalence_class_size',item.baseline_P0_equivalence_class_size, ...
        'prior_conditioned_equivalence_class',topk.best_class,'prior_conditioned_equivalence_class_size',numel(strsplit(topk.best_class_members,',')), ...
        'best_parameter_values',item.theta,'best_distance',topk.best_distance_value,'second_competing_class',class_label(topk.class_labels,topk.second_class_index), ...
        'second_distance',topk.second_distance_value,'margin',topk.margin,'rho',topk.best_distance_value/(topk.second_distance_value+1e-12), ...
        'current_class_size',numel(strsplit(topk.best_class_members,',')),'class_scores',topk.class_scores,'class_labels',{topk.class_labels}, ...
        'topology_scores',topk.best_distance,'topology_labels',{topk.topology_labels},'topology_best_template',topk.best_template,'class_members',{topk.class_members}, ...
        'best_subband_distance',topk.best_subband_distance(topk.best_topology_index,:),'subband_counts',residual.subband_counts, ...
        'best_amplitude_distance',residual.template_amplitude_distance(bt),'best_phase_distance',residual.template_phase_distance(bt), ...
        'template_full_distance',residual.template_full_distance,'template_subband_distance',residual.template_subband_distance, ...
        'topk_evidence',topk,'stability',stability,'candidate_count_before_prior',getopt(options,'candidate_count_before_prior',cache.candidate_count), ...
        'candidate_count_after_prior',cache.candidate_count,'parameter_template_count',cache.parameter_template_count,'composite_template_count',cache.composite_template_count, ...
        'distance_evaluations',residual.template_count,'configuration_hash',cache.experiment_scientific_hash,'cache_frequency_grid_id',cache.frequency_grid_id, ...
        'matching_time_s',NaN,'best_neighborhood_score',topk.best_neighborhood_scores,'second_neighborhood_score',topk.second_neighborhood_scores, ...
        'neighborhood_margin',topk.neighborhood_margins,'baseline_class_scores',baseline_scores(cache,residual.template_full_distance), ...
        'baseline_class_labels',{baseline_labels(cache)});
end
function s=class_label(x,k),if isempty(x)||isnan(k)||k<1,s='';else,s=x{k};end,end
function x=getopt(s,n,d),if isfield(s,n)&&~isempty(s.(n)),x=s.(n);else,x=d;end,end
function y=stable_unique(x),y={};for k=1:numel(x),if ~any(strcmp(y,x{k})),y{end+1}=x{k};end,end,end
function x=baseline_labels(c),x=stable_unique({c.templates.baseline_P0_equivalence_class});x=x(~cellfun(@isempty,x));end
function s=baseline_scores(c,d),x=baseline_labels(c);ids={c.templates.baseline_P0_equivalence_class};s=Inf(1,numel(x));for k=1:numel(x),q=find(strcmp(ids,x{k}));if ~isempty(q),s(k)=min(d(q));end,end,end
