function cfg = stage3b_waveform_config(root_dir)
%STAGE3B_WAVEFORM_CONFIG Isolated G.hn-derived waveform reference settings.
%   This is a standard/technical-material-derived *model reference*, not a
%   complete G.hn PHY, a commercial modem configuration, or a calibrated
%   PLC front end.  Frequencies are Hz and impedances are ohm.

    if nargin < 1 || isempty(root_dir)
        root_dir = fileparts(fileparts(mfilename('fullpath')));
    end
    base = default_config(root_dir); % Read-only reuse of the stable network model.
    cfg = struct();
    cfg.root_dir = root_dir;
    cfg.name = 'Ghn_100MHz_powerline_SISO_standard_derived_reference';
    cfg.stage = 'Stage 3B before waveform-level baseline implementation preparation';
    cfg.scope = ['abstract training waveform + sampled network CFR + receiver-domain ' ...
        'equivalent impairments; not hardware, field validation, or resource optimization'];
    cfg.base_network_config = base;
    cfg.spatial_mode = 'SISO';

    % [A] ITU-T G.9960/G.9964 material as recorded in the transceiver
    % baseline freeze report.  The 2--30 MHz selection is a project study
    % window, not a complete power-line band plan or an active-carrier map.
    cfg.nfft = 4096;
    cfg.fs_hz = 100e6;
    cfg.delta_f_hz = cfg.fs_hz / cfg.nfft;
    cfg.research_band_hz = [2e6, 30e6];
    positive_frequency_hz = (0:cfg.nfft-1) * cfg.delta_f_hz;
    positive_bins = find(positive_frequency_hz >= cfg.research_band_hz(1) & ...
        positive_frequency_hz <= cfg.research_band_hz(2));
    mirror_bins = cfg.nfft - positive_bins + 2;
    cfg.carrier = struct('positive_bins', positive_bins(:).', ...
        'mirror_bins', mirror_bins(:).', ...
        'positive_frequency_hz', positive_frequency_hz(positive_bins), ...
        'research_mask_positive', ismember(1:cfg.nfft, positive_bins), ...
        'research_mask_full', false(1,cfg.nfft), ...
        'training_mask_positive', ismember(1:cfg.nfft, positive_bins), ...
        'data_mask_positive', ismember(1:cfg.nfft, positive_bins), ...
        'active_carrier_status', 'project study mask; actual active carrier/notch pending');
    cfg.carrier.research_mask_full([positive_bins mirror_bins]) = true;

    % Hermitian construction is an explicit discrete-time modelling choice:
    % it makes the abstract waveform real-valued. It is not a claim about a
    % fully verified G.hn mapping, passband converter, or AFE implementation.
    cfg.mapping = struct('kind', 'real_valued_hermitian_discrete_time_assumption', ...
        'status', 'project temporary assumption', ...
        'description', ['positive-frequency training bins are conjugate mirrored; ' ...
            'DC/Nyquist remain zero']);
    cfg.frame = struct('training_symbol_positions', 1, ...
        'data_symbol_positions', 2, 'training_symbol_count', 1, ...
        'data_symbol_count', 1, 'training_pattern_status', ...
        'abstract known QPSK training; not claimed as a universal G.hn preamble');

    % [A] beta=N/8 and the documented G.hn candidate GI rule.  The actual
    % profile/frame selection remains open, so this is deliberately not the
    % historical Stage-3A CP=256 setting.
    cfg.gi = struct('beta_samples', 512, 'ngi_header_default_samples', 1024, ...
        'ncp_samples', 1536, 'rule', 'NCP = NGI + beta', ...
        'evidence', 'standard/official-material-derived candidate; payload profile pending verification', ...
        'window_kind', 'rectangular_assumption', 'window_enabled', false, ...
        'window_note', 'optional raised-cosine diagnostic is not a verified G.hn WOLA implementation');

    % These are compliance references only.  They are never converted to an
    % actual injection voltage, coupling loss, receiver noise figure, or line
    % reference plane in this model.
    cfg.psd_interface = struct('enabled', false, 'constraint_only', true, ...
        'reference_psd_limit_dbm_per_hz', -55, 'reference_total_limit_dbm', 20, ...
        'reference_measurement_termination_ohm', 100, ...
        'status', 'compliance reference only; not project hardware values');
    cfg.frontend = struct('C_tx_positive', [], 'C_rx_positive', [], ...
        'H_frontend_positive', [], 'Zs_ohm_reference', 50, ...
        'Zr_ohm_reference', 50, 'status', ...
        'unit transfer and 50-ohm mathematical-port placeholders; requires measurement');

    cfg.impairments = struct('integer_timing_offset_samples', 0, ...
        'fractional_timing_offset_samples', 0, 'cfo_hz', 0, 'sco_ppm', 0, ...
        'phase_offset_rad', 0);
    cfg.noise = struct('kind', 'none', 'snr_db', Inf, 'color_alpha', 0.85, ...
        'impulse_probability', 0.01, 'impulse_to_background_ratio', 20, ...
        'status', 'receiver-waveform equivalent noise; not calibrated PLC receiver noise');
    cfg.cp_audit_threshold_db = -80;
    cfg.topology = struct('candidate_indices', [2 3 4 5], 'tie_tolerance', 1e-10);
    cfg.output = struct('data_dir', fullfile(root_dir,'results','data'), ...
        'figure_dir', fullfile(root_dir,'results','figures'), ...
        'log_dir', fullfile(root_dir,'results','logs'));
end
