function hash=stage4a7_2_source_tree_hash(root)
%STAGE4A7_2_SOURCE_TREE_HASH Hash scientific Stage 4A.7.2 dependencies.
rel={'config/default_config.m','config/stage4a1_config.m','config/stage4a7_1_candidate_confirmation_config.m','config/stage4a7_2_candidate_closure_config.m', ...
    'src/generate_radial_topology_candidates.m','src/generate_engineering_topology_candidates.m','src/normalize_engineering_candidate_spec.m','src/generate_topk_topology_candidates.m','src/canonicalize_asset_graph.m','src/adapt_engineering_candidate_to_forward_model.m','src/check_forward_model_compatibility.m', ...
    'src/topology_parameter_grid.m','src/topology_apply_parameters.m','src/plc_measurement_bundle.m','src/plc_multiview_response.m','src/plc_full_network_response.m','src/cascade_network_stable.m','src/branch_input_impedance.m','src/cable_rlgc.m', ...
    'src/score_candidate_nonconformity_family.m','src/calibrate_candidate_nonconformity_family.m','src/apply_candidate_nonconformity_set.m','src/apply_candidate_nonconformity_set_indistinguishable.m','src/build_candidate_indistinguishability_graph.m','src/build_candidate_coverage_audit.m','src/build_stage4a7_2_nonunique_clusters.m','src/build_stage4a7_2_near_symmetry.m','src/stage4a7_2_wilson_interval.m','src/stage4a4_scientific_config_hash.m', ...
    'experiments/exp_stage4a7_2_candidate_closure.m'};
payload=repmat(struct('relative_path','','content',''),1,numel(rel));
for k=1:numel(rel),p=fullfile(root,rel{k});if ~exist(p,'file'),error('stage4a7_2:MissingHashDependency','Missing %s.',rel{k});end;payload(k)=struct('relative_path',rel{k},'content',fileread(p));end
hash=stage4a4_scientific_config_hash(payload);
end
