function cfg = stage3b_pre_config(root_dir)
%STAGE3B_PRE_CONFIG Isolated standard-derived Level-A diagnostic settings.
%   This is not a modem configuration or a Stage-3B optimization setup.
    if nargin < 1 || isempty(root_dir), root_dir=fileparts(fileparts(mfilename('fullpath'))); end
    cfg=struct('root_dir',root_dir,'stage','Stage 3A.2 closeout + Stage 3B-pre', ...
        'analysis_kind','analytic_extrapolation_diagnostic', ...
        'feature','complex','weights',[0.5,0.5],'tie_tolerance',1e-10, ...
        'candidate_indices',[2,3,4,5],'snr_db',[Inf,20], ...
        'trials_per_truth',20,'random_seed',20260902, ...
        'theta_cases',{{'nominal','length_plus_2pct','load_minus_10pct'}}, ...
        'total_injected_energy',1,'target_observation_time_s',3.2e-3, ...
        'levels',{{'Level-A0_matched_points','Level-A1_native_points'}}, ...
        'noise_definition',['Receiver-domain additive complex CFR-sample noise; ' ...
        'SNR=mean(abs(H_true).^2)/mean(abs(N).^2), evaluated after the line model.'], ...
        'results_data',fullfile(root_dir,'results','data'), ...
        'results_figures',fullfile(root_dir,'results','figures'), ...
        'results_logs',fullfile(root_dir,'results','logs'));
end
