function model=stage7a5_calibrate_split(a_delta,f_holdout,bank,cfg, ...
        candidate_indices,views,sigma,kind,budget)
%STAGE7A5_CALIBRATE_SPLIT Calibrate set residual and predictive fit gate.
%   A and F are independent in-library splits. OOD/test observations are not
%   inputs to this calibration function.
    a_delta=a_delta(isfinite(a_delta));f_holdout=f_holdout(isfinite(f_holdout));
    assert(numel(a_delta)>=2&&numel(f_holdout)>=2,'stage7a5:TooFewSplitCalibration');
    qa=ceil((numel(a_delta)+1)*(1-cfg.alpha));
    a_delta=sort(a_delta);
    if qa>numel(a_delta),set_threshold=Inf;else,set_threshold=a_delta(qa);end
    qf=ceil((numel(f_holdout)+1)*(1-cfg.alpha));
    f_holdout=sort(f_holdout);
    if qf>numel(f_holdout),fit_threshold=Inf;else,fit_threshold=f_holdout(qf);end
    ids=bank.candidate_ids(candidate_indices);
    model=struct('kind',kind,'budget',budget,'candidate_indices',candidate_indices, ...
        'candidate_ids',{ids},'candidate_signatures',{bank.candidate_signatures(candidate_indices)}, ...
        'views',views,'sigma',sigma,'class_threshold',[], ...
        'set_threshold',set_threshold,'fit_threshold',fit_threshold, ...
        'margin_threshold',cfg.margin_threshold,'alpha',cfg.alpha, ...
        'bank_identity',bank.identity,'search_identity',bank.search_identity, ...
        'calibration_identity',stage4a4_scientific_config_hash(struct( ...
            'a_delta',a_delta,'f_holdout',f_holdout,'ids',{ids}, ...
            'views',views,'sigma',sigma,'kind',kind,'budget',budget)));
end
