function out=stage7a5_score_observation(observed,pool,bank,base,cfg, ...
        base_indices,views,sigma,flow,budget,model)
%STAGE7A5_SCORE_OBSERVATION Truth-free scorer for A/B/C.
%   flow='A': all-frequency legacy profile; 'B': fixed-library train profile
%   with holdout gate; 'C': bounded graph expansion followed by the same gate.
    if nargin<11,model=[];end
    if ~strcmp(bank.search_identity,expected_search_identity(cfg))
        error('stage7a5:BankSearchIdentity', ...
            'Template bank was built for a different search/configuration domain.');
    end
    if ~isempty(model)
        if ~strcmp(model.bank_identity,bank.identity)|| ...
                ~strcmp(model.search_identity,bank.search_identity)
            error('stage7a5:CalibrationIdentityMismatch', ...
                'Calibration model does not match this template bank/search domain.');
        end
        if ~all(ismember(views,model.views))
            error('stage7a5:ViewIdentityMismatch','Calibration view differs from requested view.');
        end
    end
    switch flow
        case 'A'
            p=stage7a5_profile(observed,pool,bank,base,cfg,base_indices, ...
                views,sigma,1:numel(cfg.frequency_hz),true);
            active=base_indices;truncated=false;generated={};
            best_local=find(p.distances==min(p.distances),1);
            fit=p.distances(best_local);holdout=NaN;
        case 'B'
            p=stage7a5_profile(observed,pool,bank,base,cfg,base_indices, ...
                views,sigma,cfg.frequency_train_indices,true);
            active=base_indices;truncated=false;generated={};
            [~,best_local]=min(p.distances);best=active(best_local);
            h=stage7a5_holdout_stat(observed,pool(best).network,p.params(best_local,:), ...
                base,cfg,views,sigma);fit=h.statistic;holdout=h.statistic;
        case 'C'
            p=stage7a5_expand_candidates(observed,pool,bank,base,cfg, ...
                base_indices,views,sigma,cfg.frequency_train_indices,budget);
            active=p.active_indices;truncated=p.search_truncated;
            generated=p.generated_ids;[~,best_local]=min(p.distances);
            best=active(best_local);
            h=stage7a5_holdout_stat(observed,pool(best).network,p.params(best_local,:), ...
                base,cfg,views,sigma);fit=h.statistic;holdout=h.statistic;
        otherwise,error('stage7a5:UnknownFlow','Unknown flow %s.',flow);
    end
    out=struct('candidate_indices',active,'candidate_ids',{bank.candidate_ids(active)}, ...
        'distances',p.distances,'params',p.params,'grid_distances',p.grid_distances, ...
        'optimizer_evaluations',sum(p.evaluations),'fit_statistic',fit, ...
        'holdout_statistic',holdout,'search_truncated',truncated, ...
        'generated_ids',{generated},'profile_candidate_count',numel(active), ...
        'views',views, ...
        'forward_model_calls_search',0,'forward_model_calls_holdout', ...
        double(~strcmp(flow,'A')));
end

function identity=expected_search_identity(cfg)
    identity=stage4a4_scientific_config_hash(struct( ...
        'main_bounds',cfg.main_scale_bounds,'load_bounds',cfg.load_scale_bounds, ...
        'main_grid',cfg.main_scale_grid,'load_grid',cfg.load_scale_grid, ...
        'frequency_hz',cfg.frequency_hz,'state',cfg.state_50));
end
