function out=stage7a8_score_observation(observed,pool,bank,base,cfg, ...
        base_indices,views,sigma,model)
%STAGE7A8_SCORE_OBSERVATION Full C37 scoring with frequency-sliced forwards.
%   No truth identity or true parameters enter this inference interface.
    budget=numel(pool);
    assert(budget==37&&isequal({pool.topology_id},bank.candidate_ids), ...
        'stage7a8:CandidateIdentity');
    assert(all(ismember(base_indices,1:budget)));
    if ~isempty(model)
        expected=stage7a7_condition_identity(cfg,bank,views,sigma, ...
            sprintf('C%d',budget),budget);
        if ~strcmp(model.kind,'C')||model.budget~=budget|| ...
                ~strcmp(model.bank_identity,bank.identity)|| ...
                ~strcmp(model.search_identity,bank.search_identity)|| ...
                ~isequal(model.views,views)||~isequal(model.sigma,sigma)|| ...
                ~isfield(model,'condition_identity')|| ...
                ~strcmp(model.condition_identity,expected)
            error('stage7a8:CalibrationIdentityMismatch', ...
                'Pool, view, condition, mask, sigma or budget mismatch.');
        end
    end
    p=stage7a8_profile(observed,pool,bank,base,cfg,1:budget,views,sigma);
    [~,best]=min(p.distances);
    h=stage7a8_holdout_stat(observed,pool(best).network, ...
        p.params(best,:),base,cfg,views,sigma);
    out=struct('candidate_indices',1:budget, ...
        'candidate_ids',{p.candidate_ids},'distances',p.distances, ...
        'params',p.params,'grid_distances',p.grid_distances, ...
        'optimizer_evaluations',sum(p.evaluations), ...
        'profile_evaluations',budget,'fit_statistic',h.statistic, ...
        'holdout_statistic',h.statistic,'search_truncated',false, ...
        'pool_exhausted',true,'budget_blocked_count',0, ...
        'unvisited_count',0,'frontier_limited',false, ...
        'generated_ids',{{}},'completion_ids',{{}}, ...
        'profile_candidate_count',budget,'views',views, ...
        'forward_model_calls_search',sum(p.evaluations), ...
        'forward_model_calls_holdout',1);
end
