function model=stage4a7_2_r1_calibrate_profile_method(distances,truth_index,ids,method_id,alpha,options)
%STAGE4A7_2_R1_CALIBRATE_PROFILE_METHOD Calibrate one profile score family.
    if nargin<6||isempty(options),options=struct();end
    ids=stage4a7_1_cellstr(ids);truth_index=truth_index(:);fam=stage4a7_2_r1_profile_score_families(distances, ...
        getf(options,'scales',[]),getf(options,'resolution',eps));scores=fam.(method_id);
    min_n=getf(options,'minimum_per_candidate',1);classes=repmat(struct('candidate_id','','scores',[],'sample_count',0,'minimum_attainable_p',NaN,'status',''),1,numel(ids));
    for j=1:numel(ids)
        z=scores(truth_index==j,j);z=z(isfinite(z));classes(j).candidate_id=ids{j};classes(j).scores=sort(z(:).');classes(j).sample_count=numel(z);classes(j).minimum_attainable_p=1/(numel(z)+1);classes(j).status=ternary(numel(z)>=min_n,'calibrated','insufficient_calibration');
    end
    model=struct('method_id',method_id,'candidate_ids',{ids},'classes',classes,'alpha',alpha, ...
        'minimum_per_candidate',min_n,'status',ternary(all([classes.sample_count]>=min_n),'calibrated','insufficient_calibration'), ...
        'scales',fam.scales,'resolution',fam.resolution,'compatibility_hash',getf(options,'compatibility_hash',''), ...
        'calibration_hash',stage4a4_scientific_config_hash(struct('method',method_id,'ids',{ids}, ...
        'scores',{classes.scores},'alpha',alpha,'scales',fam.scales,'resolution',fam.resolution)), ...
        'definition_version','stage4a7_2_r1_profile_calibration_v1');
end
function x=getf(s,n,d),if isstruct(s)&&isfield(s,n)&&~isempty(s.(n)),x=s.(n);else,x=d;end,end
function x=ternary(tf,a,b),if tf,x=a;else,x=b;end,end
