function key=stage7a7_condition_identity(cfg,bank,views,sigma,flow,budget)
%STAGE7A7_CONDITION_IDENTITY Bind calibration to noise, mask and library.
    payload=struct('version',cfg.version,'condition',cfg.condition, ...
        'zin_error_rms_ohm',cfg.zin_error_rms_ohm, ...
        'train_indices',cfg.frequency_train_indices, ...
        'holdout_indices',cfg.frequency_holdout_indices, ...
        'snr_db',cfg.snr_db,'bank_identity',bank.identity, ...
        'search_identity',bank.search_identity,'views',views, ...
        'sigma',sigma,'flow',flow,'budget',budget);
    key=stage4a4_scientific_config_hash(payload);
end
