function hash=stage4a7_2_r1_source_tree_hash(root)
%STAGE4A7_2_R1_SOURCE_TREE_HASH Hash code that changes scientific output.
%   Result directories, logs, timestamps, worker settings and absolute
%   paths are intentionally excluded. Missing dependencies are errors.
    rel={
        'config/default_config.m','config/stage4a1_config.m', ...
        'config/stage4a7_2_candidate_closure_config.m','config/stage4a7_2_r1_data_driven_config.m', ...
        'src/generate_engineering_topology_candidates.m','src/generate_topk_topology_candidates.m', ...
        'src/generate_radial_topology_candidates.m','src/stage4a7_1_adapt_legacy_candidates.m', ...
        'src/normalize_engineering_candidate_spec.m','src/canonicalize_asset_graph.m', ...
        'src/adapt_engineering_candidate_to_forward_model.m','src/check_forward_model_compatibility.m', ...
        'src/topology_parameter_grid.m','src/topology_apply_parameters.m', ...
        'src/plc_measurement_bundle.m','src/plc_multiview_response.m','src/cascade_network_stable.m', ...
        'src/cable_rlgc.m','src/branch_input_impedance.m','src/topology_feature_distance.m', ...
        'src/build_candidate_coverage_audit.m','src/score_candidate_nonconformity_family.m', ...
        'src/calibrate_candidate_nonconformity_family.m','src/apply_candidate_nonconformity_set.m', ...
        'src/stage4a7_2_wilson_interval.m','src/stage4a4_scientific_config_hash.m', ...
        'src/read_stage4a7_2_r1_public_subnetwork.m','src/build_stage4a7_2_r1_uncertain_engineering_prior.m', ...
        'src/stage4a7_2_r1_build_profile_template_cache.m','src/stage4a7_2_r1_profile_distance.m', ...
        'src/stage4a7_2_r1_profile_score_families.m','src/stage4a7_2_r1_calibrate_profile_method.m', ...
        'src/stage4a7_2_r1_apply_profile_candidate_set.m','src/stage4a7_2_r1_method_selection.m', ...
        'src/stage4a7_2_r1_build_coverage_audit.m', ...
        'src/stage4a7_2_r1_nonunique_metrics.m','src/stage4a7_2_r1_topk_scaling_audit.m', ...
        'experiments/exp_stage4a7_2_r1_data_driven_closure.m'};
    payload=repmat(struct('relative_path','','content',''),1,numel(rel));
    for k=1:numel(rel)
        p=fullfile(root,rel{k});if ~exist(p,'file'),error('stage4a7_2_r1:MissingHashDependency','Missing %s.',rel{k});end
        payload(k)=struct('relative_path',rel{k},'content',fileread(p));
    end
    hash=stage4a4_scientific_config_hash(payload);
end
