function hash = stage4a6_3_source_tree_hash(root)
%STAGE4A6_3_SOURCE_TREE_HASH Hash implementation dependencies by relative path.
    rel = {'config/stage4a6_3_parameter_domain_config.m', ...
        'src/generate_stage4a6_3_trial_bank.m','src/audit_stage4a6_3_trial_bank.m', ...
        'src/stage4a6_3_wilson_interval.m','src/evaluate_stage4a6_3_metrics.m', ...
        'src/run_stage4a6_2_batch.m','src/run_stage4a6_2_case.m', ...
        'src/compute_stage4a6_2_parameter_profile.m', ...
        'src/compute_stage4a6_2_member_evidence.m', ...
        'src/apply_stage4a6_2_parameter_decision.m', ...
        'src/optimize_stage4a6_1_parameters.m', ...
        'src/topology_active_parameter_mask.m','src/topology_apply_parameters.m', ...
        'src/plc_measurement_bundle.m','src/plc_multiview_response.m', ...
        'src/generate_radial_topology_candidates.m','src/topology_parameter_grid.m', ...
        'experiments/exp_stage4a6_3_parameter_domain_validation.m', ...
        'run_stage4a6_3_parameter_domain_validation.m'};
    payload = repmat(struct('relative_path','','content',''),numel(rel),1);
    for k=1:numel(rel)
        payload(k).relative_path=rel{k}; p=fullfile(root,rel{k});
        if exist(p,'file'), payload(k).content=fileread(p); else, payload(k).content='<missing-at-hash-time>'; end
    end
    hash = stage4a4_scientific_config_hash(payload);
end
