function out=stage6b_evaluate_observation(observation,model,truth_network)
%STAGE6B_EVALUATE_OBSERVATION Apply existing profile and decision functions.
    t=tic;profile=stage4a7_2_r1_profile_distance({observation},model.cache,struct('feature','complex_raw'));
    accepted=stage4a7_2_r1_apply_profile_candidate_set(profile.profile_distances,model.topology_model,'absolute');
    margin=compute_candidate_margin(profile.profile_distances,model.candidate_ids);
    confidence=compute_candidate_confidence(profile.profile_distances,model.evidence_model.beta,model.candidate_ids);
    relative=min(profile.profile_distances)/max(sqrt(mean(abs(observation).^2)),eps);
    domain_accepted=relative<=model.domain_threshold;
    best_in_set=any(strcmp(accepted.accepted_candidate_set,margin.best_candidate{1}));
    frozen=struct('candidate_set_size',accepted.set_size,'domain_accepted',domain_accepted, ...
        'best_candidate_in_set',best_in_set);
    decision=classify_stage5b1_decision_state(frozen,struct('margin',margin.margin), ...
        struct('top1_confidence',confidence.top1_confidence, ...
        'normalized_entropy',confidence.normalized_entropy),model.evidence_model);
    truth_signature=stage6b_network_signature(truth_network);
    signatures=arrayfun(@(x)stage6b_network_signature(x.network),model.candidates,'UniformOutput',false);
    truth_index=find(strcmp(signatures,truth_signature),1);truth_included=~isempty(truth_index);
    best_is_truth=strcmp(signatures{margin.best_index},truth_signature);
    true_in_set=truth_included&&any(strcmp(accepted.accepted_candidate_set,model.candidate_ids{truth_index}));
    false_unique=strcmp(decision.enhanced_decision_state,'UNIQUE_CONFIDENT')&&~best_is_truth;
    out=struct('candidate_count',numel(model.candidates),'distance',margin.d1, ...
        'second_distance',margin.d2,'margin',margin.margin, ...
        'top1_confidence',confidence.top1_confidence,'entropy',confidence.entropy, ...
        'normalized_entropy',confidence.normalized_entropy,'candidate_set_size',accepted.set_size, ...
        'candidate_set',strjoin(cellstr(accepted.accepted_candidate_set),','), ...
        'best_candidate',margin.best_candidate{1},'truth_topology_included',truth_included, ...
        'best_is_truth',best_is_truth,'true_topology_in_candidate_set',true_in_set, ...
        'domain_relative_distance',relative,'domain_threshold',model.domain_threshold, ...
        'domain_accepted',domain_accepted,'decision_state',decision.enhanced_decision_state, ...
        'decision_reason',decision.decision_reason,'false_unique',false_unique, ...
        'scoring_time_s',toc(t),'distance_vector',profile.profile_distances, ...
        'normalized_score_semantics','not_a_Bayesian_posterior');
end
