function band = stage3b_pre_band_selector(name, level)
%STAGE3B_PRE_BAND_SELECTOR Standard-derived sampling grids, not hardware PHYs.
    key=lower(char(name));
    switch key
        case {'bb','bb_ghn_standard_derived_reference'}
            band=struct('name','BB_Ghn_standard_derived_reference', ...
                'source','ITU-T G.9960/G.9964 standard-derived reference', ...
                'nfft',4096,'fs_hz',100e6,'subcarrier_spacing_hz',24.4140625e3, ...
                'observation_window_hz',[2e6,30e6],'spatial_mode','SISO', ...
                'model_status','model_limited_BB_reference_not_hardware_reproduction', ...
                'rlgc_status','existing_project_model_window_2_to_30_MHz');
            k=ceil(band.observation_window_hz(1)/band.subcarrier_spacing_hz): ...
                floor(band.observation_window_hz(2)/band.subcarrier_spacing_hz);
            band.native_frequency_hz=k*band.subcarrier_spacing_hz;
        case {'nb','nb_g3plc_cenelec_a_standard_derived_reference'}
            band=struct('name','NB_G3PLC_CENELEC_A_standard_derived_reference', ...
                'source','ITU-T G.9903 CENELEC-A standard-derived reference', ...
                'nfft',256,'fs_hz',0.4e6,'subcarrier_spacing_hz',1.5625e3, ...
                'observation_window_hz',[35.9375e3,90.625e3],'spatial_mode','SISO', ...
                'nominal_usable_subcarriers',36,'ncp',30,'overlap_samples',8, ...
                'model_status','analytic_extrapolation_diagnostic_not_hardware_reproduction', ...
                'rlgc_status','frequency_extrapolation_below_existing_2_to_30_MHz_evidence');
            band.native_frequency_hz=(23:58)*band.subcarrier_spacing_hz;
        otherwise
            error('stage3b_pre_band_selector:UnknownBand','Unknown band %s.',key);
    end
    if nargin<2 || isempty(level), level='Level-A1_native_points'; end
    if strcmpi(level,'Level-A0_matched_points') && strcmp(key,'bb')
        idx=round(linspace(1,numel(band.native_frequency_hz),36));
        band.frequency_hz=band.native_frequency_hz(unique(idx,'stable'));
    else
        band.frequency_hz=band.native_frequency_hz;
    end
    band.level=char(level); band.active_point_count=numel(band.frequency_hz);
end
