function out=stage7a7_score_observation(observed,pool,bank,base,cfg, ...
        base_indices,views,sigma,budget,model)
%STAGE7A7_SCORE_OBSERVATION Truth-free expanded CFR/Zin scorer.
    if nargin<10,model=[];end
    if ~isempty(model)
        expected=stage7a7_condition_identity(cfg,bank,views,sigma, ...
            sprintf('C%d',budget),budget);
        if ~strcmp(model.kind,'C')||model.budget~=budget|| ...
                ~strcmp(model.bank_identity,bank.identity)|| ...
                ~strcmp(model.search_identity,bank.search_identity)|| ...
                ~isequal(model.views,views)||~isequal(model.sigma,sigma)|| ...
                ~isfield(model,'condition_identity')|| ...
                ~strcmp(model.condition_identity,expected)
            error('stage7a7:CalibrationIdentityMismatch', ...
                'Pool, view, condition, mask, sigma or budget mismatch.');
        end
    end
    p=stage7a7_expand_candidates(observed,pool,bank,base,cfg, ...
        base_indices,views,sigma,budget);
    [~,best_local]=min(p.distances);
    best=p.active_indices(best_local);
    h=stage7a5_holdout_stat(observed,pool(best).network, ...
        p.params(best_local,:),base,cfg,views,sigma);
    out=struct('candidate_indices',p.active_indices, ...
        'candidate_ids',{p.active_ids},'distances',p.distances, ...
        'params',p.params,'grid_distances',p.grid_distances, ...
        'optimizer_evaluations',p.total_optimizer_evaluations, ...
        'profile_evaluations',p.total_profile_evaluations, ...
        'fit_statistic',h.statistic,'holdout_statistic',h.statistic, ...
        'search_truncated',p.search_truncated, ...
        'pool_exhausted',p.pool_exhausted, ...
        'budget_blocked_count',p.budget_blocked_count, ...
        'unvisited_count',p.unvisited_count, ...
        'frontier_limited',p.frontier_limited, ...
        'generated_ids',{p.generated_ids}, ...
        'completion_ids',{p.completion_ids}, ...
        'profile_candidate_count',numel(p.active_indices), ...
        'views',views,'forward_model_calls_search',0, ...
        'forward_model_calls_holdout',1);
end
