function result = stage4a6_3_1_r1_confirm_with_frozen_stage4a5_1( ...
        observed_views, cache, subband_sets, topology_calibration_model, ...
        spec, expected_compatibility_hash, expected_topology_calibration_hash)
%STAGE4A6_3_1_R1_CONFIRM_WITH_FROZEN_STAGE4A5_1 Truth-free topology adapter.
% Truth labels, parameter-domain labels and scenario categories are not
% accepted by this interface.  Calibration identity is checked strictly.
    if nargin < 7 || isempty(expected_topology_calibration_hash)
        error('stage4a6_3_1_r1:MissingTopologyCalibrationHash', ...
            'Topology calibration hash is required.');
    end
    if ~strcmp(getfield_default(topology_calibration_model, ...
            'compatibility_hash', ''), expected_compatibility_hash)
        error('stage4a6_3_1_r1:CompatibilityMismatch', ...
            'Topology calibration compatibility hash mismatch.');
    end
    if ~strcmp(getfield_default(topology_calibration_model, ...
            'topology_calibration_hash', ''), expected_topology_calibration_hash)
        error('stage4a6_3_1_r1:TopologyCalibrationMismatch', ...
            'Topology calibration hash is missing or mismatched.');
    end
    if ~strcmp(getfield_default(cache, 'compatibility_hash', ''), ...
            expected_compatibility_hash)
        error('stage4a6_3_1_r1:CacheCompatibilityMismatch', ...
            'Template cache compatibility hash mismatch.');
    end
    result = confirm_stage4a6_3_1_topology(observed_views, cache, ...
        subband_sets, topology_calibration_model, spec, expected_compatibility_hash);
    result.confirmation_method_id = ...
        'Stage4A5_1_M3_frozen_adapter_R1';
    result.compatibility_hash = expected_compatibility_hash;
    result.topology_calibration_hash = expected_topology_calibration_hash;
    result.topology_calibration_status = ...
        getfield_default(topology_calibration_model, ...
        'topology_calibration_status', 'unknown');
end

function v = getfield_default(s, n, d)
    if isstruct(s) && isfield(s, n), v = s.(n); else, v = d; end
end
