function hash = stage4a7_2_r2_source_hash(root_dir)
%STAGE4A7_2_R2_SOURCE_HASH Hash scientific source files, not outputs.
    files={
        'config/default_config.m','config/stage4a7_2_r2_candidate_coverage_config.m', ...
        'config/stage4a7_2_r1_data_driven_config.m','src/generate_engineering_topology_candidates.m', ...
        'src/generate_topk_topology_candidates.m','src/normalize_engineering_candidate_spec.m', ...
        'src/adapt_engineering_candidate_to_forward_model.m','src/check_forward_model_compatibility.m', ...
        'src/topology_parameter_grid.m','src/topology_apply_parameters.m','src/plc_measurement_bundle.m', ...
        'src/plc_multiview_response.m','src/stage4a7_2_r1_build_profile_template_cache.m', ...
        'src/stage4a7_2_r1_profile_distance.m','src/stage4a7_2_r1_profile_score_families.m', ...
        'src/stage4a7_2_r1_calibrate_profile_method.m','src/stage4a7_2_r1_apply_profile_candidate_set.m', ...
        'src/stage4a7_2_r2_exact_topk_audit.m','src/stage4a7_2_r2_method_selection.m', ...
        'src/stage4a7_2_r2_scenario_equivalence.m','src/stage4a7_2_r2_external_manifest.m', ...
        'src/stage4a7_2_r2_sha256_file.m','experiments/exp_stage4a7_2_r2_candidate_coverage_validity.m'};
payload=cell(numel(files),1);for k=1:numel(files),p=fullfile(root_dir,files{k});if exist(p,'file'),payload{k}=sprintf('%s\n%s',files{k},fileread(p));else,payload{k}=[files{k} '\n<MISSING>'];end,end
hash=stage4a4_scientific_config_hash(payload);
end
