function hash = stage4a6_3_1_r_source_tree_hash(root)
%STAGE4A6_3_1_R_SOURCE_TREE_HASH Hash all R-pilot scientific dependencies.
% Runtime paths and result files are intentionally excluded.  The hash is
% path-independent and changes when the R protocol or its frozen upstream
% confirmer dependencies change.
    rel = { ...
        'config/stage4a6_3_1_r_protocol_config.m', ...
        'src/stage4a6_3_1_r_build_compatibility_hash.m', ...
        'src/stage4a6_3_1_r_source_tree_hash.m', ...
        'src/stage4a6_3_1_r_confirm_with_frozen_stage4a5_1.m', ...
        'src/stage4a6_3_1_r_generate_independent_scenarios.m', ...
        'src/stage4a6_3_1_r_materialize_scenario.m', ...
        'src/stage4a6_3_1_r_profile_all_accepted_members.m', ...
        'src/stage4a6_3_1_r_aggregate_class_evidence.m', ...
        'src/stage4a6_3_1_r_evaluate_metrics.m', ...
        'experiments/exp_stage4a6_3_1_r_independent_pilot.m', ...
        'run_stage4a6_3_1_r_independent_pilot.m', ...
        'src/confirm_stage4a6_3_1_topology.m', ...
        'src/run_stage4a6_3_1_member_profiles.m', ...
        'src/aggregate_stage4a6_3_1_member_evidence.m', ...
        'src/score_stage4a5_observation.m', ...
        'src/apply_stage4a5_confirmation.m', ...
        'src/stage4a5_make_subbands.m', ...
        'src/compute_stage4a6_2_member_evidence.m', ...
        'src/compute_stage4a6_2_parameter_profile.m', ...
        'src/apply_stage4a6_2_parameter_decision.m', ...
        'src/calibrate_stage4a6_2_parameter_thresholds.m', ...
        'src/generate_radial_topology_candidates.m', ...
        'src/topology_parameter_grid.m', ...
        'src/topology_active_parameter_mask.m', ...
        'src/topology_apply_parameters.m', ...
        'src/plc_measurement_bundle.m', ...
        'src/plc_multiview_response.m', ...
        'src/build_stage4a5_1_template_cache.m', ...
        'src/build_stage4a3_1_template_cache.m', ...
        'src/stage4a4_scientific_config_hash.m', ...
        'src/stage4a2_config_hash.m'};
    payload = repmat(struct('relative_path','','content',''),numel(rel),1);
    for k = 1:numel(rel)
        payload(k).relative_path = rel{k};
        p = fullfile(root,rel{k});
        if exist(p,'file')
            payload(k).content = fileread(p);
        else
            payload(k).content = '<missing-at-hash-time>';
        end
    end
    hash = stage4a4_scientific_config_hash(payload);
end
