function [hash,canonical] = stage4a6_3_1_compatibility_hash(sc,candidates,theta_grid,source_hash,cache)
%STAGE4A6_3_1_COMPATIBILITY_HASH Scientific identity shared by calibration/pilot.
% Split seeds are deliberately excluded; changing scientific rules changes it.
    cm=repmat(struct('topology_id','','canonical_key',''),numel(candidates),1);
    for k=1:numel(candidates),cm(k).topology_id=candidates(k).topology_id;cm(k).canonical_key=candidates(k).canonical_key;end
    ci=struct('schema',getfield_default(cache,'cache_schema_version',''), ...
        'cache_configuration_hash',getfield_default(cache,'cache_configuration_hash',''), ...
        'forward_model_source_hash',getfield_default(cache,'forward_model_source_hash',''), ...
        'frequency_hz',sc.grids(1).frequency_hz,'candidate_manifest',cm, ...
        'parameter_grid',{theta_grid},'measurement_kind',sc.measurement_kind, ...
        'distance',sc.distance,'termination',sc.termination);
    p=struct('stage',sc.stage_name,'version',sc.version,'grid_id',sc.grid_id, ...
        'frequency_hz',sc.grids(1).frequency_hz,'generator',sc.generator, ...
        'parameter_search',sc.parameter_search,'extended_domain_eta',sc.extended_domain_eta, ...
        'profile',sc.profile,'confirmation',sc.confirmation,'candidate_generation_mode',sc.candidate_generation_mode, ...
        'edge_universe_source',sc.edge_universe_source,'prior_source',sc.prior_source, ...
        'candidate_generator_version',sc.candidate_generator_version,'cache_identity',ci, ...
        'source_tree_hash',source_hash,'logic_version','stage4a6_3_1_compatibility_v1');
    [hash,canonical]=stage4a4_scientific_config_hash(p);
end
function v=getfield_default(s,n,d),if isstruct(s)&&isfield(s,n),v=s.(n);else,v=d;end,end
