function out=stage7a_score_observation(observation,model,search)
%STAGE7A_SCORE_OBSERVATION Apply locally calibrated four-state decision.
%   Inputs are observed CFR, a calibrated model and prespecified search
%   configuration. This scoring API has no truth topology or true theta.
    start=tic;
    profile=stage7a_profile_distance(observation,model.cache,search);
    d=profile.profile_distances;
    accepted=stage4a7_2_r1_apply_profile_candidate_set(d,model.topology_model,'absolute');
    margin=compute_candidate_margin(d,model.candidate_ids);
    confidence=compute_candidate_confidence(d,model.evidence_model.beta,model.candidate_ids);
    relative=min(d)/max(sqrt(mean(abs(observation(:)).^2)),eps);
    domain_accepted=relative<=model.domain_threshold;
    frozen=struct('candidate_set_size',accepted.set_size,'domain_accepted',domain_accepted, ...
        'best_candidate_in_set',any(strcmp(accepted.accepted_candidate_set,margin.best_candidate{1})));
    decision=classify_stage5b1_decision_state(frozen,struct('margin',margin.margin), ...
        struct('top1_confidence',confidence.top1_confidence, ...
        'normalized_entropy',confidence.normalized_entropy),model.evidence_model);
    out=struct('candidate_count',numel(model.candidates),'distance',margin.d1, ...
        'second_distance',margin.d2,'margin',margin.margin, ...
        'top1_confidence',confidence.top1_confidence, ...
        'normalized_entropy',confidence.normalized_entropy, ...
        'candidate_set_size',accepted.set_size, ...
        'candidate_set',strjoin(cellstr(accepted.accepted_candidate_set),','), ...
        'best_candidate',margin.best_candidate{1},'best_index',margin.best_index, ...
        'domain_relative_distance',relative,'domain_threshold',model.domain_threshold, ...
        'domain_accepted',domain_accepted,'decision_state',decision.enhanced_decision_state, ...
        'decision_reason',decision.decision_reason, ...
        'best_main_scale',profile.best_main_scale(margin.best_index), ...
        'best_branch_load_scale',profile.best_branch_load_scale(margin.best_index), ...
        'template_comparisons',profile.template_comparisons, ...
        'scoring_time_s',toc(start),'distance_vector',d, ...
        'normalized_score_semantics','not_a_Bayesian_posterior');
end
