function hash = stage4a5_1_source_tree_hash(root)
%STAGE4A5_1_SOURCE_TREE_HASH Hash model-relevant source contents, path-free.
    rel={ ...
        'config/stage4a5_1_integrity_config.m', ...
        'src/generate_stage4a5_1_trial_bank.m', ...
        'src/remap_out_of_library_topology_ids.m', ...
        'src/build_truth_labels_by_canonical_key.m', ...
        'src/build_frozen_resampling_masks.m', ...
        'src/compute_frequency_block_stability_frozen.m', ...
        'src/validate_candidate_cache_identity.m', ...
        'src/generate_radial_topology_candidates.m', ...
        'src/generate_prior_constrained_candidates.m', ...
        'src/topology_parameter_grid.m', ...
        'src/topology_apply_parameters.m', ...
        'src/plc_full_network_response.m', ...
        'src/plc_multiview_response.m', ...
        'src/topology_feature_distance.m', ...
        'src/build_stage4a3_1_template_cache.m'};
    payload=struct('relative_path',{},'content',{});
    for k=1:numel(rel)
        p=fullfile(root,rel{k});
        if ~exist(p,'file'),error('stage4a5_1:MissingSource','Missing source %s.',rel{k});end
        payload(k)=struct('relative_path',rel{k},'content',fileread(p)); %#ok<AGROW>
    end
    hash=stage4a4_scientific_config_hash(payload);
end
