function model=stage7a3_calibrate_residual_gate(scores,alpha,identity)
%STAGE7A3_CALIBRATE_RESIDUAL_GATE One-sided split-quantile inlier cutoff.
%   The cutoff is calibrated only from a disjoint in-library F split.
    x=double(scores(:));
    assert(~isempty(x)&&all(isfinite(x))&&all(x>=0), ...
        'stage7a3:InvalidGateCalibration','Calibration scores must be finite and nonnegative.');
    assert(alpha>0&&alpha<1,'stage7a3:GateAlpha','alpha must be in (0,1).');
    n=numel(x);rank=ceil((n+1)*(1-alpha));
    if rank>n,threshold=Inf;else,z=sort(x);threshold=z(rank);end
    model=struct('statistic','max_four_band_normalized_complex_residual', ...
        'alpha',alpha,'calibration_count',n,'order_statistic_rank',rank, ...
        'threshold',threshold,'identity',char(identity), ...
        'calibration_hash',stage4a4_scientific_config_hash(struct( ...
            'scores',x,'alpha',alpha,'identity',identity)));
end
