function hash = stage4a7_1_source_tree_hash(root)
%STAGE4A7_1_SOURCE_TREE_HASH Hash Stage-4A.7.1 scientific dependencies.
%   Runtime locations, result files, logs, timestamps and worker settings
%   are excluded.  Missing files are an error rather than a silent omission.
    rel={
        'config/default_config.m', ...
        'config/stage4a1_config.m', ...
        'config/stage4a7_1_candidate_confirmation_config.m', ...
        'experiments/exp_stage4a7_1_candidate_generation_and_confirmation.m', ...
        'run_stage4a7_1_candidate_generation_and_confirmation.m', ...
        'src/generate_radial_topology_candidates.m', ...
        'src/generate_prior_constrained_candidates.m', ...
        'src/validate_radial_topology_candidate.m', ...
        'src/topology_candidates.m', ...
        'src/canonicalize_asset_graph.m', ...
        'src/generate_engineering_topology_candidates.m', ...
        'src/generate_topk_topology_candidates.m', ...
        'src/check_forward_model_compatibility.m', ...
        'src/stage4a7_1_adapt_legacy_candidates.m', ...
        'src/generate_stage4a7_1_scenarios.m', ...
        'src/evaluate_stage4a7_1_pilot_metrics.m', ...
        'src/score_candidate_library_fast.m', ...
        'src/score_candidate_weighted_residual.m', ...
        'src/estimate_cfr_noise_covariance.m', ...
        'src/build_candidate_indistinguishability_graph.m', ...
        'src/calibrate_candidate_set_predictor.m', ...
        'src/apply_candidate_set_predictor.m', ...
        'src/score_candidate_set_metrics.m', ...
        'src/stage4a7_1_multinode_tomography_capability.m', ...
        'src/build_stage4a5_1_template_cache.m', ...
        'src/build_stage4a3_1_template_cache.m', ...
        'src/score_stage4a5_1_observation.m', ...
        'src/compute_subband_residuals.m', ...
        'src/compute_topk_template_evidence.m', ...
        'src/compute_frequency_block_stability_frozen.m', ...
        'src/calibrate_stage4a5_confirmation.m', ...
        'src/stage4a5_method_specs.m', ...
        'src/build_frozen_resampling_masks.m', ...
        'src/generate_stage4a5_trial_bank.m', ...
        'src/generate_stage4a5_1_trial_bank.m', ...
        'src/topology_parameter_grid.m', ...
        'src/topology_apply_parameters.m', ...
        'src/plc_measurement_bundle.m', ...
        'src/match_candidate_library_calibrated.m', ...
        'src/apply_candidate_confirmation.m', ...
        'src/cascade_network_stable.m', ...
        'src/plc_full_network_response.m', ...
        'src/plc_multiview_response.m', ...
        'src/topology_feature_distance.m', ...
        'src/stage4a4_scientific_config_hash.m', ...
        'src/stage4a2_config_hash.m'};
    payload=repmat(struct('relative_path','','content',''),1,numel(rel));
    for k=1:numel(rel)
        p=fullfile(root,rel{k});if ~exist(p,'file'),error('stage4a7_1:MissingHashDependency','Missing %s.',rel{k});end
        payload(k)=struct('relative_path',rel{k},'content',fileread(p));
    end
    hash=stage4a4_scientific_config_hash(payload);
end
