function out = stage4a6_3_1_r1_profile_all_accepted_members( ...
        observed_views, frequency_hz, confirmation, candidates, cfg, domain, ...
        profile_options, parameter_model, expected_compatibility_hash, ...
        expected_parameter_calibration_hash, method_id)
%STAGE4A6_3_1_R1_PROFILE_ALL_ACCEPTED_MEMBERS Strict parameter identity gate.
    if nargin < 11 || isempty(method_id), method_id = 'A6_3_M3_joint_diagnostic'; end
    if ~strcmp(getfield_default(parameter_model, 'compatibility_hash', ''), ...
            expected_compatibility_hash)
        error('stage4a6_3_1_r1:ParameterCompatibilityMismatch', ...
            'Parameter calibration compatibility hash mismatch.');
    end
    if ~strcmp(getfield_default(parameter_model, ...
            'parameter_calibration_hash', ''), expected_parameter_calibration_hash)
        error('stage4a6_3_1_r1:ParameterCalibrationMismatch', ...
            'Parameter calibration hash is missing or mismatched.');
    end
    raw = stage4a6_3_1_r_profile_all_accepted_members(observed_views, ...
        frequency_hz, confirmation, candidates, cfg, domain, ...
        profile_options, parameter_model);
    evidence = getfield_default(raw, 'member_evidence', struct([]));
    out = stage4a6_3_1_r1_aggregate_class_evidence(confirmation, evidence, ...
        parameter_model, method_id, expected_compatibility_hash, ...
        expected_parameter_calibration_hash);
end

function out = getfield_default(s, n, d)
    if isstruct(s) && isfield(s, n), out = s.(n); else, out = d; end
end
