function model=stage7a10_calibrate(a0,truth0,a1,truth1,f,bank,indices,sigma,selector,cfg)
%STAGE7A10_CALIBRATE Disjoint H50 A0, adaptive-set A1 and quality F splits.
%   Matrices are samples-by-candidates; truth labels are local class indices.
    m=numel(indices);assert(m>=2&&size(a0,2)==m&&size(a1,2)==m&&size(f,2)==m);
    first=zeros(1,m);class=zeros(1,m);
    for k=1:m
        x=sort(a0(truth0==k,k));assert(numel(x)>=2);
        first(k)=quant(x,cfg.alpha);
        x=sort(a1(truth1==k,k));assert(numel(x)>=2);
        class(k)=quant(x,cfg.alpha);
    end
    fit=quant(sort(min(f,[],2)),cfg.alpha);
    model=struct('indices',indices,'candidate_ids',{bank.candidate_ids(indices)}, ...
        'bank_identity',bank.identity,'first_threshold',first, ...
        'class_threshold',class,'fit_threshold',fit, ...
        'margin_threshold',cfg.separation_threshold, ...
        'extra_view_threshold',cfg.extra_view_threshold,'sigma',sigma, ...
        'selector',selector,'a0_count',size(a0,1), ...
        'a1_count',size(a1,1),'f_count',size(f,1), ...
        'identity',stage4a4_scientific_config_hash(struct( ...
            'indices',indices,'bank',bank.identity,'first',first, ...
            'class',class,'fit',fit,'selector',selector.separation, ...
            'sigma',sigma,'a0',a0,'a1',a1,'f',f)));
end
function q=quant(sorted,alpha)
    n=numel(sorted);rank=ceil((n+1)*(1-alpha));
    if rank>n,q=Inf;else,q=sorted(rank);end
end
