function hash = stage4a6_2_source_tree_hash(root)
%STAGE4A6_2_SOURCE_TREE_HASH Hash Stage 4A.6.2 source by relative paths.
    rel = { ...
        'config/stage4a6_2_profile_config.m', ...
        'src/stage4a6_2_source_tree_hash.m', ...
        'src/compute_stage4a6_2_parameter_profile.m', ...
        'src/compute_stage4a6_2_member_evidence.m', ...
        'src/calibrate_stage4a6_2_parameter_thresholds.m', ...
        'src/apply_stage4a6_2_parameter_decision.m', ...
        'src/run_stage4a6_2_case.m', ...
        'src/run_stage4a6_2_batch.m', ...
        'src/aggregate_stage4a6_2_shards.m', ...
        'src/validate_stage4a6_2_shard.m', ...
        'src/save_stage4a6_2_shard_atomic.m', ...
        'src/stage4a6_2_case_seed.m', ...
        'src/optimize_stage4a6_1_parameters.m', ...
        'src/topology_active_parameter_mask.m', ...
        'src/compute_stage4a6_1_jacobian.m', ...
        'src/analyze_parameter_identifiability.m', ...
        'src/topology_apply_parameters.m', ...
        'src/plc_measurement_bundle.m', ...
        'src/plc_multiview_response.m', ...
        'src/plc_full_network_response.m', ...
        'src/generate_radial_topology_candidates.m', ...
        'src/topology_candidates.m', ...
        'src/topology_parameter_grid.m', ...
        'experiments/exp_stage4a6_2_profile_stabilization.m', ...
        'run_stage4a6_2_profile_stabilization.m'};
    payload = repmat(struct('relative_path','','content',''), numel(rel), 1);
    for k = 1:numel(rel)
        path = fullfile(root, rel{k});
        if exist(path, 'file')
            payload(k).relative_path = rel{k};
            payload(k).content = fileread(path);
        else
            payload(k).relative_path = rel{k};
            payload(k).content = '<missing-at-hash-time>';
        end
    end
    hash = stage4a4_scientific_config_hash(payload);
end
