function hash = stage4a6_2_1_source_tree_hash(root)
%STAGE4A6_2_1_SOURCE_TREE_HASH Hash closure-stage source by relative path.
    rel={'config/stage4a6_2_profile_config.m','config/stage4a6_2_1_protocol_config.m', ...
        'src/compute_stage4a6_2_parameter_profile.m','src/compute_stage4a6_2_member_evidence.m', ...
        'src/apply_stage4a6_2_parameter_decision.m','src/calibrate_stage4a6_2_parameter_thresholds.m', ...
        'src/run_stage4a6_2_case.m','src/run_stage4a6_2_batch.m','src/save_stage4a6_2_shard_atomic.m', ...
        'src/validate_stage4a6_2_shard.m','src/aggregate_stage4a6_2_shards.m', ...
        'src/stage4a6_2_case_seed.m','src/stage4a6_2_source_tree_hash.m', ...
        'src/stage4a6_2_1_source_tree_hash.m','src/stage4a6_2_flatness_rule.m', ...
        'src/optimize_stage4a6_1_parameters.m','src/topology_active_parameter_mask.m', ...
        'src/topology_apply_parameters.m','src/plc_multiview_response.m','src/plc_measurement_bundle.m', ...
        'experiments/exp_stage4a6_2_1_protocol_closure.m','run_stage4a6_2_1_protocol_closure.m'};
    p=repmat(struct('relative_path','','content',''),numel(rel),1);
    for k=1:numel(rel)
        p(k).relative_path=rel{k};f=fullfile(root,rel{k});
        if exist(f,'file'),p(k).content=fileread(f);else,p(k).content='<missing-at-hash-time>';end
    end
    hash=stage4a4_scientific_config_hash(p);
end
