function network=stage7a7_split_main_edit(parent,edge_index,cfg,branch)
%STAGE7A7_SPLIT_MAIN_EDIT Split one allowed 20 m edge and add a side branch.
%   parent/network lengths are m. Output preserves 80 m main length and
%   shifts downstream branch attachment indices; truth ID is never read.
    network=parent;
    assert(numel(parent.main_lengths)==4&& ...
        ismember(edge_index,cfg.insert_edges),'stage7a7:InsertEdge');
    assert(numel(parent.branches)<cfg.maximum_branches, ...
        'stage7a7:BranchBudget');
    original=parent.main_lengths(edge_index);
    first=original*cfg.insert_fraction;second=original-first;
    assert(first>=cfg.minimum_main_segment_m&& ...
        second>=cfg.minimum_main_segment_m,'stage7a7:MinimumSegment');
    network.main_lengths=[parent.main_lengths(1:edge_index-1), ...
        first,second,parent.main_lengths(edge_index+1:end)];
    t=parent.main_cable_type(edge_index);
    network.main_cable_type=[parent.main_cable_type(1:edge_index-1), ...
        t,t,parent.main_cable_type(edge_index+1:end)];
    for k=1:numel(network.branches)
        if network.branches(k).node>=edge_index
            network.branches(k).node=network.branches(k).node+1;
        end
    end
    branch.node=edge_index;
    network.branches(end+1)=branch;
    assert(abs(sum(network.main_lengths)-cfg.total_main_length_m)<1e-12&& ...
        numel(network.main_lengths)+1<=cfg.maximum_main_nodes&& ...
        numel(network.branches)<=cfg.maximum_branches&& ...
        numel(network.main_lengths)+1+numel(network.branches)<= ...
        cfg.maximum_total_nodes,'stage7a7:GraphConstraint');
    counts=accumarray([network.branches.node].',1, ...
        [numel(network.main_lengths)-1 1]);
    assert(all(counts<=cfg.maximum_branches_per_node), ...
        'stage7a7:BranchNodeBudget');
end
