function hash = stage4a6_3_1_source_tree_hash(root)
%STAGE4A6_3_1_SOURCE_TREE_HASH Hash path-independent pilot dependencies.
    rel={'config/stage4a6_3_1_protocol_config.m', ...
        'src/stage4a6_3_1_compatibility_hash.m','src/generate_stage4a6_3_1_independent_trials.m', ...
        'src/confirm_stage4a6_3_1_topology.m','src/run_stage4a6_3_1_member_profiles.m', ...
        'src/aggregate_stage4a6_3_1_member_evidence.m','src/evaluate_stage4a6_3_1_metrics.m', ...
        'src/score_stage4a5_observation.m','src/apply_stage4a5_confirmation.m', ...
        'src/stage4a5_make_subbands.m','src/compute_stage4a6_2_member_evidence.m', ...
        'src/compute_stage4a6_2_parameter_profile.m','src/apply_stage4a6_2_parameter_decision.m', ...
        'src/generate_radial_topology_candidates.m','src/topology_parameter_grid.m', ...
        'src/topology_active_parameter_mask.m','src/topology_apply_parameters.m', ...
        'src/plc_measurement_bundle.m','src/plc_multiview_response.m', ...
        'src/build_stage4a5_1_template_cache.m','src/build_stage4a3_1_template_cache.m', ...
        'experiments/exp_stage4a6_3_1_protocol_pilot.m','run_stage4a6_3_1_protocol_pilot.m'};
    payload=repmat(struct('relative_path','','content',''),numel(rel),1);
    for k=1:numel(rel)
        payload(k).relative_path=rel{k};p=fullfile(root,rel{k});
        if exist(p,'file'),payload(k).content=fileread(p);else,payload(k).content='<missing-at-hash-time>';end
    end
    hash=stage4a4_scientific_config_hash(payload);
end
