function digest = stage4a5_source_tree_hash(root)
%STAGE4A5_SOURCE_TREE_HASH Hash the Stage 4A.5 source files by relative path.
    names={'config/stage4a5_multiscale_confirmation_config.m', ...
        'experiments/exp_stage4a5_multiscale_confirmation.m', ...
        'run_stage4a5_multiscale_confirmation.m', ...
        'tests/test_stage4a5_multiscale_confirmation.m'};
    extra={'compute_subband_residuals.m','compute_topk_template_evidence.m', ...
        'compute_frequency_block_stability.m','calibrate_stage4a5_confirmation.m', ...
        'apply_stage4a5_confirmation.m','evaluate_stage4a5_metrics.m', ...
        'select_stage4a5_method.m','stage4a5_method_specs.m','score_stage4a5_observation.m', ...
        'generate_stage4a5_trial_bank.m','build_stage4a5_truth_labels.m', ...
        'stage4a5_make_subbands.m'};
    for k=1:numel(extra),names{end+1}=['src/' extra{k}];end
    names=sort(names);text='';for k=1:numel(names),file=fullfile(root,names{k});if ~exist(file,'file'),error('stage4a5:MissingSource','Missing source %s.',names{k});end;text=[text names{k} char(10) fileread(file) char(10)];end %#ok<AGROW>
    md=java.security.MessageDigest.getInstance('SHA-256');md.update(uint8(unicode2native(text,'UTF-8')));raw=typecast(md.digest(),'uint8');digest=lower(reshape(dec2hex(raw,2).',1,[]));
end
