function metrics = stage4a6_3_1_r1_evaluate_metrics(decisions, labels)
%STAGE4A6_3_1_R1_EVALUATE_METRICS Separate topology/parameter risks.
% Labels are used only here, after truth-free decisions have been produced.
% The effective statistical unit is an observation cluster, preferring the
% noiseless CFR hash, then the parameter hash, then the physical ID.
    if isempty(decisions) || isempty(labels), metrics = struct([]); return; end
    methods = unique({decisions.method_id}, 'stable');
    categories = unique({labels.category}, 'stable');
    metrics = repmat(metric_row(), 0, 1);
    for im = 1:numel(methods)
        for ic = 1:numel(categories)
            li = strcmp({labels.category}, categories{ic});
            lab = labels(li);
            [lab, cluster_ids] = cluster_labels(lab);
            did = strcmp({decisions.method_id}, methods{im});
            d0 = decisions(did);
            [tf, loc] = ismember({lab.sample_id}, {d0.sample_id});
            lab = lab(tf); cluster_ids = cluster_ids(tf); d = d0(loc(tf));
            if isempty(d), continue; end
            n = numel(d);
            truth = {lab.truth_topology_id};
            output_sets = cell(1,n);
            accepted = false(1,n);
            for k = 1:n
                output_sets{k} = split_ids(getfield_default(d(k), ...
                    'accepted_topology_set', getfield_default(d(k), ...
                    'topology_set', '')));
                accepted(k) = ismember(getfield_default(d(k), ...
                    'topology_status', ''), {'unique_topology', ...
                    'unique_given_prior', 'equivalence_class'});
            end
            truth_eq = cell(1,n); truth_eq_size = NaN(1,n);
            truth_eq_eval = false(1,n); truth_unique = false(1,n);
            for k = 1:n
                truth_eq{k} = split_ids(getfield_default(lab(k), ...
                    'truth_equivalence_set', ''));
                truth_eq_size(k) = getfield_default(lab(k), ...
                    'truth_equivalence_member_count', NaN);
                truth_eq_eval(k) = ~isempty(truth_eq{k}) && ...
                    isfinite(truth_eq_size(k)) && truth_eq_size(k) >= 1;
                truth_unique(k) = truth_eq_eval(k) && truth_eq_size(k) == 1;
            end
            topo_hit = false(1,n); topo_exact = false(1,n);
            for k = 1:n
                topo_hit(k) = accepted(k) && any(strcmp(output_sets{k}, truth{k}));
                topo_exact(k) = accepted(k) && truth_eq_eval(k) && ...
                    same_set(output_sets{k}, truth_eq{k});
            end
            parameter_truth_eval = ismember({lab.parameter_domain_truth}, ...
                {'in_domain','out_of_domain'});
            parameter_out = strcmp({lab.parameter_domain_truth}, 'out_of_domain');
            parameter_in = strcmp({lab.parameter_domain_truth}, 'in_domain');
            parameter_status = {d.parameter_domain_status};
            param_in_pred = strcmp(parameter_status, 'parameter_in_domain');
            param_out_pred = strcmp(parameter_status, 'parameter_out_suspected');
            param_definite = param_in_pred | param_out_pred;
            param_ind = parameter_truth_eval & ~param_definite;
            topo_wrong = accepted & ~topo_hit;
            param_wrong = parameter_truth_eval & param_definite & ...
                ((parameter_in & param_out_pred) | (parameter_out & param_in_pred));
            end_decided = accepted & param_definite;
            end_wrong = end_decided & (topo_wrong | param_wrong);

            r = metric_row();
            r.method_id = methods{im}; r.category = categories{ic};
            r.nominal_row_count = sum(did & ismember({decisions.sample_id}, ...
                {labels(li).sample_id}));
            r.unique_physical_scenario_count = count_unique_field(lab, ...
                'physical_scenario_id');
            r.unique_parameter_vector_count = count_unique_field(lab, ...
                'parameter_vector_hash');
            r.unique_observation_count = count_unique_field(lab, ...
                'noiseless_cfr_hash');
            r.observation_cluster_count = numel(unique(cluster_ids));
            r.duplicate_observation_count = r.nominal_row_count - n;
            r.effective_denominator = n;
            r.accepted_count = sum(accepted);
            r.false_unique_definition = ...
                'truth nonunique under frozen observation equivalence AND unique_topology output';
            fu_eval = truth_eq_eval;
            r.false_unique_evaluable_count = sum(fu_eval);
            r.false_unique_denominator = r.false_unique_evaluable_count;
            r.false_unique_numerator = sum(fu_eval & ~truth_unique & ...
                strcmp({d.topology_status}, 'unique_topology'));
            [r.false_unique_rate,r.false_unique_ci_low,r.false_unique_ci_high] = ...
                rate(r.false_unique_numerator, r.false_unique_evaluable_count);
            [r.topology_set_accuracy,r.topology_set_accuracy_ci_low, ...
                r.topology_set_accuracy_ci_high] = rate(sum(topo_hit), n);
            [r.equivalence_class_accuracy,r.equivalence_class_accuracy_ci_low, ...
                r.equivalence_class_accuracy_ci_high] = ...
                rate(sum(topo_exact), sum(truth_eq_eval));
            r.strict_unique_numerator = sum(strcmp({d.topology_status}, ...
                'unique_topology') & topo_hit);
            [r.strict_unique_accuracy,r.strict_unique_ci_low,r.strict_unique_ci_high] = ...
                rate(r.strict_unique_numerator, n);
            r.topology_acceptance_numerator = sum(accepted);
            [r.topology_acceptance_coverage,r.topology_acceptance_ci_low, ...
                r.topology_acceptance_ci_high] = rate(sum(accepted), n);
            r.topology_selective_risk_numerator = sum(topo_wrong);
            [r.topology_selective_risk,r.topology_selective_risk_ci_low, ...
                r.topology_selective_risk_ci_high] = ...
                rate(sum(topo_wrong), sum(accepted));
            r.parameter_evaluable_count = sum(parameter_truth_eval);
            r.parameter_decision_numerator = sum(parameter_truth_eval & param_definite);
            [r.parameter_decision_coverage,r.parameter_decision_ci_low, ...
                r.parameter_decision_ci_high] = rate(r.parameter_decision_numerator, ...
                r.parameter_evaluable_count);
            r.parameter_selective_risk_numerator = sum(param_wrong);
            [r.parameter_selective_risk,r.parameter_selective_risk_ci_low, ...
                r.parameter_selective_risk_ci_high] = rate(sum(param_wrong), ...
                r.parameter_decision_numerator);
            r.parameter_indeterminate_numerator = sum(param_ind);
            [r.parameter_indeterminate_rate,r.parameter_indeterminate_ci_low, ...
                r.parameter_indeterminate_ci_high] = rate(sum(param_ind), ...
                r.parameter_evaluable_count);
            r.ood_numerator = sum(parameter_out); r.in_domain_numerator = sum(parameter_in);
            r.ood_recall_numerator = sum(parameter_out & param_out_pred);
            [r.ood_recall,r.ood_recall_ci_low,r.ood_recall_ci_high] = ...
                rate(r.ood_recall_numerator, r.ood_numerator);
            r.ood_false_accept_numerator = sum(parameter_out & param_in_pred);
            [r.ood_false_acceptance_rate,r.ood_false_acceptance_ci_low, ...
                r.ood_false_acceptance_ci_high] = rate(r.ood_false_accept_numerator, ...
                r.ood_numerator);
            r.in_domain_false_alarm_numerator = sum(parameter_in & param_out_pred);
            [r.in_domain_false_alarm,r.in_domain_false_alarm_ci_low, ...
                r.in_domain_false_alarm_ci_high] = rate(r.in_domain_false_alarm_numerator, ...
                r.in_domain_numerator);
            r.end_to_end_numerator = sum(end_decided);
            [r.end_to_end_coverage,r.end_to_end_coverage_ci_low, ...
                r.end_to_end_coverage_ci_high] = rate(sum(end_decided), n);
            r.end_to_end_selective_risk_numerator = sum(end_wrong);
            [r.end_to_end_selective_risk,r.end_to_end_selective_risk_ci_low, ...
                r.end_to_end_selective_risk_ci_high] = rate(sum(end_wrong), ...
                sum(end_decided));
            r.indeterminate_numerator = sum(parameter_truth_eval & ~param_definite);
            [r.indeterminate_rate,r.indeterminate_ci_low,r.indeterminate_ci_high] = ...
                rate(r.indeterminate_numerator, r.parameter_evaluable_count);
            r.evaluable_count = n;
            r.definition_version = 'stage4a6_3_1_r1_metrics_v1';
            metrics(end+1) = r; %#ok<AGROW>
        end
    end
end

function r = metric_row()
    r = struct('method_id','','category','','nominal_row_count',0, ...
        'unique_physical_scenario_count',0,'unique_parameter_vector_count',0, ...
        'unique_observation_count',0,'observation_cluster_count',0, ...
        'duplicate_observation_count',0,'effective_denominator',0, ...
        'accepted_count',0,'false_unique_definition','','false_unique_evaluable_count',0, ...
        'false_unique_numerator',0,'false_unique_denominator',0, ...
        'false_unique_rate',NaN, ...
        'false_unique_ci_low',NaN,'false_unique_ci_high',NaN, ...
        'topology_set_accuracy',NaN,'topology_set_accuracy_ci_low',NaN, ...
        'topology_set_accuracy_ci_high',NaN,'equivalence_class_accuracy',NaN, ...
        'equivalence_class_accuracy_ci_low',NaN,'equivalence_class_accuracy_ci_high',NaN, ...
        'strict_unique_numerator',0,'strict_unique_accuracy',NaN, ...
        'strict_unique_ci_low',NaN,'strict_unique_ci_high',NaN, ...
        'topology_acceptance_numerator',0,'topology_acceptance_coverage',NaN, ...
        'topology_acceptance_ci_low',NaN,'topology_acceptance_ci_high',NaN, ...
        'topology_selective_risk_numerator',0,'topology_selective_risk',NaN, ...
        'topology_selective_risk_ci_low',NaN,'topology_selective_risk_ci_high',NaN, ...
        'parameter_evaluable_count',0,'parameter_decision_numerator',0, ...
        'parameter_decision_coverage',NaN,'parameter_decision_ci_low',NaN, ...
        'parameter_decision_ci_high',NaN,'parameter_selective_risk_numerator',0, ...
        'parameter_selective_risk',NaN,'parameter_selective_risk_ci_low',NaN, ...
        'parameter_selective_risk_ci_high',NaN,'parameter_indeterminate_numerator',0, ...
        'parameter_indeterminate_rate',NaN,'parameter_indeterminate_ci_low',NaN, ...
        'parameter_indeterminate_ci_high',NaN,'ood_numerator',0,'in_domain_numerator',0, ...
        'ood_recall_numerator',0,'ood_recall',NaN,'ood_recall_ci_low',NaN, ...
        'ood_recall_ci_high',NaN,'ood_false_accept_numerator',0, ...
        'ood_false_acceptance_rate',NaN,'ood_false_acceptance_ci_low',NaN, ...
        'ood_false_acceptance_ci_high',NaN,'in_domain_false_alarm_numerator',0, ...
        'in_domain_false_alarm',NaN,'in_domain_false_alarm_ci_low',NaN, ...
        'in_domain_false_alarm_ci_high',NaN,'end_to_end_numerator',0, ...
        'end_to_end_coverage',NaN,'end_to_end_coverage_ci_low',NaN, ...
        'end_to_end_coverage_ci_high',NaN,'end_to_end_selective_risk_numerator',0, ...
        'end_to_end_selective_risk',NaN,'end_to_end_selective_risk_ci_low',NaN, ...
        'end_to_end_selective_risk_ci_high',NaN,'indeterminate_numerator',0, ...
        'indeterminate_rate',NaN,'indeterminate_ci_low',NaN,'indeterminate_ci_high',NaN, ...
        'evaluable_count',0,'definition_version','');
end

function [out, cluster_ids] = cluster_labels(labels)
    out = repmat(labels(1),0,1); cluster_ids = {};
    keys = cell(1,numel(labels));
    for k=1:numel(labels)
        keys{k}=getfield_default(labels(k),'noiseless_cfr_hash','');
        if isempty(keys{k}), keys{k}=getfield_default(labels(k),'parameter_vector_hash',''); end
        if isempty(keys{k}), keys{k}=getfield_default(labels(k),'physical_scenario_id',labels(k).sample_id); end
    end
    [u,ia] = unique(keys,'stable'); %#ok<ASGLU>
    out = labels(ia); cluster_ids = keys(ia);
end

function ids = split_ids(s)
    if isstring(s), s=char(s); end
    if isempty(s), ids={}; elseif iscell(s), ids=s; else, ids=strsplit(char(s),','); end
    ids = ids(~cellfun(@isempty,ids));
end
function tf = same_set(a,b),tf=numel(a)==numel(b)&&all(ismember(a,b))&&all(ismember(b,a));end
function n = count_unique_field(s, f)
    x = cell(1,numel(s)); for k=1:numel(s), x{k}=getfield_default(s(k),f,''); end
    x=x(~cellfun(@isempty,x)); if isempty(x),n=0;else,n=numel(unique(x));end
end
function [p,l,h] = rate(a,b)
    if b==0, p=NaN;l=NaN;h=NaN; return; end
    p=a/b; ci=stage4a6_3_wilson_interval(a,b); l=ci(1);h=ci(2);
end
function v=getfield_default(s,n,d),if isstruct(s)&&isfield(s,n),v=s.(n);else,v=d;end,end
