function out=stage7a6_score_observation(observed,pool,bank,base,cfg, ...
        base_indices,views,sigma,budget,model)
%STAGE7A6_SCORE_OBSERVATION Truth-free Stage 7A.6 expanded scorer.
%   Continuous profile bounds, training indices and holdout statistic are
%   inherited unchanged from Stage 7A.5. All lengths use m, frequency Hz.
    if nargin<10,model=[];end
    if ~isempty(model)
        if ~strcmp(model.kind,'C')||model.budget~=budget|| ...
                ~strcmp(model.bank_identity,bank.identity)|| ...
                ~strcmp(model.search_identity,bank.search_identity)|| ...
                ~isequal(model.views,views)
            error('stage7a6:CalibrationIdentityMismatch', ...
                'Calibrated budget, pool, search domain or view differs.');
        end
    end
    p=stage7a6_expand_candidates(observed,pool,bank,base,cfg, ...
        base_indices,views,sigma,budget);
    [~,best_local]=min(p.distances);
    best=p.active_indices(best_local);
    h=stage7a5_holdout_stat(observed,pool(best).network, ...
        p.params(best_local,:),base,cfg,views,sigma);
    out=struct('candidate_indices',p.active_indices, ...
        'candidate_ids',{p.active_ids},'distances',p.distances, ...
        'params',p.params,'grid_distances',p.grid_distances, ...
        'optimizer_evaluations',p.total_optimizer_evaluations, ...
        'profile_evaluations',p.total_profile_evaluations, ...
        'fit_statistic',h.statistic,'holdout_statistic',h.statistic, ...
        'search_truncated',p.search_truncated, ...
        'generated_ids',{p.generated_ids}, ...
        'profile_candidate_count',numel(p.active_indices), ...
        'views',views,'forward_model_calls_search',0, ...
        'forward_model_calls_holdout',1);
end
