function model=stage7a5_calibrate_legacy(a_dist,a_truth,f_dist,bank, ...
        candidate_indices,views,sigma,cfg)
%STAGE7A5_CALIBRATE_LEGACY Recreate Stage 7A.4 A/F rules on independent data.
    class_threshold=zeros(1,numel(candidate_indices));
    for k=1:numel(candidate_indices)
        x=sort(a_dist(a_truth==candidate_indices(k),k));
        assert(numel(x)>=2,'stage7a5:TooFewA');
        rank=ceil((numel(x)+1)*(1-cfg.alpha));
        if rank>numel(x),class_threshold(k)=Inf;else,class_threshold(k)=x(rank);end
    end
    fit=sort(min(f_dist,[],2));rank=ceil((numel(fit)+1)*(1-cfg.alpha));
    if rank>numel(fit),fit_threshold=Inf;else,fit_threshold=fit(rank);end
    ids=bank.candidate_ids(candidate_indices);
    model=struct('kind','legacy_full_profile','candidate_indices',candidate_indices, ...
        'candidate_ids',{ids},'candidate_signatures',{bank.candidate_signatures(candidate_indices)}, ...
        'views',views,'sigma',sigma,'class_threshold',class_threshold, ...
        'set_threshold',NaN,'fit_threshold',fit_threshold, ...
        'margin_threshold',cfg.margin_threshold,'alpha',cfg.alpha, ...
        'bank_identity',bank.identity,'search_identity',bank.search_identity, ...
        'calibration_identity',stage4a4_scientific_config_hash(struct( ...
            'a_dist',a_dist,'a_truth',a_truth,'f_dist',f_dist,'ids',{ids}, ...
            'views',views,'sigma',sigma)));
end
