function model=stage7a4_calibrate_decision(a_distances,a_truth,f_distances,bank, ...
        candidate_indices,view_indices,sigma,cfg,label)
%STAGE7A4_CALIBRATE_DECISION Independent A/F split set and fit thresholds.
%   A truth labels are used here only; the scoring function never receives
%   them. Thresholds are empirical order statistics, not OOD guarantees.
    m=numel(candidate_indices);a_truth=a_truth(:);
    assert(size(a_distances,2)==m&&numel(a_truth)==size(a_distances,1) && ...
        size(f_distances,2)==m&&all(isfinite(a_distances(:)))&& ...
        all(isfinite(f_distances(:))),'stage7a4:CalibrationShape');
    class_threshold=zeros(1,m);counts=zeros(1,m);
    for k=1:m
        scores=sort(a_distances(a_truth==k,k));counts(k)=numel(scores);
        assert(counts(k)>=2,'stage7a4:TooFewCalibration');
        rank=ceil((counts(k)+1)*(1-cfg.alpha));
        if rank>counts(k),class_threshold(k)=Inf;
        else,class_threshold(k)=scores(rank);end
    end
    fit=sort(min(f_distances,[],2));n=numel(fit);
    rank=ceil((n+1)*(1-cfg.alpha));
    if rank>n,fit_threshold=Inf;else,fit_threshold=fit(rank);end
    ids=bank.candidate_ids(candidate_indices);
    model=struct('label',label,'candidate_indices',candidate_indices, ...
        'candidate_ids',{ids},'candidate_signatures',{bank.candidate_signatures(candidate_indices)}, ...
        'view_indices',view_indices,'sigma',sigma,'class_threshold',class_threshold, ...
        'class_counts',counts,'fit_threshold',fit_threshold,'fit_count',n, ...
        'alpha',cfg.alpha,'margin_threshold',cfg.separation_threshold, ...
        'bank_identity',bank.identity,'calibration_identity', ...
        stage4a4_scientific_config_hash(struct('label',label,'ids',{ids}, ...
            'view_indices',view_indices,'bank_identity',bank.identity, ...
            'sigma',sigma,'a_distances',a_distances,'a_truth',a_truth, ...
            'f_distances',f_distances,'alpha',cfg.alpha)));
end
