function [hash, canonical, identity] = stage4a6_3_1_r_build_compatibility_hash(sc,candidates,theta_grid,source_hash,cache)
%STAGE4A6_3_1_R_BUILD_COMPATIBILITY_HASH Shared calibration/evaluation identity.
% Split seeds are intentionally excluded from this scientific identity.
    cm = repmat(struct('topology_id','','canonical_key',''),numel(candidates),1);
    for k=1:numel(candidates)
        cm(k).topology_id=candidates(k).topology_id;
        cm(k).canonical_key=candidates(k).canonical_key;
    end
    identity = struct('candidate_library_hash',stage4a4_scientific_config_hash(cm), ...
        'candidate_grammar_hash',stage4a4_scientific_config_hash(sc.generator), ...
        'prior_hash',stage4a4_scientific_config_hash(struct('source',sc.prior_source, ...
        'mode',sc.candidate_generation_mode)), ...
        'observation_hash',stage4a4_scientific_config_hash(struct('grid_id',sc.grid_id, ...
        'frequency_hz',sc.grids(1).frequency_hz,'measurement_kind',sc.measurement_kind, ...
        'termination',sc.termination)), ...
        'feature_hash',stage4a4_scientific_config_hash(sc.distance), ...
        'confirmation_config_hash',stage4a4_scientific_config_hash(sc.confirmation), ...
        'parameter_domain_hash',stage4a4_scientific_config_hash(struct( ...
        'search',sc.parameter_search,'eta',sc.extended_domain_eta,'profile',sc.profile)), ...
        'cache_hash',getfield_default(cache,'cache_configuration_hash',''), ...
        'random_seed_identity','stable_seed(master_seed,sample_id,split-specific master)', ...
        'source_tree_hash',source_hash);
    payload = struct('stage',sc.stage_name,'version',sc.version, ...
        'grid_id',sc.grid_id,'identity',identity,'generator',sc.generator, ...
        'parameter_search',sc.parameter_search,'extended_domain_eta',sc.extended_domain_eta, ...
        'profile',sc.profile,'confirmation',sc.confirmation, ...
        'protocol',sc.protocol,'logic_version','stage4a6_3_1_r_compatibility_v1');
    [hash,canonical] = stage4a4_scientific_config_hash(payload);
end
function v=getfield_default(s,n,d)
    if isstruct(s)&&isfield(s,n),v=s.(n);else,v=d;end
end
