function [sample,candidate_rows]=stage7a1_audit_decision(observation,model,distances,truth_signature,profile)
%STAGE7A1_AUDIT_DECISION Expose unchanged candidate-set and four-state gates.
%   DISTANCES is a 1-by-candidate vector from either cached search method.
%   PROFILE may be empty for the Stage 6B baseline. Truth is used only for
%   audit labels, never by any scoring or calibration function.
    if nargin<5,profile=[];end
    d=double(distances(:).');ids=model.candidate_ids;m=numel(ids);
    assert(numel(d)==m&&all(isfinite(d)),'stage7a1:InvalidDistances', ...
        'Profile distance count does not match candidate library.');
    accepted=stage4a7_2_r1_apply_profile_candidate_set(d,model.topology_model,'absolute');
    margin=compute_candidate_margin(d,ids);
    confidence=compute_candidate_confidence(d,model.evidence_model.beta,ids);
    relative=min(d)/max(sqrt(mean(abs(observation(:)).^2)),eps);
    domain_pass=relative<=model.domain_threshold;
    best_in_set=any(strcmp(accepted.accepted_candidate_set,margin.best_candidate{1}));
    frozen=struct('candidate_set_size',accepted.set_size, ...
        'domain_accepted',domain_pass,'best_candidate_in_set',best_in_set);
    decision=classify_stage5b1_decision_state(frozen,struct('margin',margin.margin), ...
        struct('top1_confidence',confidence.top1_confidence, ...
        'normalized_entropy',confidence.normalized_entropy),model.evidence_model);
    signatures=cell(1,m);
    for k=1:m,signatures{k}=stage6b_network_signature(model.candidates(k).network);end
    truth_index=find(strcmp(signatures,truth_signature),1);
    ranked=sortrows([d(:),(1:m).'],[1 2]);ranks=zeros(1,m);
    for k=1:m,ranks(ranked(k,2))=k;end
    truth_in_library=~isempty(truth_index);
    truth_in_set=false;truth_rank=NaN;truth_distance=NaN;
    if truth_in_library
        truth_in_set=any(strcmp(accepted.accepted_candidate_set,ids{truth_index}));
        truth_rank=ranks(truth_index);truth_distance=d(truth_index);
    end
    best_is_truth=truth_in_library&&margin.best_index==truth_index;
    if ~truth_in_library,failure='truth_not_in_library';
    elseif ~best_is_truth,failure='wrong_top1';
    elseif ~truth_in_set,failure='truth_not_in_candidate_set';
    elseif ~domain_pass,failure='domain_gate_rejection';
    elseif accepted.set_size>1,failure='multiple_candidate_set';
    elseif ~decision.evidence_sufficient,failure='unique_evidence_not_met';
    else,failure='none';end
    if isfield(model,'candidate_library_hash'),library_hash=model.candidate_library_hash;
    else,library_hash=stage4a4_scientific_config_hash(struct('ids',{ids},'signatures',{signatures}));end
    sample=struct('candidate_count',m,'candidate_library_hash',library_hash, ...
        'truth_in_library',truth_in_library,'truth_index',index_or_nan(truth_index), ...
        'truth_rank',truth_rank,'truth_distance',truth_distance, ...
        'best_index',margin.best_index,'best_candidate',margin.best_candidate{1}, ...
        'best_is_truth',best_is_truth,'correct_unique',best_is_truth&& ...
            strcmp(decision.enhanced_decision_state,'UNIQUE_CONFIDENT'), ...
        'false_unique',~best_is_truth&& ...
            strcmp(decision.enhanced_decision_state,'UNIQUE_CONFIDENT'), ...
        'candidate_set',strjoin(cellstr(accepted.accepted_candidate_set),','), ...
        'candidate_set_size',accepted.set_size,'candidate_set_empty',accepted.empty, ...
        'truth_in_candidate_set',truth_in_set,'alpha',model.topology_model.alpha, ...
        'domain_relative_distance',relative,'domain_threshold',model.domain_threshold, ...
        'domain_pass',domain_pass,'d1',margin.d1,'d2',margin.d2, ...
        'top1_top2_margin',margin.margin, ...
        'margin_threshold',model.evidence_model.margin_threshold, ...
        'margin_pass',decision.margin_pass, ...
        'top1_confidence',confidence.top1_confidence, ...
        'confidence_threshold',model.evidence_model.top1_confidence_threshold, ...
        'confidence_pass',decision.confidence_pass, ...
        'entropy',confidence.entropy,'normalized_entropy',confidence.normalized_entropy, ...
        'entropy_threshold',model.evidence_model.normalized_entropy_threshold, ...
        'entropy_pass',decision.entropy_pass,'best_in_set',best_in_set, ...
        'evidence_sufficient',decision.evidence_sufficient, ...
        'decision_state',decision.enhanced_decision_state, ...
        'decision_reason',decision.decision_reason,'failure_class',failure, ...
        'set_exclusion',truth_in_library&&~truth_in_set, ...
        'domain_rejection',~domain_pass, ...
        'evidence_gate_failure',~decision.evidence_sufficient, ...
        'multiple_competitors',accepted.set_size>1);
    candidate_rows=repmat(struct('candidate_id','','candidate_signature','', ...
        'candidate_rank',0,'profile_distance',NaN,'candidate_p_value',NaN, ...
        'in_candidate_set',false,'is_truth',false, ...
        'normalized_confidence_score',NaN,'best_template_index',NaN, ...
        'best_main_scale',NaN,'best_branch_load_scale',NaN),m,1);
    for k=1:m
        candidate_rows(k).candidate_id=ids{k};
        candidate_rows(k).candidate_signature=signatures{k};
        candidate_rows(k).candidate_rank=ranks(k);
        candidate_rows(k).profile_distance=d(k);
        candidate_rows(k).candidate_p_value=accepted.p_values(k);
        candidate_rows(k).in_candidate_set=accepted.p_values(k)>model.topology_model.alpha;
        candidate_rows(k).is_truth=truth_in_library&&k==truth_index;
        candidate_rows(k).normalized_confidence_score=confidence.normalized_confidence_scores(k);
        if ~isempty(profile)
            candidate_rows(k).best_template_index=profile.best_template_indices(k);
            candidate_rows(k).best_main_scale=profile.best_main_scale(k);
            candidate_rows(k).best_branch_load_scale=profile.best_branch_load_scale(k);
        end
    end
end
function x=index_or_nan(x),if isempty(x),x=NaN;end,end
