function fairness = stage3b_pre_fair_sampling(band, total_energy, target_time_s)
%STAGE3B_PRE_FAIR_SAMPLING Declare, rather than optimize, Level-A fairness.
    if nargin<2||isempty(total_energy),total_energy=1;end
    if nargin<3||isempty(target_time_s),target_time_s=3.2e-3;end
    payload_s=band.nfft/band.fs_hz;
    repetitions=max(1,round(target_time_s/payload_s));
    fairness=struct('total_injected_energy',total_energy, ...
        'energy_per_frequency_sample_per_repetition',total_energy/(band.active_point_count*repetitions), ...
        'payload_duration_s',payload_s,'target_observation_time_s',target_time_s, ...
        'repetitions',repetitions,'achieved_observation_time_s',repetitions*payload_s, ...
        'noise_reference','post-line CFR sample; equal receiver-domain SNR definition', ...
        'note',['Ideal known CFR samples are used. Energy/time fields define the ' ...
        'fairness contract but do not instantiate a PHY frame, pilot or PSD.']);
end
