function out=stage7a2_score_distances(observation,distances,model)
%STAGE7A2_SCORE_DISTANCES Truth-free fixed-model set and four-state decision.
%   MODEL contains the exact candidate library and A/B calibration identity.
    d=double(distances(:).');y=observation(:).';
    assert(numel(d)==numel(model.candidate_ids)&&all(isfinite(d))&& ...
        numel(y)==numel(model.frequency_hz)&&all(isfinite(y)), ...
        'stage7a2:ScoringShape','Observation and model shape mismatch.');
    assert(strcmp(model.set_model.identity,model.identity), ...
        'stage7a2:CalibrationIdentityMismatch','Candidate-set model identity mismatch.');
    accepted=stage7a2_apply_set(d,model.set_model);
    margin=compute_candidate_margin(d,model.candidate_ids);
    confidence=compute_candidate_confidence(d,model.evidence_model.beta,model.candidate_ids);
    relative=min(d)/max(sqrt(mean(abs(y).^2)),eps);
    frozen=struct('candidate_set_size',accepted.set_size, ...
        'domain_accepted',relative<=model.domain_threshold, ...
        'best_candidate_in_set',accepted.keep(margin.best_index));
    decision=classify_stage5b1_decision_state(frozen,struct('margin',margin.margin), ...
        struct('top1_confidence',confidence.top1_confidence, ...
        'normalized_entropy',confidence.normalized_entropy),model.evidence_model);
    state=decision.enhanced_decision_state;reason=decision.decision_reason;
    if isfield(model,'risk_gate')&&~model.risk_gate.certified&&strcmp(state,'UNIQUE_CONFIDENT')
        state='LOW_CONFIDENCE';reason='independent_selective_risk_gate_not_certified';
    end
    out=struct('candidate_set',strjoin(accepted.candidate_set,','), ...
        'candidate_set_size',accepted.set_size,'candidate_keep',accepted.keep, ...
        'candidate_p_values',accepted.p_values,'best_candidate',margin.best_candidate{1}, ...
        'best_index',margin.best_index,'distance',margin.d1,'second_distance',margin.d2, ...
        'margin',margin.margin,'top1_confidence',confidence.top1_confidence, ...
        'normalized_entropy',confidence.normalized_entropy, ...
        'domain_relative_distance',relative,'domain_threshold',model.domain_threshold, ...
        'domain_accepted',frozen.domain_accepted, ...
        'margin_pass',decision.margin_pass,'confidence_pass',decision.confidence_pass, ...
        'entropy_pass',decision.entropy_pass, ...
        'decision_state',state,'decision_reason',reason);
end
