function hash = stage4a6_1_source_tree_hash(root)
%STAGE4A6_1_SOURCE_TREE_HASH Hash implementation without absolute paths.
    rel = { ...
        'config/stage4a6_1_optimizer_config.m', ...
        'src/stage4a6_1_parameter_names.m', ...
        'src/topology_active_parameter_mask.m', ...
        'src/optimize_stage4a6_1_parameters.m', ...
        'src/compute_stage4a6_1_jacobian.m', ...
        'src/compute_stage4a6_1_profile.m', ...
        'src/compute_stage4a6_1_member_evidence.m', ...
        'src/calibrate_stage4a6_1_parameter_domain.m', ...
        'src/apply_stage4a6_1_parameter_decision.m', ...
        'src/evaluate_stage4a6_1_metrics.m', ...
        'src/run_stage4a6_1_member_batch.m', ...
        'src/generate_stage4a6_1_trial_bank.m'};
    payload = repmat(struct('relative_path','','content',''), numel(rel), 1);
    for k = 1:numel(rel)
        payload(k).relative_path = rel{k};
        payload(k).content = fileread(fullfile(root,rel{k}));
    end
    hash = stage4a4_scientific_config_hash(payload);
end
