function [model,timing]=stage7a1_calibrate_split_library(candidates,base,sc,cache,condition,tag,set_seed_base,evidence_seed_base,original_model)
%STAGE7A1_CALIBRATE_SPLIT_LIBRARY Diagnostic A/B calibration with disjoint seeds.
%   A calibrates candidate set/domain; B calibrates Stage 5B.1 evidence.
%   A supplied original_model holds A fixed and replaces only its evidence
%   calibration from an independent B batch. No test observation enters here.
    if nargin<9,original_model=[];end
    assert(set_seed_base~=evidence_seed_base,'stage7a1:SeedOverlap', ...
        'Candidate-set and evidence seed bases must differ.');
    n=condition.per_candidate;
    assert(n>=2&&n<=200,'stage7a1:CalibrationCount','Unsupported diagnostic calibration count.');
    assert(isequal(cache.candidate_ids,{candidates.topology_id}), ...
        'stage7a1:CandidateIdentity','Cache candidate order differs from library.');
    ids=cache.candidate_ids;
    timing=struct('set_time_s',0,'evidence_time_s',0);
    if isempty(original_model)
        started=tic;
        [a,truth_a,relative_a,seeds_a]=generate_block(candidates,base,sc,cache,condition,set_seed_base);
        set_id=stage4a4_scientific_config_hash(struct('role','candidate_set', ...
            'condition',condition,'tag',tag,'seeds',seeds_a,'library',{cache.candidate_signatures}));
        options=struct('minimum_per_candidate',n,'resolution',eps, ...
            'compatibility_hash',stage4a4_scientific_config_hash(struct('stage','7A.1', ...
            'tag',tag,'condition',condition,'set_id',set_id,'search',sc.search, ...
            'admissible',{cache.admissible},'frequency_hz',sc.frequency_hz)));
        topology_model=stage4a7_2_r1_calibrate_profile_method(a,truth_a,ids,'absolute',sc.alpha,options);
        domain_threshold=fixed_quantile(relative_a,sc.domain_quantile);
        timing.set_time_s=toc(started);
    else
        assert(isequal(original_model.candidate_ids,ids), ...
            'stage7a1:CandidateIdentity','Original candidate-set model differs from cache.');
        a=original_model.calibration_distances;
        truth_a=original_model.calibration_truth_index;
        topology_model=original_model.topology_model;
        domain_threshold=original_model.domain_threshold;
        set_id=stage4a4_scientific_config_hash(struct('role','stage7a_original', ...
            'tag',tag,'seed',original_model.calibration_seed, ...
            'offset',original_model.calibration_seed_offset, ...
            'topology_calibration_hash',topology_model.calibration_hash));
    end
    started=tic;
    [b,truth_b,~,seeds_b]=generate_block(candidates,base,sc,cache,condition,evidence_seed_base);
    set_size=zeros(size(b,1),1);
    b_truth_in_set=false(size(b,1),1);
    for q=1:size(b,1)
        accepted=stage4a7_2_r1_apply_profile_candidate_set(b(q,:),topology_model,'absolute');
        set_size(q)=accepted.set_size;
        b_truth_in_set(q)=any(strcmp(accepted.accepted_candidate_set,ids{truth_b(q)}));
    end
    a_truth_in_set=false(size(a,1),1);
    for q=1:size(a,1)
        accepted=stage4a7_2_r1_apply_profile_candidate_set(a(q,:),topology_model,'absolute');
        a_truth_in_set(q)=any(strcmp(accepted.accepted_candidate_set,ids{truth_a(q)}));
    end
    eopts=sc.evidence_calibration;eopts.candidate_ids=ids;
    evidence_model=calibrate_stage5b1_decision_metrics(b,truth_b,set_size,eopts);
    evidence_id=stage4a4_scientific_config_hash(struct('role','evidence', ...
        'condition',condition,'tag',tag,'seeds',seeds_b,'set_id',set_id));
    timing.evidence_time_s=toc(started);
    model=struct('tag',tag,'candidates',candidates,'candidate_ids',{ids},'cache',cache, ...
        'topology_model',topology_model,'evidence_model',evidence_model, ...
        'domain_threshold',domain_threshold,'calibration_set_id',set_id, ...
        'evidence_set_id',evidence_id,'set_seed_base',set_seed_base, ...
        'evidence_seed_base',evidence_seed_base,'set_per_candidate',n, ...
        'evidence_per_candidate',n,'evidence_reference_count',evidence_model.reference_sample_count, ...
        'set_in_sample_truth_coverage',mean(a_truth_in_set), ...
        'evidence_out_of_sample_truth_coverage',mean(b_truth_in_set), ...
        'evidence_out_of_sample_empty_count',nnz(set_size==0), ...
        'evidence_out_of_sample_singleton_count',nnz(set_size==1), ...
        'candidate_library_hash',stage4a4_scientific_config_hash(struct( ...
            'ids',{ids},'signatures',{cache.candidate_signatures})), ...
        'search_domain_hash',stage4a4_scientific_config_hash(struct( ...
            'search',sc.search,'admissible',{cache.admissible})), ...
        'cache_grid_hash',stage4a4_scientific_config_hash(struct( ...
            'main_scale',cache.main_scale,'branch_load_scale',cache.branch_load_scale, ...
            'coarse_mask',cache.coarse_mask)), ...
        'calibration_frequency_hz',sc.frequency_hz, ...
        'scope','stage7a1_independent_set_and_evidence_calibration');
end

function [distances,truth_index,relative,seeds]=generate_block(candidates,base,sc,cache,condition,seed_base)
    n=condition.per_candidate;m=numel(candidates);
    distances=zeros(n*m,m);truth_index=zeros(n*m,1);relative=zeros(n*m,1);
    seeds=zeros(n*m,1);cursor=0;
    for j=1:m
        allowed=cache.main_scale(cache.admissible{j});
        main_bounds=[max(min(allowed),condition.main_bounds(1)), ...
            min(max(allowed),condition.main_bounds(2))];
        assert(main_bounds(1)<=main_bounds(2),'stage7a1:EmptyCalibrationDomain', ...
            'Condition has no admissible main-length interval for candidate %d.',j);
        for r=1:n
            cursor=cursor+1;seed=seed_base+j*1000+r;seeds(cursor)=seed;
            rs=RandStream('mt19937ar','Seed',seed);
            theta=struct('main_length_scale',draw_uniform(rs,main_bounds), ...
                'branch_length_scale',sc.search.branch_length_scale, ...
                'branch_load_scale',draw_uniform(rs,condition.load_bounds), ...
                'source_impedance_ohm',sc.search.source_impedance_ohm, ...
                'receiver_impedance_ohm',sc.search.receiver_impedance_ohm,'regularization',0);
            clean=stage6b_forward_cfr(candidates(j).network,theta,base, ...
                sc.frequency_hz,sc.measurement_kind);
            observation=add_noise(clean,condition.snr_db,rs);
            profile=stage7a_profile_distance(observation,cache,sc.search);
            distances(cursor,:)=profile.profile_distances;truth_index(cursor)=j;
            relative(cursor)=min(profile.profile_distances)/ ...
                max(sqrt(mean(abs(observation).^2)),eps);
        end
    end
end
function x=draw_uniform(rs,b)
    x=b(1)+(b(2)-b(1))*rand(rs);
end
function y=add_noise(x,snr,rs)
    if isinf(snr),y=x;return;end
    s=sqrt(mean(abs(x).^2)/10^(snr/10)/2);
    y=x+s*(randn(rs,size(x))+1i*randn(rs,size(x)));
end
function y=fixed_quantile(x,q)
    x=sort(double(x(:)));y=x(max(1,min(numel(x),ceil(q*numel(x)))));
end
