function placeholder = stage3b_pre_fair_sampling(band)
%STAGE3B_PRE_FAIR_SAMPLING Describe deferred waveform-level fairness only.
%   This function deliberately does not allocate energy, create repetitions,
%   alter noise variance, average observations, or affect matching.
    placeholder=struct('status','future_waveform_fairness_placeholder', ...
        'band_name',band.name,'payload_duration_s',band.nfft/band.fs_hz, ...
        'not_used_in_current_observation_statistics',true, ...
        'note',['Current Stage-3B-pre uses one ideal known CFR vector plus optional ' ...
        'receiver-domain sample noise. Energy/time fairness is not implemented.']);
end
