function out=stage7a11_decide(observed,bank,model)
%STAGE7A11_DECIDE Four-state joint-selector decision; no generating truth.
%   Calibration identity binds graph ordering, sigma, selector and thresholds.
    assert(strcmp(bank.identity,model.bank_identity) && ...
        isequal(bank.candidate_ids(model.indices),model.candidate_ids), ...
        'stage7a11:CalibrationIdentity');
    assert(isfield(model.selector,'algorithm') && ...
        strcmp(model.selector.algorithm,'joint_h50_conditioned_grid_v1'), ...
        'stage7a11:CalibrationIdentity');
    p=stage7a11_adaptive_profile(observed,bank,model.indices, ...
        model.sigma,model.selector,model.first_threshold);
    d=p.distances;keep=d<=model.class_threshold & p.first_set;
    if p.selected_view==0,keep(:)=false;end
    [sorted,order]=sort(d);margin=sorted(2)-sorted(1);
    fit_pass=sorted(1)<=model.fit_threshold;
    if p.selected_view==0
        state='REJECTED';reason='empty_first_set';
    elseif ~fit_pass
        state='REJECTED';reason='fit_quality_gate';
    elseif ~any(keep)
        state='REJECTED';reason='empty_candidate_set';
    elseif nnz(keep)>1
        state='MULTIPLE_AMBIGUOUS';reason='multiple_candidates';
    elseif p.separation<model.extra_view_threshold
        state='LOW_CONFIDENCE';reason='insufficient_joint_view_separation';
    elseif ~keep(order(1)) || margin<model.margin_threshold
        state='LOW_CONFIDENCE';reason='insufficient_unique_margin';
    else
        state='UNIQUE_CONFIDENT';reason='single_candidate_with_margin';
    end
    out=struct('candidate_set',strjoin(model.candidate_ids(keep),','), ...
        'candidate_set_size',nnz(keep),'best_candidate',model.candidate_ids{order(1)}, ...
        'distance',sorted(1),'second_distance',sorted(2),'margin',margin, ...
        'fit_threshold',model.fit_threshold,'fit_accepted',fit_pass, ...
        'decision_state',state,'decision_reason',reason, ...
        'all_distances',d,'selected_view',p.selected_view, ...
        'first_set',p.first_set,'first_distances',p.first_distances, ...
        'extra_view_separation',p.separation,'view_scores',p.view_scores, ...
        'competition_indices',p.competition_indices, ...
        'class_threshold',model.class_threshold);
end
