function [expected,hash] = stage4a5_1_cache_expected(grid,candidates,theta_grid,cfg,sc,source_hash)
%STAGE4A5_1_CACHE_EXPECTED Build complete path-independent cache identity.
    manifest=repmat(struct('topology_id','','canonical_key',''),numel(candidates),1);
    for k=1:numel(candidates),manifest(k)=struct('topology_id',candidates(k).topology_id,'canonical_key',candidates(k).canonical_key);end
    payload=struct('schema',sc.cache_schema_version,'frequency_hz',grid.frequency_hz(:).', ...
        'frequency_grid_id',grid.id,'candidates',manifest,'parameter_grid',theta_grid, ...
        'measurement_kind',sc.measurement_kind,'source_impedance_ohm',cfg.Zs, ...
        'receiver_impedance_ohm',cfg.Zr,'distance_feature',sc.distance.feature, ...
        'distance_weights',sc.distance.weights,'distance_options',sc.distance.options, ...
        'tie_tolerance',sc.distance.tie_tolerance,'forward_model_source_hash',source_hash);
    hash=stage4a4_scientific_config_hash(payload);
    expected=payload;expected.cache_schema_version=sc.cache_schema_version;
    expected.cache_configuration_hash=hash;
end
