function out=stage7a1_exhaustive_profile_distance(observation,cache,search)
%STAGE7A1_EXHAUSTIVE_PROFILE_DISTANCE Audit all cached admissible fine cells.
%   Input CFR is one complex row; output distances are 1-by-candidate.
%   This audit never constructs templates or alters the production search.
    y=observation(:).';
    assert(numel(y)==numel(cache.frequency_hz)&&all(isfinite(y)), ...
        'stage7a1:InvalidObservation','Observation is incompatible with cached CFR templates.');
    n=numel(cache.candidate_ids);d=zeros(1,n);best=zeros(1,n);pivot=zeros(1,n);
    pivot_distance=zeros(1,n);global_in_local=false(1,n);comparisons=0;t=tic;
    for k=1:n
        allow=cache.admissible{k};indices=find(allow);H=cache.H{k};
        all_d=sqrt(mean(abs(H(indices,:)-y).^2,2));
        [d(k),pos]=min(all_d);best(k)=indices(pos);
        coarse=find(cache.coarse_mask&allow);
        coarse_d=sqrt(mean(abs(H(coarse,:)-y).^2,2));
        [pivot_distance(k),cpos]=min(coarse_d);pivot(k)=coarse(cpos);
        local=allow & abs(cache.main_scale-cache.main_scale(pivot(k)))<= ...
            search.coarse_main_step+1e-12 & ...
            abs(cache.branch_load_scale-cache.branch_load_scale(pivot(k)))<= ...
            search.coarse_load_step/2+1e-12;
        global_in_local(k)=local(best(k));
        comparisons=comparisons+numel(indices)+numel(coarse);
    end
    out=struct('profile_distances',d,'best_template_indices',best, ...
        'best_main_scale',cache.main_scale(best), ...
        'best_branch_load_scale',cache.branch_load_scale(best), ...
        'coarse_pivot_indices',pivot,'coarse_pivot_distance',pivot_distance, ...
        'global_in_local_window',global_in_local, ...
        'template_comparisons',comparisons,'forward_evaluations',0, ...
        'runtime_s',toc(t),'definition_version','stage7a1_exhaustive_cached_fine_audit_v1');
end
