function model=stage7a13_calibrate_h50(cal_graphs,inference_bank,base,cfg)
%STAGE7A13_CALIBRATE_H50 Pooled and meter-count class/fit gates.
%   E/A/F use disjoint seeds and graph structures outside final test.
%   Calibration scores each graph against its own H50 template bank;
%   inference_bank identity binds the frozen 17-graph application library.
    signatures=arrayfun(@(g)stage6b_network_signature(g.network), ...
        cal_graphs,'UniformOutput',false);
    assert(numel(unique(signatures))==numel(cal_graphs), ...
        'stage7a13:DuplicateCalibrationGraph');
    assert(numel(unique([cfg.seed_cfr_E,cfg.seed_cfr_A,cfg.seed_cfr_F, ...
        cfg.seed_cfr_T]))==4,'stage7a13:SeedLeakage');
    cal_bank=stage7a4_template_bank(cal_graphs,base,cfg);
    ix=1:numel(cal_graphs);
    E=stage7a4_generate_split(cal_graphs,ix,base,cfg, ...
        cfg.seed_cfr_E,cfg.n_cfr_cal_per_graph,20,'standard');
    sigma=stage7a4_calibrate_view_scales(E,cfg);
    A=stage7a4_generate_split(cal_graphs,ix,base,cfg, ...
        cfg.seed_cfr_A,cfg.n_cfr_cal_per_graph,20,'standard');
    F=stage7a4_generate_split(cal_graphs,ix,base,cfg, ...
        cfg.seed_cfr_F,cfg.n_cfr_cal_per_graph,20,'standard');
    [a,a_meter,a_graph]=truth_scores(A,cal_graphs,cal_bank,sigma);
    [f,f_meter,f_graph]=truth_scores(F,cal_graphs,cal_bank,sigma);
    alpha=0.05;pooled_class=quantile_ceil(a,1-alpha);
    pooled_fit=quantile_ceil(f,1-alpha);
    max_meter=max([a_meter;f_meter]);
    strata=repmat(struct('meter_count',0,'class_threshold',NaN, ...
        'fit_threshold',NaN,'class_n',0,'fit_n',0, ...
        'class_structures',0,'fit_structures',0,'fallback',true), ...
        max_meter,1);
    for meter=1:max_meter
        am=a_meter==meter;fm=f_meter==meter;
        a_n=nnz(am);f_n=nnz(fm);
        a_structures=numel(unique(a_graph(am)));
        f_structures=numel(unique(f_graph(fm)));
        enough=a_n>=cfg.min_stratum_samples && ...
            f_n>=cfg.min_stratum_samples && ...
            a_structures>=cfg.min_stratum_structures && ...
            f_structures>=cfg.min_stratum_structures;
        if enough
            class_threshold=quantile_ceil(a(am),1-alpha);
            fit_threshold=quantile_ceil(f(fm),1-alpha);
        else
            class_threshold=pooled_class;
            fit_threshold=pooled_fit;
        end
        strata(meter)=struct('meter_count',meter, ...
            'class_threshold',class_threshold, ...
            'fit_threshold',fit_threshold,'class_n',a_n, ...
            'fit_n',f_n,'class_structures',a_structures, ...
            'fit_structures',f_structures,'fallback',~enough);
    end
    model=struct('bank_identity',inference_bank.identity, ...
        'candidate_signatures',{inference_bank.candidate_signatures}, ...
        'calibration_signatures',{signatures}, ...
        'calibration_graph_ids',{ {cal_graphs.topology_id} }, ...
        'sigma',sigma,'pooled_class_threshold',pooled_class, ...
        'pooled_fit_threshold',pooled_fit, ...
        'margin_threshold',cfg.separation_threshold, ...
        'strata',strata,'class_scores',a,'fit_scores',f, ...
        'class_meter_count',a_meter,'fit_meter_count',f_meter, ...
        'E_seed',cfg.seed_cfr_E,'A_seed',cfg.seed_cfr_A, ...
        'F_seed',cfg.seed_cfr_F,'E_n',numel(E), ...
        'A_n',numel(A),'F_n',numel(F), ...
        'cal_bank_forward_calls',cal_bank.forward_calls, ...
        'cal_bank_logical_bytes',cal_bank.logical_cache_bytes);
end

function [scores,meter_count,graph_id]=truth_scores(samples,graphs,bank,sigma)
    n=numel(samples);scores=zeros(n,1);meter_count=zeros(n,1);
    graph_id=strings(n,1);
    for i=1:n
        truth=samples(i).truth_global_index;
        p=stage7a4_profile_views(samples(i).observed,bank,truth,5,sigma);
        scores(i)=p.distances;
        meter_count(i)=1+numel(graphs(truth).network.branches);
        graph_id(i)=string(graphs(truth).topology_id);
    end
end

function q=quantile_ceil(values,fraction)
    values=sort(values(:));
    assert(~isempty(values),'stage7a13:EmptyCalibration');
    q=values(min(numel(values),ceil((numel(values)+1)*fraction)));
end
